- kythe/go/extractors/config/extractor.go
- kythe/go/extractors/config/smoke/smoke.go
- kythe/go/extractors/config/smoke/smoke_test.go
Feedback from previous phabricator review D2323.
> Refactor extractor interface to use a container.

- kythe/go/platform/kzip/kzip.go
- kythe/go/platform/kzip/kzip_test.go
To save some boilerplate for scanning a kzip from an open file, add the
top-level kzip.Scan function that handles finding the file size, creating the
reader, and calling its Scan method. Add a test to ensure it works.
> kzip: Add a scan helper.

- kythe/java/com/google/devtools/kythe/util/QualifiedNameExtractor.java
- kythe/javatests/com/google/devtools/kythe/util/QualifiedNameExtractorTest.java
- kythe/proto/common.proto
"printf" is both an identifier and its qualified name.
> Names in the global namespace are still qualified names

- kythe/go/extractors/config/extractor.go
- kythe/go/extractors/config/smoke/smoke.go
- kythe/go/extractors/config/smoke/smoke_test.go
- kythe/go/platform/tools/extraction/extractrepo.go
- kythe/go/platform/tools/extraction/repotester.go
> Support timeout for repo testing.

- WORKSPACE
- tools/build_rules/verifier_test/cc_indexer_test.bzl
> Add support for Bazel 0.14.0

- kythe/cxx/common/index_pack.cc
- kythe/cxx/common/index_pack_test.cc
- kythe/cxx/extractor/cxx_extractor_test.cc
- third_party/llvm/BUILD
- tools/modules/update.sh
- tools/modules/versions.sh
Minimize incremental diffs via regular synchronization with LLVM.
> Update required version of LLVM/Clang

- kythe/go/extractors/config/extractor.go
- kythe/go/platform/tools/extraction/extractrepo/extractrepo.go
Necessary for short term workaround using docker-in-docker in #156.
> Add support for passing in outside temp dir for repo.

- RELEASES.md
- kythe/proto/BUILD
> Add explore.proto to release archive

- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
Partially addresses issue #2834
> Distinguish builtins from fortifying wrappers

- AUTHORS
- CONTRIBUTORS
- kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
Since it was private, it wasn't exposed in some binaries.
> Allow setting the option for emitting JVM signatures.

- WORKSPACE
- kythe/cxx/common/BUILD
- kythe/cxx/common/index_writer.h
- kythe/cxx/common/json_proto.cc
- kythe/cxx/common/json_proto.h
- kythe/cxx/common/kzip_reader.cc
- kythe/cxx/common/kzip_writer.cc
- kythe/cxx/common/kzip_writer.h
- kythe/cxx/common/kzip_writer_test.cc
- kythe/cxx/common/libzip/error.h
- third_party/protobuf.BUILD
Implement and test a C++ KzipWriter
> Add Kzip IndexWriter implementation; update protobuf

- kythe/go/extractors/config/wrapper/BUILD
- kythe/go/extractors/config/wrapper/README.md
- kythe/go/extractors/config/wrapper/gradle_build_modifier.go
- kythe/go/extractors/config/wrapper/gradle_build_modifier_test.go
- kythe/go/extractors/config/wrapper/testdata/modified-gradle.build
- kythe/go/extractors/config/wrapper/testdata/other-gradle.build
- kythe/go/extractors/config/wrapper/testdata/plain-gradle.build
> Add logic to append kythe javac-wrapper to gradle.build files.

- kythe/go/extractors/config/config_parser_test.go
- kythe/go/extractors/config/wrapper/gradle_build_modifier_test.go
- kythe/go/indexer/indexer_test.go
- kythe/go/test/testutil/testutil.go
Refactor existing usages to use that testutil.
Refactor broken existing usages to use that testutil.
> Move the correct formation of golang test data reading into testutil.

- kythe/cxx/common/libzip/error.cc
Not all of the errno codes are present on macOS (and most of those shouldn't be encountered here anyway).
> Remove errno codes missing on macOs

- kythe/cxx/indexer/cxx/testdata/BUILD
- kythe/cxx/indexer/cxx/testdata/rec/rec_implicit_ctor_calls_conversion.cc
Add a disabled test to document that this bug exists for the time being.
> Add manual/disabled test case for #2894

- kythe/cxx/indexer/cxx/testdata/basic/macros_lambda_call.cc
> Add clarifying comment to macros_lambda_call PR

- kythe/go/serving/xrefs/columnar/BUILD
- kythe/go/serving/xrefs/columnar/columnar_encoding.go
- kythe/go/serving/xrefs/columnar/columnar_test.go
- kythe/proto/xref_serving.proto
- kythe/proto/xref_serving_go_proto/xref_serving.pb.go
First part of serving support for #2930.
> Implement the encoding for columnar FileDecorations

- kythe/go/serving/xrefs/BUILD
- kythe/go/serving/xrefs/columnar.go
- kythe/go/serving/xrefs/columnar/columnar_encoding.go
- kythe/go/serving/xrefs/columnar_test.go
> Implement columnar FileDecorations table reader

- kythe/go/serving/pipeline/BUILD
- kythe/go/serving/pipeline/beam.go
- kythe/go/serving/pipeline/beam_integration_test.go
- kythe/go/serving/pipeline/encoding.go
- kythe/go/serving/tools/write_tables/BUILD
- kythe/go/serving/tools/write_tables/write_tables.go
> Implement columnar FileDecorations post-processing

- kythe/cxx/extractor/testdata/extract_verify_stddef_test.cc
- kythe/cxx/extractor/testdata/test_stdin_names_verify.cc
- kythe/cxx/indexer/cxx/testdata/test_index_pack.sh
- kythe/cxx/indexer/cxx/testdata/test_kindex.sh
- kythe/cxx/verifier/verifier_main.cc
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/DefaultPackage.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethod.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Imports.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Inheritance.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Lambdas.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MemberReferences.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Names.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/PluginTests.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/WildcardMethod.java
- kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
- kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt
- kythe/release/release_test.sh
I've opened #2993 and #2994 to track some latent issues exposed by this change.
> Make --check_for_singletons the default and clean up failing tests

- kythe/javatests/com/google/devtools/kythe/analyzers/java/TestPlugin.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/PluginTests.java
> Fix JVM PluginTests edge

- kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/BUILD
> Ignore singletons in jvm_nodes_tests

- kythe/go/serving/xrefs/BUILD
- kythe/go/serving/xrefs/columnar.go
- kythe/go/serving/xrefs/columnar_test.go
- kythe/proto/xref_serving.proto
> Implement columnar CrossReferences serving reader

- kythe/go/serving/pipeline/beam.go
- kythe/go/serving/pipeline/beam_integration_test.go
- kythe/go/serving/pipeline/beamio/leveldb.go
- kythe/go/serving/pipeline/encoding.go
- kythe/go/serving/tools/write_tables/write_tables.go
> Implement columnar CrossReferences post-processing

- kythe/go/serving/pipeline/beam.go
- kythe/go/serving/pipeline/beam_integration_test.go
- kythe/go/serving/pipeline/beam_test.go
- kythe/go/serving/pipeline/beamtest/beamtest.go
- kythe/go/serving/pipeline/encoding.go
- kythe/go/serving/xrefs/columnar.go
- kythe/go/serving/xrefs/columnar_test.go
> Add MarkedSources to columnar CrossReferences

- kythe/cxx/indexer/cxx/KytheGraphObserver.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.h
Tried some different automated refactoring, but it didn't really work
well, so stopping after this file.
> Another round of clang-tidy.

- kythe/docs/asciidoc.bzl
- kythe/docs/schema/java-schema-unit-template.CompilationUnit
> Ensure asciidoc invocation gets data runfiles (for Java)

- kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
The Kotlin indexer uses this helper method.
> Add helper method for Kotlin indexer

- kythe/go/extractors/bazel/extractors.bzl
Also update some doc string text that needed updated anyway.
> Rename the kindex_extractor macro to kzip_extractor.

- kythe/go/extractors/config/base/gradle/gradle.go
- kythe/go/extractors/config/base/mvn/mvn.go
- kythe/go/extractors/config/base/testdata/expected_gradle_config.Dockerfile
- kythe/go/extractors/config/base/testdata/expected_mvn2_config.Dockerfile
- kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
- kythe/go/extractors/config/base/testdata/gradle_config.json
- kythe/go/extractors/config/base/testdata/mvn2_config.json
- kythe/go/extractors/config/base/testdata/mvn_config.json
- kythe/go/extractors/config/runextractor/README.md
- kythe/go/extractors/config/runextractor/constants/constants.go
- kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Also remove an unused method in java extractor.
Fixes #3059
> Make maven/gradle extractors default to using kzip

- kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
- kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
- kythe/java/com/google/devtools/kythe/platform/shared/BUILD
- kythe/java/com/google/devtools/kythe/util/BUILD
- kythe/proto/BUILD
These libraries are needed to build the experimental Kotlin indexer: https://github.com/JetBrains/kotlin-kythe-plugin/compare/master...schroederc:bazel-build
> Open common Java libraries to //visibility:public

- WORKSPACE
- external.bzl
- third_party/googlelog.BUILD
- third_party/libzip.BUILD
This is enough to build Kythe as part of https://github.com/google/anodyne.
> Migrate C++ dependencies to external.bzl

- kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
- kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
- kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
- kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
- kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
- kythe/java/com/google/devtools/kythe/util/BUILD
- kythe/java/com/google/devtools/kythe/util/JsonUtil.java
Extractors and Indexers need to load in the Any types for reading JSON pb files so move the variable out of the extractors package and into a util package
> Move the Kythe default json pb any types

- tools/build_rules/verifier_test/verifier_test.bzl
new_file is deprecated, use the replacement (declare_file)
> Use declare_file instead of new_file

- tools/build_rules/verifier_test/verifier_test.bzl
> Add documentation to verifier_test.bzl

- kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
- kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
- kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
> Java indexer: allow for analysis of multiple compilations

- kythe/web/site/sync_docs.sh
The previous check would always fail on my machine.
> Fix check for asciidoctor gem

- kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java
> ClassFileIndexer: support indexing multiple compilations in kzip files

- kythe/go/extractors/config/base/gradle/gradle.go
- kythe/go/extractors/config/base/mvn/mvn.go
- kythe/go/extractors/config/base/testdata/expected_gradle_config.Dockerfile
- kythe/go/extractors/config/base/testdata/expected_mvn2_config.Dockerfile
- kythe/go/extractors/config/base/testdata/expected_mvn_config.Dockerfile
- kythe/go/extractors/config/base/testdata/gradle_config.json
- kythe/go/extractors/config/base/testdata/mvn2_config.json
- kythe/go/extractors/config/base/testdata/mvn_config.json
- kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
> Point kythe java extractor artifacts at new gcr.io/kythe-public.

- kythe/release/appengine/buildbot/Dockerfile
- kythe/release/appengine/buildbot/master/master.cfg.template
> build(buildbot): upgrade Bazel minimum to 0.18.0

- kythe/go/extractors/config/preprocessor/BUILD
- kythe/go/extractors/config/preprocessor/Dockerfile
- kythe/go/extractors/config/preprocessor/preprocessor.go
Expose at gcr.io/kythe-public/build-preprocessor for use in cloud build
for #3150.
> Add a build-preprocessor docker image for config/preprocessor.

- kythe/cxx/common/BUILD
- kythe/cxx/indexer/cxx/BUILD
- third_party/llvm/src/BUILD
This PR drops some of the easy deps.
> chore: prise away some LLVM deps for #945

- CONTRIBUTORS
Add the rest of the Kythe team to the CONTRIBUTORS file.
> docs: Add team members

- kythe/docs/schema/schema.txt
The example was after a different section.
> fix example for expands/transitive

- tools/modules/update.sh
shellcheck lint errors keep preventing me from pushing anything, so fix them :-)
> fix shell lint warnings in tools/modules/update.sh

- tools/modules/check.sh
> fix: check for sentinel versions of llvm/clang in check.sh

- WORKSPACE
> build: support Bazel version 0.22.0

- kythe/go/platform/tools/kzip_validator/kzip_validator.go
I accidentally closed pull/3379 instead of merging it, this is the same.
> fix: fix a typo in a comment

- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
- kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
- kythe/java/com/google/devtools/kythe/platform/java/helpers/JavacUtil.java
- kythe/java/com/google/devtools/kythe/platform/shared/MetadataLoaders.java
- kythe/javatests/com/google/devtools/kythe/analyzers/jvm/JvmGraphTest.java
Also replaced a couple with `ImmutableList` where I think it's possible.
> chore: remove usage of deprecated `Lists.newArrayList()`

- kythe/typescript/indexer.ts
- kythe/typescript/testdata/index_module/index.ts
- kythe/typescript/testdata/module.ts
- kythe/typescript/testdata/module_with_function.ts
- kythe/typescript/testdata/reexport_importer.ts
- kythe/typescript/testdata/reexporter.ts
See discussion in the commit message.
> use the first token in the file as the module link

- kythe/extractors/gcp/README.md
- kythe/extractors/gcp/examples/gradle.yaml
- kythe/extractors/gcp/examples/guava-android-mvn.yaml
- kythe/extractors/gcp/examples/guava-mvn.yaml
- kythe/extractors/gcp/examples/mvn.yaml
- kythe/go/extractors/gcp/config/converter.go
- kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
- kythe/go/extractors/gcp/config/testdata/gradle.yaml
- kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
- kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
- kythe/go/extractors/gcp/config/testdata/mvn.yaml
`_OUTPUT_GS_BUCKET` to `_BUCKET_NAME`
`_VERSION` to `_COMMIT`
Also stuff output into a gs bucket subdir based on `_CORPUS` and remove
`_CORPUS-` from the file prefix.
> fix: normalize env vars used for input and output to gcp extraction

- setup.bzl
> fix(dev): update the pinned version of Gazelle

- external.bzl
Update to new guava which fixes https://github.com/google/guava/issues/3147
> fix(guava): allow using guava along with modules

- kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
> feat(java_indexer): add MarkedSources for array/generic tapp nodes

- external.bzl
- kythe/extractors/bazel/BUILD
- kythe/extractors/bazel/Dockerfile
- kythe/extractors/bazel/extract.sh
Looking for feedback. 
(Haven't been able to test it yet due to local lein breakage holding up a local build of release, which impacts building this Dockerfile.)
> feat(extraction): use bazelisk in Bazel extractor Dockerfile extraction

- kythe/go/serving/pipeline/pipeline.go
> fix(post_processing): convert DirectoryReply to FileDirectory for serving data

- kythe/go/extractors/govname/BUILD
- kythe/go/extractors/govname/types.go
- kythe/go/indexer/BUILD
- kythe/go/indexer/emit.go
- kythe/go/indexer/facts.go
- kythe/go/indexer/indexer.go
- kythe/go/indexer/testdata/types.go
> feat(go_indexer): add typed edges for bindings

- kythe/go/extractors/govname/types.go
- kythe/go/indexer/emit.go
- kythe/go/indexer/testdata/types.go
> feat(go_indexer): convert variadic function parameters from slice

- kythe/go/indexer/emit.go
- kythe/go/indexer/testdata/types.go
> feat(go_indexer): add receiver type to function types

- kythe/docs/schema/schema.txt
- kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/WildcardMethod.java
> feat(java_indexer): add receiver type to function types

- kythe/go/extractors/config/smoke/BUILD
- kythe/go/extractors/config/smoke/smoke.go
- kythe/go/indexer/emit.go
- kythe/go/indexer/indexer.go
- kythe/go/platform/indexpack/BUILD
- kythe/go/platform/indexpack/indexpack_test.go
- kythe/go/platform/kzip/BUILD
- kythe/go/platform/kzip/kzip.go
- kythe/go/services/link/link.go
- kythe/go/serving/explore/BUILD
- kythe/go/serving/explore/explore.go
- kythe/go/storage/entryset/entryset.go
Use less memory, use better interface where possible.
> chore: map[*]bool, map[string]struct{} -> map[*]struct{}, stringset

- kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DeprecationAnnotations.java
Follow-up to 84a77bf9671833b3044c390f5b565fa7464aefff.
> Emit kythe/tag/deprecated for elements annotated @Deprecated

- kythe/cxx/indexer/proto/proto_graph_builder.cc
- kythe/cxx/indexer/proto/testdata/basic/deprecated.proto
Followup to https://github.com/kythe/kythe/pull/3677.
> fix(proto_indexer): empty deprecation message and addititional test case

- external.bzl
- kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java
> chore: upstream removal of deprecated truth library

- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
- kythe/cxx/indexer/cxx/IndexerASTHooks.h
- kythe/cxx/indexer/cxx/testdata/BUILD
- kythe/cxx/indexer/cxx/testdata/function/function_defines.cc
- kythe/cxx/indexer/cxx/testdata/function/function_member_defines.cc
- kythe/cxx/indexer/cxx/testdata/template/template_fn_defines.cc
Partially addresses issue #3698.
> feat(cxx_indexer): provide defines spans for functions

- external.bzl
This is to support external repositories.
> fix(tooling): allow sample UI dependencies to be disabled

- WORKSPACE
https://github.com/bazelbuild/bazel/releases/tag/0.25.2
> build(bazel): support Bazel 0.25.2

- kythe/go/util/riegeli/compression.go
zstd.Writer is based on the zstd streaming API.  From https://facebook.github.io/zstd/zstd_manual.html:
> - ZSTD_compressContinue() presumes prior input ***is still accessible and unmodified*** (up to maximum distance size, see WindowLog).
The Riegeli Writer cannot uphold this precondition of the zstd streaming
API. Go's GC may collect any input buffer when no longer used by the
client; it cannot see the usage in the C library.
Instead, buffer and compress each zstd chunk individually without
relying on the streaming API.
> fix(tooling): fix #3246

- kythe/docs/exploring-kythe-sample-web-ui.txt
> chore(docs): fix sample ui links

- .bazelrc
- setup.bzl
- tools/build_rules/verifier_test/cc_indexer_test.bzl
Preemptively address https://github.com/bazelbuild/bazel/issues/7793
>  chore(build): apply changes for forthcoming Bazel incompatibilities

- .bazelrc
> chore(bazel): enable compatibility option for string join

- kythe/go/platform/tools/kzip/createcmd/BUILD
- kythe/go/platform/tools/kzip/createcmd/createcmd.go
- kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
Also update encoding flag doc in mergecmd.
> feat(kzip): create permits specifying encoding

- kythe/go/platform/kzip/kzip.go
- kythe/go/platform/tools/kzip/flags/encoding.go
also update docs on constants.
> fix(kzip): EncodingFlag fully implements flag.Getter and flag.Value

- kythe/go/extractors/golang/packages.go
See `go help build` for more info.
> fix(go): -tags is space-separated, not comma

- kythe/typescript/indexer.ts
- kythe/typescript/testdata/function.ts
Symbols now exist for computed names.
> feature(typescript_indexer): index computed function names

- kythe/typescript/kythe.ts
Add typings for Kythe. Ported from
[@types/kythe](https://www.npmjs.com/package/@types/kythe).
> feature(typescript_indexer): add Kythe typings

- kythe/typescript/indexer.ts
We were handling module path resolution correctly previously, but doing
it in a confusing way. Since we only care about paths that define an
entire module, just query to see if the module reference is an entire
source file. If so, return the module path to that source file;
otherwise, we can bail because there is no unique path to reference.
> refactor(typescript_indexer): cleanup module path resolution

- kythe/cxx/indexer/cxx/BUILD
- kythe/cxx/indexer/cxx/DynamicClaimClient.cc
- kythe/cxx/indexer/cxx/DynamicClaimClient.h
- kythe/cxx/indexer/cxx/KytheClaimClient.cc
- kythe/cxx/indexer/cxx/KytheClaimClient.h
- kythe/cxx/indexer/cxx/frontend.cc
Follow-up for #3902 that does the same for KytheClaimClient
> chore(cxx_indexer): pull memcahced-dependent claiming into separate file

- kythe/extractors/bazel/BUILD
- kythe/extractors/bazel/Dockerfile
- kythe/extractors/bazel/bazel_wrapper.sh
- kythe/extractors/bazel/extract.sh
The shell code invoking bazel has gotten complicated so put it in its
own script. This makes the main script a little easier to read and makes
it easier to invoke our custom bazel logic with xargs.
> feat: Add bazel wrapper for external extraction

- kythe/extractors/bazel/extract.sh
Sometimes it may be easier to specify targets to build using a bazel query
rather than listing out explicit targets. Unfortunately, bazel cannot take many
arguments on the command line, so we need to shard our results across several
bazel invocations.
Note that we we changing how the old bazel build invocation happens, so this
change is not backwards compatible.
> feat: use bazel query to find targets to extract

- kythe/go/platform/tools/kzip/infocmd/BUILD
- kythe/go/platform/tools/kzip/infocmd/infocmd.go
- kythe/go/platform/tools/kzip/mergecmd/mergecmd.go
- kythe/go/platform/tools/kzip/viewcmd/BUILD
- kythe/go/platform/tools/kzip/viewcmd/viewcmd.go
- kythe/go/platform/vfs/vfs.go
- kythe/go/platform/vfs/zip/fs.go
The `stdinWrapper` bit at the bottom is kinda ugly - let me know if you see a better way to do that.
> feat(kzip tool): use vfs to allow for changing filesystem impl

- kythe/go/platform/kzip/info/BUILD
- kythe/go/platform/kzip/info/info.go
- kythe/go/platform/tools/kzip/infocmd/BUILD
- kythe/go/platform/tools/kzip/infocmd/info.go
- kythe/go/platform/tools/kzip/infocmd/infocmd.go
this code will be used in another binary.
> refactor(kzip): move KzipInfo creation logic into a library

- kythe/typescript/indexer.ts
- kythe/typescript/tsconfig.json
Enable some additional compiler checks, and make the code pass these
checks.
> typescript: enable more strictness flags

- kythe/go/platform/kzip/info/info.go
This got dropped in d32202ebd959cfabc9da546b2cfe980a842c2a8c
> fix(kzip): populate KzipInfo.total_files in info.go

- kythe/cxx/common/path_utils_test.cc
Notably on OS X /tmp is a symlink for /private/tmp
> fix(cxx_common): fix path_utils_test when tempdir is a symlink

- kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
This reverts commit f37f1c90e1e1a6182edcb595f62362f631a8a0ea.
> Revert "fix(javac-wrapper): use `set -e` to propagate errors (#4042)"

- kythe/docs/kythe-kzip.txt
This is just an attempt to document what we currently have implemented. I can imagine simpler, cleaner algorithms but it's functional.
Addresses #3680
> docs: document the compilation unit digesting algorithm

- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
> feat(java_indexer): add typed edges for `this`/`super`

- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
We are seeing nulls in these data structures. While we work on finding out why, don't crash the indexer when we encounter them.
> fix(java): handle more null data from java

- .bazelrc
> build(bazel): disable persistent worker mode for TypeScript

- kythe/proto/generate_go_protobufs.py
- kythe/release/appengine/buildbot/master/master.cfg
- tools/build_rules/verifier_test/unbundle.py
> style: format Python code

- kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
- kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
- kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
- kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
- kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java
java.util.Optional is preferred, so use it everywhere
> fix(java_common): switch to using java.util.Optional over Guava

- kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
Have I mentioned yet how ready I am to drop JDK8 support?
> fix(java_indexer): cast to base with asPath to support JDK8

- kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
Previously the jar file was listed as the `source_file`, but had no corresponding entry in `required_input`. The jvm extractor scans the jar and records each contained `.class` file as a `required_input`. This change lists each `.class` file in `source_file` instead of the jar.
> fix(jvm extractor): use class files as srcs, not jar

- kythe/java/com/google/devtools/kythe/analyzers/java/AutoValuePlugin.java
- kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
- kythe/java/com/google/devtools/kythe/analyzers/java/Plugin.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AutoValues.java
Supported by schema change in #4177.
> feat(java_indexer): add `generates` edge to generated AutoValue sources

- kythe/cxx/verifier/BUILD
- kythe/cxx/verifier/assertion_ast.h
- kythe/cxx/verifier/assertions.cc
- kythe/cxx/verifier/testdata/just_file_node.dot
- kythe/cxx/verifier/testdata/regex_expected_error.txt
- kythe/cxx/verifier/testdata/singleton_inspect_expected_error.txt
- kythe/cxx/verifier/testdata/test_verifier_regex.sh
- Remove EVar(0x... = ...) wrapper
- Change App(vname, (...)) to vname(...)
- Change EVar(&lt;nullptr&gt;) to &lt;null&gt;
- Quote strings that don't conform to verifier ID syntax.
> Make verifier "?" output similar to goal form

- kythe/java/com/google/devtools/kythe/platform/java/helpers/BlockAnonymousSignatureGenerator.java
methodDecl.sym might be null; log if it is and avoid a NPE.
> chore(java indexer): Handle null pointer

- external.bzl
Context: https://github.com/bazelbuild/bazel/issues/10270
> Mirror all http_archives.

- kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
The temporary directory may be passed in as a relative directory, so convert both parts of the startsWith check to an absolute path.
> fix(java indexer): fix startsWith check

- kythe/web/site/examples.md
> chore(site): fix README link

- kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
When using a local path, we should return the path-as-requested, not the path-translated-to-absolute.
Also, don't do a redundant absolute conversion for the systemRoot (`abspath.resolve(...)` must itself return an absolute path).
> fix(java_common): don't modify return path value

- kythe/cxx/tools/generate_compile_commands/extract_compile_command.cc
- tools/cpp/generate_compilation_database.sh
> fix(cxx_tools): replace sandboxed directory with bazel execroot

- kythe/release/appengine/buildbot/master/master.cfg
> fix(build): fully disable go-gopath builder

- kythe/docs/schema/schema.txt
Discussed: https://github.com/kythe/kythe/issues/4249
> Add optional `language` fact to schema for `file` node.

- kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
There's no real reason for these to be private or package-restricted and can provide some utility for clients of the class.
> feat(java_common): move list/startRead to public access

- kythe/go/serving/xrefs/xrefs.go
> fix(serving): avoid nil when serving data is missing SourceNode

- kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
Refactor runJavaAnalysisToExtractCompilationDetails to make data flow and dependencies more clear by extracting behavior into named functions and classes.
> chore(java_extractor): refactor java extractor for readability

- RELEASES.md
- kythe/release/BUILD
Draft release: https://github.com/kythe/kythe/releases/tag/untagged-65a07fb631dc08e5f198
> release: v0.0.40

- kythe/extractors/openjdk11/extract/extract.go
The internal equivalent facility can't be used until after flags are parsed or it panics, so add an indirection for the runfiles-relative paths.
> fix: indirect runfiles path in opendjk11 extractor

- RELEASES.md
- kythe/release/BUILD
Draft release: https://github.com/kythe/kythe/releases/tag/untagged-b9dcbee8adfd21bd2255
> Release v0.0.42

- .bazelrc
- third_party/go/BUILD
- tools/build_rules/llvm/llvm.bzl
> fix(build): fix uses of empty globs

- external.bzl
* I broke this in https://github.com/kythe/kythe/pull/4419
> fix(build): add dep for new version of bazelisk

- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/BUILD
Export the JDK test kzip for use in fingerprint.
> fix(java_tests): export jdk_kzip

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-0ea73217f2adff0cb5c3#
> Release v0.0.44

- kythe/go/extractors/config/runextractor/cmakecmd/BUILD
- kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
Patched from https://r.android.com/1356137
> build(cmakecmd): remove dep on go-uuid

- kythe/typescript/test.ts
Fixes https://github.com/kythe/kythe/pull/4591#discussion_r456686833
> Use template literal instead of concating number and string

- kythe/typescript/yarn.lock
- package-lock.json
- package.json
Address the lodash vulnerability.
> chore: update TS deps

- kythe/rust/fuchsia_extractor/src/bin/main.rs
It turns out that Rust's save-analysis JSON files sometimes are
generated as garbled.  While unsure why this is the case, we should
not stop the entire extraction pipeline because a few files came out
not well-formed.
This change does the following:
- Makes a single failure non-breaking.
- Factored out a function `lenient_process_files` to allow us to print
any error content but proceed with extraction.
- Adds a --quiet flag to suppress non-error output, which can sometimes
be overwhelming.
> feat(rust): Makes the extractor more robust

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-22a6593104cf59a1a721
> release: v0.0.46

- kythe/rust/indexer/src/indexer/analyzers.rs
Most user-generated `rust_library` and `rust_binary` rules don't incorporate the `version` option, which can potentially cause collisions with the disambiguators used in the signature. This PR adds the crate name alongside the disambiguators to cover this case.
> fix(rust): Add crate name to generated signatures

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-ce5b26f7a70f5b40a244
> Release v0.0.47

- kythe/cxx/indexer/textproto/analyzer.cc
StringPiece doesn't exist in google3, so this causes trouble on import.
> fix(textproto): remove StringPiece override of CreateAndAddAnchorNode

- kythe/extractors/gcp/examples/restcheck/rest_auth_check.go
- kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
- kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go
- kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
- kythe/go/extractors/config/runextractor/mavencmd/mavencmd.go
- kythe/go/extractors/gcp/config/yamlgen/yamlgen.go
- kythe/go/platform/tools/extraction/extractrepo/extractrepo.go
- kythe/go/platform/tools/extraction/repotester/repotester.go
Make flag checking names more consistent
> chore: s/verifyFlags/checkFlags/ for internal consistency

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-c0f2f2f0f236accdd0b4
Fixes #4675
> Release v0.0.48

- WORKSPACE
- kythe/proto/BUILD
- kythe/typescript/BUILD
- package-lock.json
- package.json
- setup.bzl
- tools/git/BUILD
> chore: update rules_nodejs and TS deps

- kythe/cxx/indexer/cxx/testdata/BUILD
This test may take close to the 'small' test timeout.
> chore(cxx): increase test timeout

- kythe/go/platform/vfs/BUILD
- kythe/go/platform/vfs/vfs_test.go
Fixes #4703 (the test won't *pass* on windows, but the clone will at least be possible).
> fix(go_test): dynamically create files for vfs_test

- external.bzl
- setup.bzl
- third_party/libzip.BUILD
- third_party/libzip/BUILD
- third_party/libzip/genziperrs.py
- tools/build_rules/build_event_stream/repo.bzl
There were some snags updating a few of the others, figured it best to do the updates incrementally.
> chore: update some dependencies

- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AbstractClass.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
> feat(java_indexer): tag abstract methods/classes as such

- kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
> Yet another invalid escape sequence

- kythe/cxx/extractor/BUILD
- kythe/cxx/extractor/bazel_artifact.h
- kythe/cxx/extractor/bazel_artifact_reader.cc
- kythe/cxx/extractor/bazel_artifact_reader.h
- kythe/cxx/extractor/bazel_artifact_selector.cc
- kythe/cxx/extractor/bazel_artifact_selector.h
- kythe/cxx/extractor/bazel_artifact_selector_test.cc
- kythe/proto/BUILD
- kythe/proto/bazel_artifact_selector.proto
- tools/build_rules/build_event_stream/repo.bzl
Also Aspect support and type-erased value type wrapper for them.
> feat(cxx_common): extend bazel artifact selection to allow stateful selectors

- kythe/release/appengine/buildbot/Dockerfile
- kythe/release/appengine/buildbot/buster-backports.list
- kythe/release/appengine/buildbot/llvm-toolchain.list
- tools/arc/linter.sh
> chore: update buildbot to use a non-ancient clang-format

- kythe/go/util/tools/write_extra_action/write_extra_action.go
For C++, command line arguments aren't available to Starlark.  To work around this give `write_extra_action` some additional knowledge of `CppCompileInfo` specifically to fill out `tool` `compiler_option` and `source_file` fields.
> feat(go_utils): allow filling in cpp-specific information

- kythe/extractors/bazel/Dockerfile
Version bump to make the bazel extractor docker image build.
> chore: Update bazel extractor docker file

- kythe/cxx/verifier/BUILD
> fix(cxx_verifier): properly attribute srcs/hdrs to avoid ODR

- kythe/go/serving/pipeline/BUILD
- kythe/go/serving/pipeline/beam.go
- kythe/go/serving/pipeline/beam_test.go
This will solve a problem if pipeline gets run using multiple instances.
> Merge FileDecorations in Beam pipeline.

- kythe/go/serving/graph/columnar.go
Make sure the database iterator is closed.
This is mostly indentation changes. It's much easier to review with https://github.com/kythe/kythe/pull/4859/files?w=1
> Close the graph columnar db iterator.

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-9b9f942c34a990d5bbb7
> release: v0.0.50

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-e685d4e7c5cc4086462a
> release: v0.0.51

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-1df58dae87b2be5a9837
> release: v0.0.52

- kythe/release/cloudbuild/lint.yaml
- kythe/release/cloudbuild/pre-commit/Dockerfile
- kythe/release/cloudbuild/pre-commit/cloudbuild.yaml
- kythe/release/cloudbuild/pre-commit/go
This is done as a separate trigger in Cloud Build rather than a different step because it's optional, unlike the tests.
> feat(build): add image and cloudbuild configs for pre-commit

- kythe/cxx/common/indexing/KytheGraphRecorder.cc
- kythe/cxx/common/indexing/KytheGraphRecorder.h
documented in the schema at https://kythe.io/docs/schema#reffile
> feat(cxx_indexer): add kRefFile to EdgeKinds

- kythe/rust/extractor/src/bin/cli.rs
- kythe/rust/extractor/src/bin/extractor.rs
- kythe/rust/extractor/src/bin/save_analysis.rs
- kythe/rust/extractor/src/lib.rs
- kythe/rust/extractor/tests/integration_test.rs
- kythe/rust/extractor/tests/test.rs
- kythe/rust/fuchsia_extractor/src/bin/main.rs
- kythe/rust/fuchsia_extractor/src/kzip.rs
- kythe/rust/indexer/src/bin/main.rs
- kythe/rust/indexer/src/indexer/analyzers.rs
- kythe/rust/indexer/src/indexer/entries.rs
- kythe/rust/indexer/src/indexer/mod.rs
- kythe/rust/indexer/src/indexer/offset.rs
- kythe/rust/indexer/src/indexer/save_analysis.rs
- kythe/rust/indexer/src/providers.rs
- kythe/rust/indexer/src/writer.rs
- kythe/rust/indexer/testdata/struct.rs
- kythe/rust/indexer/testdata/type.rs
- kythe/rust/indexer/testdata/xrefs.rs
- kythe/rust/indexer/testdata/xrefs/main.rs
- kythe/rust/indexer/tests/array_writer.rs
- kythe/rust/indexer/tests/providers.rs
`find kythe/rust -iname '*.rs' -exec rustfmt {} \;`
> fix(rust_indexer): rustfmt everything

- kythe/typescript/indexer.ts
In TypeScript 4.3, some DOM/compiler interfaces has changed.
> fix(typescript_indexer): fix compilation issues with TypeScript 4.3

- kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DefaultCorpus.java
when --use_compilation_corpus_as_default is enabled
> feat(java_indexer): place builtins in the compilation unit corpus

- kythe/typescript/BUILD
Merge an internal LSC change externally.
> chore: mark jasmine use testonly

- kythe/data/simple_vnames.json
Change simple_vnames.json to produce relative vnames with a distinct root for absolute paths.
> chore: update simple_vnames.json to emit relative paths

- kythe/rust/extractor/BUILD
- kythe/rust/extractor/extractor_script.sh
- kythe/rust/extractor/extractor_test.bzl
- tools/build_rules/verifier_test/rust_indexer_test.bzl
> fix(rust_extractor): fix running the Rust extractor on macOS

- kythe/rust/extractor/src/bin/save_analysis.rs
> fix(rust_extractor): process env vars and compiler args passed to wrapper

- kythe/cxx/indexer/proto/file_descriptor_walker.cc
- kythe/cxx/indexer/proto/testdata/corner_cases/gen-proto-dest.proto
Fix a couple of issues which surfaced during import.
> chore: minor fixes for import

- kythe/go/platform/kcd/memdb/memdb_test.go
- kythe/go/platform/kcd/testutil/testutil.go
Add another test for interaction between written units and files.
> test: use testing package for kcd tests

- kythe/rust/fuchsia_extractor/src/bin/main.rs
This change adds a flag --withrlibs, false by default, which when set
causes the extractor to package rlibs files for compilation replay.
However, since the current rust indexer does not use that analysis method,
the default behavior is to *not* package these files.
Fixes: #5084
> [fuchsia_extractor] Don't pack rlib files by default

- RELEASES.md
- kythe/release/BUILD
New release for fuchsia_extractor update
> release: v0.0.54

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-439f5268b389479ddf63
Fixes #5102
> release: v0.0.55

- kythe/release/Dockerfile
Uses correct javac file from third_party dir
> Fix file in ADD command

- kythe/go/services/cli/commands_xrefs.go
> feat: include edge in output of `kythe xrefs` for definitions and references

- kythe/go/serving/xrefs/xrefs.go
This will help with turnup of new labels.
> feat(serving): offer a callback to rewrite edge labels

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-103e3cf6927d34dc3ec5
> Release v0.0.56

- external.bzl
Bump the version again for more log4j fallout.
> chore: update Flogger again

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-6c9144e89734503c5e33
> Release v0.0.57

- tools/build_rules/extraction.bzl
Import a file change that was done internally
> fix: import internal change

- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/java/com/google/devtools/kythe/analyzers/java/TreeContext.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DiamondOperations.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethodRef.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Generics.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericsAbs.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MemberReferences.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Scopes.java
> fix(java_indexer): use ref/id edges for class references in new expressions

- RELEASES.md
- kythe/release/BUILD
Draft release at: https://github.com/kythe/kythe/releases/tag/untagged-5f6f0e99c3268f192bc2
> Release v0.0.59

- kythe/typescript/indexer.ts
> fix(typescript_indexer): fix lint issue

- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.cc
- kythe/cxx/indexer/cxx/marked_source.cc
- tools/build_rules/verifier_test/cc_indexer_test.bzl
This is from an "SRE" perspective: a non-owner of the code trying to navigate the logs. Directionally serious: if someone cared about these they'd be fixed, and these have existed unattended for years, and don't seem likely to get much love soon.
> fix(cxx): be quiet about things that no one cares about

- kythe/docs/schema/schema.txt
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Interfaces.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/package-info.java
Serving is not yet ready for this. 
You were right, zrlk, we should have flag-gated this.
> fix(java): rollback recent annotation ref/id changes

- tools/build_rules/verifier_test/cc_indexer_test.bzl
This should be the final PR for this stupid import.
> chore: remove unused entry from load statement

- kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
This now uses the same logic as the java extractor:
https://github.com/kythe/kythe/blob/4aff6ac52c27de4d306b73982b343d6dcae4c2a7/kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java#L297-L313
> feat(jvm_extractor): assign a corpus to compilation units

- cargo-bazel-lock.json
- external.bzl
- kythe/rust/extractor/src/lib.rs
Upgrades Rust version to match internal version and fixes reference.
> chore(rust_common): bump version to 2022-07-27 and fix bug

- kythe/cxx/indexer/proto/source_tree.cc
The signature of Open() is changing to `absl::string_view`. Apply some changes to accommodate this.
> chore: preparatory cleanups for a signature change to absl::string_view

- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
This is a little bizarre because BuildNodeIdForDecl should be dereferencing member templates, but apparently the behavior doesn't work in production. Reintroduce the logic to try and figure out what's going on.
> fix(cxx_indexer): reintroduce dereferencing to BuildNodeIdForTemplateName

- kythe/java/com/google/devtools/kythe/extractors/java/standalone/ReflectiveJdkCompatibilityShims.java
A little overzealous in the unchecked suppression.
> chore: remove unnecessary suppression

- .bazelrc
- buildenv/java/BUILD
- setup.bzl
> chore: update rules_go and fix visilibity for Bazel changes

- kythe/go/serving/xrefs/xrefs.go
This ensures that a soft deadline returns xrefs.
> fix(serving): clear empty xref sets after all reads

- kythe/cxx/common/indexing/KytheGraphRecorder.cc
- kythe/cxx/common/indexing/KytheGraphRecorder.h
- kythe/cxx/indexer/cxx/GraphObserver.h
- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.h
- kythe/cxx/indexer/cxx/testdata/BUILD
- kythe/cxx/indexer/cxx/testdata/rec/rec_class_visibility.cc
> feat(cxx): emit member visibility facts

- RELEASES.md
- kythe/release/BUILD
https://github.com/kythe/kythe/releases/edit/untagged-abe7b01c3b7648bb31eb
> release: v0.0.61

- kythe/extractors/bazel/BUILD
- kythe/extractors/bazel/gcb.yaml
- tools/build_rules/docker.bzl
Haven't tried this out yet, looking for feedback on the approach
> chore: enable building kythe extractor docker image via GCB

- kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
> chore(java): delete unused method FileVnames.fillInWith()

- kythe/java/com/google/devtools/kythe/platform/shared/FileDataCache.java
To fix test with Bazel@Head: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2908#0186de4b-de3f-421a-9df2-59beeb9aca93
> Use ImmutableMap in place of Map

- kythe/go/util/span/span.go
This is causing issues in prod.  As I work out a minimal repro, let's turn this off.
> fix(serving): don't checklines in diffmatchpatch

- kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk9CompatibilityShims.java
This is in preparation to see if we can support multijars
> chore: match interface return type

- kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
> chore: add runtime dep

- external.bzl
- kythe/cxx/extractor/bazel_artifact_selector.cc
- tools/build_rules/build_event_stream/repo.bzl
Better accommodate unhandled oneof cases in uri conversion.
> chore: update build_event_stream handling

- kythe/testdata/indexers/proto/testdata.proto
for testing purposes, I need to have two messages that contain a field of the same name and type
> test(proto): add another example message to testdata.proto

- kythe/cxx/indexer/cxx/KytheVFS.cc
> fix(cxx_indexer): ensure the working directory is absolute

- kythe/java/com/google/devtools/kythe/platform/java/helpers/21/JdkCompatibilityShimsImpl.java
> chore(java_indexer): for loop variable field got renamed back to what it was

- kythe/cxx/indexer/textproto/analyzer.cc
- kythe/cxx/indexer/textproto/plugin.h
Extend plugin interface with AnalyzeIntegerField method to support annotations for integer fields.
> Add plugin entry point for integer fields.

- kythe/cxx/indexer/cxx/GoogleFlagsLibrarySupport.cc
- kythe/cxx/indexer/cxx/GraphObserver.h
- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.cc
- kythe/cxx/indexer/cxx/KytheGraphObserver.h
- kythe/web/site/contributing.md
I also fixed a tiny typo on the contributing page.
> refactor: Remove SourceRange from recordCompletion

- kythe/go/extractors/bazel/BUILD
- kythe/go/extractors/bazel/settings.go
- kythe/go/extractors/bazel/utils.go
- kythe/go/util/datasize/datasize.go
Allow filtering by file size in Bazel extractor.
> feat(extractor): add a flag for filtering on input file size

- kythe/extractors/bazel/extractors.bazelrc
- kythe/release/release.BUILD
Remove two remnants of Rust that were missed in #5802
> fix(rust_common): finish removing rust

- tools/build_rules/verifier_test/cc_indexer_test.bzl
buildifier keeps complaining about this...
> chore(cc_indexer_test): add module docstring

- kythe/cxx/indexer/cxx/testdata/BUILD
- kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
- tools/build_rules/extra_aspects/BUILD
- tools/build_rules/extra_aspects/actions.bzl
- tools/build_rules/extra_aspects/config.bzl
- tools/build_rules/extra_aspects/cxx/BUILD
- tools/build_rules/extra_aspects/cxx/aspect.bzl
- tools/build_rules/extra_aspects/cxx/config.bzl
- tools/build_rules/extra_aspects/cxx/rules.bzl
- tools/build_rules/extra_aspects/extra_actions.bzl
- tools/build_rules/verifier_test/cc_indexer_test.bzl
This allows using cc_library targets directly in verifier tests.
> feat(dev): add aspect-based implementation of extra actions for tests

- kythe/java/com/google/devtools/kythe/analyzers/java/AutoValuePlugin.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
- kythe/java/com/google/devtools/kythe/analyzers/java/Plugin.java
- kythe/javatests/com/google/devtools/kythe/analyzers/java/TestPlugin.java
Add a name so we can record stats about failures/etc. for java indexer plugins
> chore(java_indexer): add name for java plugins

- RELEASES.md
- kythe/release/BUILD
It's been a while since our last release (July 2023), so there are a lot of release notes. I trimmed it down a bit, but left most of it there.
> Release v0.0.64

- kythe/release/cloudbuild/website-updater/Dockerfile
- kythe/release/cloudbuild/website-updater/cloudbuild.yaml
See Cloud Build "trigger" here: https://console.cloud.google.com/cloud-build/triggers;region=global/edit/24ce2421-6f4e-4d6c-a715-217d714cbe31?project=kythe-repo
And a recent successful build/deploy here: https://console.cloud.google.com/cloud-build/builds;region=global/699028f6-4cec-4cc5-a6b8-76fd8dc662a9?project=kythe-repo
> feat(website): add cloudbuild config for auto-updating website

- kythe/go/serving/xrefs/xrefs.go
- kythe/proto/xref.proto
Clarify the behavior of the CrossReferences RPC
> Clarify documentation about Cross reference service and node merging

- kythe/cxx/indexer/cxx/IndexerASTHooks.cc
- kythe/cxx/indexer/cxx/IndexerASTHooks.h
- kythe/cxx/indexer/textproto/analyzer.cc
- kythe/cxx/indexer/textproto/plugin.h
- setup.bzl
- third_party/llvm-bazel-glob.patch
These are some changes were submitted in Google and are now fed back into the open source repository.
> Upstreaming changes

- .bazelrc
Fixes https://github.com/kythe/kythe/issues/6135
> chore: explicitly enable workspace, default is changing

- kythe/cxx/common/json_proto.cc
Names will return string_view.
> chore: adapt to protobuf API changes

- kythe/cxx/indexer/cxx/KytheGraphObserver.cc
See llvm-project/clang/include/clang/Basic/AArch64SVEACLETypes.def
> Update arm builtin types

- kythe/go/platform/kcd/kcd.go
- kythe/go/platform/kcd/kzipdb/BUILD
- kythe/go/platform/kcd/kzipdb/kzipdb.go
- kythe/go/platform/kcd/locked/locked.go
- kythe/go/platform/kcd/memdb/memdb.go
This PR adds the interfaces changes in KCD dbs for introducing FetchCUSelector RPC.
> Add interface changes in KCD for introducing FetchCUSelector RPC.

- kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
- kythe/java/com/google/devtools/kythe/analyzers/java/JavaNode.java
- kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
- kythe/java/com/google/devtools/kythe/analyzers/java/ResolvedAutoValue.java
Add missing @CanIgnoreReturnValue annotations #6199
> Add missing @CanIgnoreReturnValue annotations
