kythe/cxx/extractor/testdata/test_common.sh

Fixes https://github.com/bazelbuild/bazel/issues/1848.

Use a sub-directory inside TEST_TMPDIR as the OUT_DIR for tests.

---

kythe/go/util/cmdutil/BUILD
kythe/go/util/cmdutil/cmdutil.go
kythe/go/util/cmdutil/cmdutil_test.go

This package contains shared logic for setting up command-line tools using the
subcommands package. The cmdutil.Info type handles reporting name, synopsis,
and usage information, and provides some default behaviour for other methods of
the required interface.

Add package cmdutil.

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/basic/alias_root_transitive.cc

Look through ElaboratedTypes that elaborate typedefs when crawling the alias chain.

---

kythe/go/platform/tools/extraction/repotester.go

TIL that the number 100 contains three digits, not two.

Fix alignment.

---

kythe/go/platform/tools/extraction/extractrepo.go

This now takes a config.Repo instead of explicit arguments.

Bug fix: Fix the parameters to an ExtractRepo call.

---

kythe/go/extractors/config/smoke/smoke.go
kythe/go/extractors/config/smoke/smoke_test.go
kythe/go/platform/tools/extraction/repotester.go

Allows better eyeballing of e.g. empty repos for culling from test list,
or other obvious problems.

Add download/extract counts as well.

---

kythe/go/platform/kcd/kzipdb/BUILD
kythe/go/platform/kcd/kzipdb/kzipdb.go
kythe/go/platform/kcd/kzipdb/kzipdb_test.go

Package kzipdb provides an implementation of the kcd.Reader interface that
consumes data from a kzip file. This implementation does not allow writing.

Implement a kcd.Reader around a kzip file.

---

WORKSPACE
kythe/cxx/common/indexing/BUILD
tools/build_rules/verifier_test/cc_indexer_test.bzl
tools/build_rules/verifier_test/toolchain_utils.bzl
tools/cpp/CROSSTOOL.tpl
tools/cpp/clang_configure.bzl

This reworks how the cc_indexer_test rules get access to the configuration and builtin include libraries as well as updating to a newer version of CROSSTOOL.tpl.
Fragments are deprecated in favor of toolchains which aren't ready yet.
Accompanying this are some additional changes required for macOS.

Prepare for forthcoming changes to Bazel toolchains/fragments

---

kythe/go/extractors/bazel/settings.go

When setting up flags for a Bazel extractor, write the usage message to the
writer owned by the flag set, instead of defaulting to stderr. The default is
stderr anyway, but this allows the caller to choose.

Cleanup: Write usage to flagset output instead of os.Stderr.

---

kythe/go/platform/tools/extraction/repotester.go

Now that we're running this on many, many more repositories, prefer a
different format.

Move to csv for repo testing.

---

kythe/go/platform/kcd/kzipdb/kzipdb.go
kythe/go/platform/kcd/kzipdb/kzipdb_test.go

Since the index field of an indexed compilation may legally be unset, use the
accessor to fetch its revisions list.

Bug fix: Avert a crash reading a nil proto field.

---

kythe/go/platform/tools/pack2kzip/BUILD
kythe/go/platform/tools/pack2kzip/pack2kzip.go

The pack2zip tool scans the contents of an indexpack directory or ZIP file, and
repacks it into a .kzip archive. Each compilation and required input file is
copied to the target format as-is, save that an optional revision marker may be
added.

Add a command-line tool to convert indexpack to kzip.

---

kythe/go/platform/tools/pack2kzip/BUILD
kythe/go/platform/tools/pack2kzip/pack2kzip.go

Allowing writes to proceed concurrently with reads reduces copying time by
about half.  Copying a sample indexpack containing ~4700 compilation records
and ~15200 unique files gives:
Format: Dir     ZIP
======= ------- -------
Before: 4m34.8s 4m41.2s
After:  2m29.1s 2m27.7s
-45%    -47%

pack2kzip: Copy concurrently.

---

kythe/go/util/schema/BUILD
kythe/go/util/schema/indexdata.go
kythe/go/util/schema/mkdata/mkdata.go
kythe/go/util/schema/schema.go
kythe/go/util/schema/update_data.sh
tools/build_rules/testing.bzl

Addresses #54.
Prior to this change, the schema package has some logic in schema.go that
depends on a Bazel-generated file. This prevents the package from being
go-gotten unless we check in that file. So we'll check a copy in.
To do this, update the existing genrule, which worked by concatenating the text
proto directly into a source file, with a tool that generates Go source that
doesn't require the text proto. The file emitted by the new tool is independent
of the rest of the package, and includes both the constant maps (read from the
text proto at compile time) and the functions that use them.  This also makes
it easier to update the file without invoking Bazel.
This change also adds a rule that will fail to build if the generated code used
by the Bazel rule for the schema library …

Make the schema package support "go get" again.

---

tools/build_rules/testing.bzl

I put these attributes into the signature, but didn't manage to get them all
the way to the test.

Plumb size & tags attributes correctly in the file_diff_test macro.

---

kythe/go/platform/analysis/local/BUILD
kythe/go/platform/analysis/local/local.go

Rename KIndexQueue to FileQueue, and make it support .kzip files as well as
.kindex files. Get rid of the functional options in favour of a simpler struct.

Update local driver queue to handle kzip files.

---

kythe/go/util/schema/BUILD
kythe/go/util/schema/mkdata/BUILD

To maintain the conventional build-package to go-package organization, we need
this to have its own BUILD file.

schema: Give the mkdata tool its own BUILD file.

---

kythe/go/extractors/cmd/gotool/BUILD
kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/indexer/testdata/go_indexer_test.bzl

Allow the gotool extractor to write output to a kzip file in addition to
.kindex and indexpack format. Eventually we will get rid of the other two
formats, but for now this is just adding the new format.

Add kzip support to the gotool extractor.

---

RELEASES.md

Add mention of Objective C and TypeScript. Fix various cosmetic capitalization
and punctuation and formatting bits.

Tweaks and additions to the 0.0.27 pre-release notes.

---

kythe/typescript/package.json
kythe/typescript/yarn.lock

There is no code change necessary to support TypeScript 2.8.3, but
this is the version used within Google so it's good to match just
to be sure.

typescript: update compiler to 2.8.3

---

kythe/typescript/indexer.ts

The first diff, with weird wrapping is unfortunate (I filed a bug about
it) but in general we always autoformat and the other changes are good.
This reduces the diff of subsequent changes.

typescript: run the autoformatter

---

kythe/go/extractors/bazel/extractor_test.go
kythe/go/extractors/bazel/settings.go
kythe/go/extractors/bazel/utils.go

As part of migrating to a fixup interface that uses the compilation unit
directly, update the FindSourceArgs constructor to return the new style.

Make FindSourceArgs return a new-style fixup.

---

kythe/go/languageserver/document_test.go
kythe/go/languageserver/languageserver_test.go
kythe/go/languageserver/pathmap/mapper_test.go
kythe/go/services/cli/commands_xrefs.go
kythe/go/services/link/link_test.go

No functional changes, only some semantics-preserving cleanup.

Apply simplifications found by gofmt -s.

---

kythe/go/platform/tools/pack2kzip/BUILD
kythe/go/platform/tools/pack2kzip/pack2kzip.go

When copying large packs, the file copying stage can exhaust available threads.
Add a throttle to keep that from happening.

pack2kzip: Be a little bit less concurrent.

---

kythe/go/platform/kzip/kzip.go

When opening a reader, pre-sort the file entries by name, allowing the Lookup,
Scan, and Open methods to work more quickly.

kzip: Use binary search to speed up reads and scans.

---

kythe/go/extractors/bazel/extractor.go
kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

Update the one remaining use of the Fixup field to use FixUnit instead, and
delete the Fixup field from the type entirely.

Obsolete and remove the Fixup field of the bazel.Extractor.

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt

Previously, the Java indexer would emit a "generated" JVM node with a signature like `foo.bar.Generic<T>.member` while the JVM indexer would emit the same node with the signature `foo.bar.Generic.member`.  
This commit fixes this by modifying the Java indexer to emit the unadorned name that the JVM indexer emits.
This seems like the right direction to change, because generics are entirely a language feature, and don't exist at the JVM level.  Also, the Java indexer already emits the unadorned name for the class itself. It was just the members that were mismatched.

Fix generic class member JVM names.

---

kythe/java/com/google/devtools/kythe/util/JsonUtil.java

When initializing in main(), we call`usingTypeRegistry()`, which throws `IllegalArgumentException` if called a second time.
However we may in fact call main multiple times, e.g., if running kythe in a nailgun server.
This change works around the problem by short-circuiting the `usingTypeRegistry()` call if the same type registry is already in use. It will trigger the same `IllegalArgumentException` however, if you try to change the type registry to some other one.

Allow JSON initialization to run multiple times.

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt

Previously we hard-coded j.l.Object in the source indexer, which did not match what the binary indexer emits.
Tests that this works for both simple and multiple-bound generics (in the latter case, the first bound is the erasure, by definition).

Represent type params by their erasure in JVM names.

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/jvm/JvmGraph.java

This ensures all JvmGraph clients work equivalently.

Push JVM reference type normalization from #118 into core JvmGraph

---

kythe/go/extractors/config/extractor.go
kythe/go/extractors/config/smoke/smoke.go
kythe/go/extractors/config/smoke/smoke_test.go
kythe/go/platform/tools/extraction/extractrepo/extractrepo.go

Opens up future possibility to do a simple copy from local disk if we already have the repo living somewhere.
I'm not super sold on the exact interface here, but this brings us one step closer to nixing a lot of the copying work.
Slight added benefit: consolidating the git clone logic in extractor instead of replicating it in smoke harness as well.

Rework interface on extractor to not hard code git clone.

---

kythe/go/serving/pipeline/pipeline.go
kythe/go/serving/tools/write_tables/BUILD
kythe/go/serving/tools/write_tables/write_tables.go
kythe/go/util/disksort/disksort.go

Since the Snappy Reader/Writers have a static buffer size, remove the IOBufferSize option and stick with what Snappy uses as a buffer size.

disksort: properly flush snappy.Writer

---

kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/platform/kzip/kzip.go
kythe/go/platform/kzip/kzip_test.go

Add a new constructor NewWriteCloser, which behaves as the normal constructor
save that it takes an io.WriteCloser instead of an io.Writer, and arranges that
when closing the kzip writer, the underlying io.WriteCloser will also be closed.
This simplifies use of the library with files that must otherwise be closed
explicitly. Tests are included to verify that error propagation does the
sensible thing.

kzip: Allow propagating Close.

---

kythe/go/indexer/cmd/go_indexer/BUILD
kythe/go/indexer/cmd/go_indexer/go_indexer.go

As part of the ongoing work to replace .kindex files and indexpacks, add the
ability to add .kzip input to the Go indexer. For now, the other formats are
still supported.

go_indexer: Add the ability to read kzip inputs.

---

kythe/go/extractors/bazel/utils.go
kythe/go/extractors/cmd/bazel/extract_kindex/extract_kindex.go

As part of the migration from kindex files, update the extract_kindex tool to
support writing kzip output. We will eventually want to rename the binary too,
but that can be a separate step; for now, it continues to support kindex also.

extract_kindex: Add support for writing kzip files as output.

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt

Instead of hand-crafted logic, this defers to the compiler's own data structures, which do the right thing in multiple cases, such as type erasure, synthetic inner class ctor params, generics in method signatures, etc.
This change adds several test cases.
This supersedes https://github.com/google/kythe/pull/139 and replaces logic previously implemented in https://github.com/google/kythe/pull/120 and https://github.com/google/kythe/pull/118.

Obtain JVM (aka "external") names in a principled way.

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/jvm/JvmGraph.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
kythe/javatests/com/google/devtools/kythe/analyzers/jvm/JvmGraphTest.java
kythe/javatests/com/google/devtools/kythe/analyzers/jvm/testdata/jvm_nodes.kythe_verifier.txt

Previously we emitted `pkg.Outer.Inner`, but at the JVM level
there are no inner classes, and `Inner` compiles to a top-level
class in pkg `pkg` named `Outer$Inner`. So we should emit accordingly.
The new `methodWithInnerParam` test exposes the issue - prior to this
change, the source and binary indexers would have emitted different
method signatures.

Fix JVM names of inner classes.

---

kythe/go/serving/pipeline/BUILD
kythe/go/serving/pipeline/beam.go
kythe/go/serving/pipeline/beam_test.go
kythe/go/serving/pipeline/beamtest/BUILD
kythe/go/serving/pipeline/beamtest/beamtest.go
kythe/go/serving/tools/write_tables/BUILD
kythe/go/serving/tools/write_tables/write_tables.go

Unregistered types/functions become runtime panics on remote Beam runners.

Add tests to ensure all used proto types and functions are registered with Beam

---

kythe/go/platform/kzip/kzip.go

If the zip archive contains a root/units/ entry to represent the base
directory, ensure the Scan function doesn't attempt to read the file, as it is
not a meaningful unit. Such directories are never created by this library, but
may be inserted by other generators.

kzip: tolerate an empty units directory entry

---

third_party/beam/BUILD
third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go

The passert package matches its input collections based on their
ordering which can be non-deterministic when the CoGBK implementation is
parallel.

Fix #157 flaky //third_party/beam:gbk_test

---

WORKSPACE

```
AutoCommon:  0.8     -> 0.10
AutoService: 1.0-rc3 -> 1.0-rc4
AutoValue:   1.5.2   -> 1.5.4
ErrorProne:  2.2.0   -> 2.3.1
GSON:        2.8.4   -> 2.8.5
Guava:       25.0    -> 25.1
HTMLTypes:   1.0.7   -> 1.0.8
RE2J:        1.1     -> 1.2
Truth:       0.36    -> 0.41
```

Update Google Java dependencies

---

kythe/go/extractors/config/config_parser.go
kythe/go/extractors/config/extractor.go
kythe/go/platform/tools/extraction/extractrepo/Dockerfile
kythe/go/platform/tools/extraction/extractrepo/extractrepo.go

Yet another affordance for docker-in-docker described in #156, which we
probably should get rid of long term.  For the short/medium term though,
this makes calling the eventual docker image a lot nicer, since we can
specify output to arbitrary top-level directories.

Add copy output step to the end of kythe maven extraction.

---

kythe/go/serving/xrefs/BUILD
kythe/go/serving/xrefs/xrefs_test.go

`tickets` is written, but never read.

xrefs_test.go: remove dead code and associated imports

---

kythe/typescript/indexer.ts

This helps clean up the warning messages from the ts indexer to make it easier to see real warnings.

Reduce todo log level from warn to log

---

kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java

This helps to create anchors from other languages. For example JavaScript indexer can create "imputes" edges pointing from .java files.
Tested:
bazel test //kythe/javatests/...

Inherit language from file vname when creating new anchor.

---

WORKSPACE

Tested with `bazel clean --expunge && bazel test //... //kythe/release:release_test`

Add support for Bazel 0.15

---

kythe/go/util/kytheuri/bench_test.go
kythe/go/util/kytheuri/uri.go

Use a strings.Builder to reduce allocation overheads. This gives us a 32%
reduction in runtime for Kythe URI encoding on the parsing benchmark sample.
BenchmarkString-8        1000000              2331 ns/op
BenchmarkOldString-8      500000              3446 ns/op

kytheuri: Speed up encoding a URI to a string.

---

kythe/go/util/kytheuri/uri.go

This drops the runtime by another 4.5%.
BenchmarkOldString-8     1000000              2061 ns/op
BenchmarkString-8        1000000              1968 ns/op
The crux of the change is to avoid allocating to concatenate the static strings
with their prefixes. The swap for the function call wins the round.

kytheuri: Git rid of some additional allocations.

---

kythe/go/util/riegeli/transpose.go
kythe/go/util/riegeli/transpose_test.go

This is mostly to remove the panics from the decoder.  It'll be easier to test these features once the encoder is working.

Riegeli: support decoding proto groups and non-proto records

---

WORKSPACE
tools/build_rules/verifier_test/verifier_test.bzl

java_common.create_provider will be deprecated soon.
[1] https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html#JavaInfo

Migrate from java_common.create_provider to new constructor JavaInfo() [1]

---

kythe/typescript/package.json
kythe/typescript/utf8.ts
kythe/typescript/utf8_test.ts
kythe/typescript/yarn.lock

The 'utf8' module maps nodejs UTF-16 offsets <-> Kythe UTF-8 offsets.
Because of surrogate pairs, a single code point in UTF-8 may be multiple
UTF-16 code units.
The fix also includes a unit test for the module that includes some
surrogate pairs.  To run this unit test we bring in a dependency on
Jasmine and adjust the test-running machinery to run both the unit
test and the end-to-end test.
This code was mostly written by Bowen Ni <bowen1897@gmail.com>; I just
added the Jasmine glue for running as part of open source Kythe.

properly handle utf16 surrogate pairs

---

kythe/java/com/google/devtools/kythe/platform/tools/pom_compiler_plugin_fragment.xml

Mostly just a reminder to myself so I don't have to keep hunting the same doc every time I forget.

Add comment pointing to maven docs on compiler config bits.

---

kythe/typescript/indexer.ts

console.log writes to stdout which can cause problems with the indexing pipeline. Put the log to stderr back in for now.
This undoes https://github.com/google/kythe/commit/8f53ded74543efad087aca592b17ff049f74f5ae

Switch ts log back to warn

---

kythe/cxx/tools/fyi/testdata/compile_commands.bzl

Migrate CToolchain-dependent ctx.fragments.cpp field calls to receive the information from toolchains. This is an intermediate step in migrating to the new Skylark API for the C++ toolchain. The extra _cc_toolchain attribute will be removed later in this migration.

Use find_cpp_toolchain in compile_commands.bzl

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java

The process for gathering annotations was:
1. Add ProcessAnnotation
2. Check for anything at --processors
3. If there's nothing then check for processors exposed by META-INF
However (3) will never happen because in (1) we always add a processor. Therefore if we move (1) to happen later we have a chance of getting to annotations.
This is necessary because some processors generate source code and Kythe wasn't running those processors.

Add ProcessAnnotation later.

---

kythe/cxx/common/BUILD
kythe/cxx/common/kzip_reader.cc
kythe/cxx/common/kzip_reader.h
kythe/cxx/common/kzip_reader_test.cc
kythe/cxx/common/libzip/error.cc
kythe/cxx/common/libzip/error.h

[Trying this again with a cleaner commit history]
This PR pulls out the zip_error_t handling a bit to prepare for sharing code with KzipWriter and exposes a FromSource factory which allows creating a KzipReader from a zip_source_t* to facilitate extension beyond local files.

Refactor KzipReader a bit to prepare for KzipWriter

---

tools/bazel.rc

This ensures environment variables are static across machines and allows for cross-user caching.
In a Future Bazel Release, this will [become the default](https://github.com/bazelbuild/bazel/commit/9a444d4340563386b2141ab67a5bfdb14a62d311) so this keeps us ahead of the curve.

Add --experimental_strict_action_env to bazel.rc

---

kythe/go/storage/tools/triples/BUILD
kythe/go/storage/tools/triples/triples.go

Fixes #2855. Per https://www.w3.org/TR/2014/REC-n-triples-20140225, the syntax
of N-Triples is expressed over UTF-8 encoded Unicode code points.
We are escaping code sequences correctly, but not binary values.  The
/kythe/code fact carries a wire-format protobuf message, which is not UTF-8 and
must therefore be escaped. This commit checks specifically for that fact when
encoding triples, and Base64 encodes the value. This matches the JSON encoding
for proto3 messages.

RDF: Encode /kythe/code facts in Base64.

---

kythe/cxx/common/status_or.h

This should partially address 2873 and help us to get our
buildbots green again. We shouldn't consider the issue closed
until we fix the issue permanently (likely by requiring
a newer clang).

Temporary fix for misbehaving old Clangs

---

kythe/go/platform/tools/kindex_file_generator/BUILD

We're only concerned with whether the result is empty.
Using `-b` instead of `-k` appears to fix #2875 for
some environments.

Measure bytes, not blocks, in a shell test.

---

kythe/cxx/common/BUILD
kythe/cxx/common/kzip_reader_test.cc
kythe/cxx/common/kzip_writer_test.cc
kythe/cxx/common/testutil.cc
kythe/cxx/common/testutil.h

This should further facilitate more reliable imports.

Factor out common test-source-root routine

---

kythe/cxx/common/status_or.h

When not using ref-qualifiers on the member functions, returning a value by-move has potentially confusing semantics so switch to using a copy.

Don't use std::move for the clang-3.5 ref-qualifier workaround

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java

Bazel's --java_header_compilation flag always tags enums as final which will cause the analyzer to assign different VNames to the definition of the Symbol and references to the Symbol outside of the defining compilation.  To compensate, we just ignore that modifier while constructing VNames for enums.
See: https://github.com/google/turbine/blob/0536e276/java/com/google/turbine/binder/CompUnitPreprocessor.java#L168

Java indexer: ignore final modifiers on enums

---

kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/basic/macros_lambda_call.cc

Adds a disabled test case for mis-anchored ref/call edges nested in macros nested in lambdas. Regular `ref` is accurate, but `ref/call` points to the start of the macro invocation.

Add minimal reproduction for #2899

---

kythe/go/extractors/config/runextractor/BUILD
kythe/go/extractors/config/runextractor/README.md
kythe/go/extractors/config/runextractor/backup/backup.go
kythe/go/extractors/config/runextractor/cmakecmd/BUILD
kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
kythe/go/extractors/config/runextractor/mavencmd/mavencmd.go
kythe/go/extractors/config/runextractor/runextractor.go

Also populate an empty cmake extractor shim and remove some of the
java-specific verbiage in prep for #2861.

Add list of required env vars.

---

tools/build_rules/verifier_test/cc_indexer_test.bzl
tools/cpp/CROSSTOOL.tpl

This PR makes Kythe forward compatible with Bazel 0.16 which introduced
a new Skylark API to the C++ toolchain
(https://docs.google.com/document/u/1/d/1g91BWJITcYw_X-VxsDC0VgUn5E9g0kRBGoBSpoO41gA/edit).
Backwards compatibility is maintained.
While at it, I:
* removed unused crosstool fields
* since I cannot write Skylark code without buildifier formatting it if my life
dependent on it, I also reformatted cc_indexer_test.bzl file.
I'll gladly split this work into multiple PRs if that's preferred.

Use the new Bazel C++ toolchain API

---

kythe/go/extractors/bazel/extutil/BUILD
kythe/go/extractors/bazel/extutil/extutil.go

In support of #2864, add a library to make it easier for extractors that
currently emit .kindex files to switch between that and .kzip format.  This
will allow an extractor to emit either format until we are finished with the
.kindex migration, at which point this can be collapsed and removed.

Add package extutil, to bridge .kzip/.kindex output.

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
kythe/go/extractors/cmd/bazel/extract_kindex/BUILD
kythe/go/extractors/cmd/bazel/extract_kindex/extract_kindex.go

Consolidate places where library code was duplicated in the extractor binaries.
There are no functional changes here. This cleanup is preparatory to a solution
for #2912, but for the moment that bug is still active.

Bazel extractors: Update dependencies, support code.

---

kythe/go/extractors/bazel/extractor.go
kythe/go/extractors/cmd/bazel/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
kythe/go/extractors/cmd/bazel/govnames.json
kythe/go/extractors/cmd/bazel/govnames_test.json
kythe/go/util/vnameutil/test/test_vname_rules.go

This program was not updated since we switched away from the legacy Go rules,
and was still expecting the build to generate a symlink forest and other such
nonsense that no longer applies.
Replace that with a much simpler implementation. The action's command line now
includes the file locations directly, so we do not need to guess and remap path
prefixes. Most of the old code was able to be simply deleted.
Fixes #2912.

bazel_go_extractor: Update for current bazel_go rules. 

---

kythe/web/site/getting-started.md

This is intended to address #2874.

Increase minimum required version of clang to 3.6.

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

The extractor defaults all compilations to the "go" language, but inference
based on filenames omits a language label (correctly, per the schema). In the
cases where we use that inference, ensure the language remains set.

Bazel Go extractor: Ensure compilations are tagged for "go".

---

kythe/cxx/verifier/BUILD
tools/build_rules/lexyacc.bzl

Rather than requiring the srcs and outputs to have a certain order, make
explicit the (one) grammar-file input, the header and source outputs, and
additional outputs generated by the compiler-compiler. Also, while I'm in here,
add some documentation.

Re-work the genyacc macro.

---

kythe/docs/kythe-kzip.txt

The spec says that the digest should only apply to the CompilationUnit itself,
not its wrapper message, but this was a little subtle and could easily be
overlooked. Make it more explicit.

kzip doc: Clarify the computation of unit digests.

---

kythe/cxx/verifier/BUILD
tools/build_rules/lexyacc.bzl

Rather than requiring the srcs have a certain order, make explicit the (one)
grammar-file input, and separate includes. Also, while I'm in here, add some
documentation.

Re-work the genlex macro.

---

kythe/go/languageserver/languageserver.go
kythe/go/languageserver/languageserver_test.go

If an indexer emits a zero-width span by providing a start location without an
end, the language server will currently discard it because it lacks an end
marker. While this is not an ideal way for the indexer to represent
definitions, we can get a somewhat less surprising result by reusing the start
location as the end when the latter wasn't provided.

KLS: Deal more gracefully with zero-width definition spans.

---

kythe/go/languageserver/languageserver.go

This is a follow-up to #2944. In addition to not throwing away empty spans from
the service, also ensure that when those spans are not discarded when they
don't get moved by remapping.

KLS: Don't discard an unresolved empty location during remapping.

---

third_party/javac/BUILD

This is a partial rollback of #2892 to ensure the Java indexer/extractor can on JRE8.

Link against JDK8 targeted langtools

---

WORKSPACE

The built-in http and git rules are being deprecated in favour of the
starlark versions so load them from their respective starlark modules.
Tested using `--incompatible_remove_native_git_repository` and
`--incompatible_remove_native_http_archive` flags.
See https://groups.google.com/forum/#!topic/bazel-discuss/dO2MHQLwJF0

Remove deprecated use of built-in http/git rules

---

kythe/release/BUILD
kythe/release/package_release.sh
kythe/release/release_test.sh
kythe/release/setup_release.sh

md5 is not in the normal mac PATH, so it is easier if we just use a signature
generated from our own shasum tool.
This is necessary now since we are setting
experimental_strict_action_env in our bazel.rc.

Use our shasum tool instead of md5 for releases

---

kythe/go/platform/tools/kindex_file_generator/BUILD

du -b doesn't exist on macOS. We can use wc -c instead to get the character count.

Use wc -c instead of du -b

---

kythe/extractors/cmake/extract_compilation_database.sh

The easiest way to get this test to work on macOS is to not use parallel since parallel isn't in the PATH that bazel uses.

Don't use parallel

---

kythe/docs/rfc/2966.md

Specify the handling of analysis requests that were not yet reported as done
when the analyzer process terminates. Define the term "pending". Clarify the
obligations of the driver in cleaning up after a failed analyzer.

Analysis protocol: Clarify request lifetime.

---

kythe/go/indexer/emit.go
kythe/go/indexer/testdata/basic/anonymous.go

Similar to #2828, this commit ensures that the fields of struct type
declarations also get their subfields decorated, when those subfields are of
anonymous struct type.
Fixes #2984.

Go indexer: Fix more anonymous struct field declarations.

---

kythe/docs/schema/asciidoc_with_verifier.bzl
kythe/docs/schema/example-base.sh
kythe/docs/schema/example-cxx.sh
kythe/docs/schema/example-dot.sh
kythe/docs/schema/example-go.sh
kythe/docs/schema/example-java.sh
kythe/docs/schema/example-objc.sh
tools/build_rules/external_tools/external_tools_configure.bzl

shasum is a perl script, which means it is tricky to put in the bazel
sandbox. On Linux, you execute shasum, but on macOS apparently the perl
wrapper finds the right version of the shasum and executes that. Since
we already have our own shasum binary, we should just use that and make
this problem go away.
Part of #2967

Use our own custom shasum tool

---

.bazelrc
tools/bazel.rc

This supports a decent transition for #2897.  Once we drop support for 0.16, we'll be able to remove the warning and move our settings directly to the new `%workspace%/.bazelrc` location.

Support new location for project-specific Bazel options

---

kythe/go/indexer/cmd/go_indexer/BUILD
kythe/go/indexer/cmd/go_indexer/go_indexer.go

Now that kzip support is available, we no longer need indexpack support in this
tool. For now, .kindex files can still be handled.
Addresses part of #2866.

go_indexer: Remove indexpack support.

---

kythe/go/extractors/config/runextractor/gradlecmd/gradle_build_modifier.go
kythe/go/extractors/config/runextractor/gradlecmd/gradle_build_modifier_test.go
kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go
kythe/go/extractors/config/runextractor/gradlecmd/testdata/modified-gradle.build
kythe/go/extractors/config/runextractor/gradlecmd/testdata/other-gradle.build

Previously hardcoded this to /opt/kythe/extractors/javac-wrapper.sh,
which works fine in the current docker image, but probably should be
configurable.

Update gradlecmd to support different javacWrapper

---

kythe/docs/schema/marked-source.txt

The singleton check did its job here -- we had a typo in the evar.

Fix another singleton variable in the marked-source example.

---

kythe/docs/schema/example-java.sh
kythe/docs/schema/example-objc.sh
kythe/docs/schema/kythe-filter.conf

The examples embedded in the schema and other related docs have a lot of
variables that are used only once (i.e., singletons), which trip on the
verifier now that the default is to flag singletons.
For example purposes it's fine to have singletons -- the check is there to
avert typographical errors in unit tests. Errors could also happen in the
examples, but the unit tests should be catching any real bugs that might be
disguised in that case.

Default extracted verifier tests to not check for singletons.

---

kythe/docs/asciidoc.bzl
kythe/web/site/sync_docs.sh
tools/build_rules/external_tools/external_tools_configure.bzl

Because asciidoc may generate an unknown number of output files (as the result of running filters), 
fix the rule to capture these in a ZIP file instead.  Also add some documentation so that future readers 
can see what's going on. This addresses an issue where recent versions of Bazel, which have become
more aggressive about cleaning up the sandbox after an action executes, would lose the support files
from the asciidoc filters.
Also update the website documentation builder to account for the above.

Make the asciidoc rule emit outputs to a zip file.

---

kythe/web/site/sync_docs.sh

This rule is marked manual to work around missing files in buildbot.  So to
make it go out on the website, we need to build it explicitly rather than via
the glob.

Site sync: Explicitly build the schema-overview doc.

---

kythe/docs/BUILD
kythe/release/appengine/buildbot/Dockerfile

This simplifies installing some of our dependencies.  It also upgrades our asciidoc dependencies to ensure //kythe/docs:schema-overview builds properly.

Upgrade Buildbot container to debian:stretch

---

kythe/go/indexer/indexer.go
kythe/go/indexer/testdata/code/methdecl.go

This is to address a user complaint that hovercards do not include the result
types in the rendering.

Go: Mark result parameters as part of the TYPE in MarkedSource.

---

kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go

Note this doesn't affect most normal operation since we would tend to
run this inside of a docker container that sets up a clean environment
every time.  However, for both local testing and possibly future usage,
we might not want to assume that - so do a 'gradle clean build' instead
of 'gradle build'.  This means if we're re-using the environment for
whatever reason (maybe to make it cheaper and less overhead? who knows),
we won't sometimes mysteriously get no extraction results.
(sub-1-line pull request with a lengthy explanation, but probably worth it
for posterity)

Always build gradle clean.

---

third_party/beam/BUILD
third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk.go
third_party/beam/sdks/go/pkg/beam/runners/disksort/gbk_test.go

Since https://github.com/apache/beam/pull/5882, the GBK concurrency causes races in the core Beam executor and cannot be supported.

Remove concurrency from Beam disksort runner

---

WORKSPACE
tools/remote_test.sh

This is a patch until https://github.com/google/flogger/pull/37 is closed.

Fork Flogger to build Java targets in RBE environment

---

kythe/cxx/indexer/cxx/marked_source.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/marked_source/ms_array.cc

We had been doing this for functions, but we should
also do it for variables and fields.
Addresses #3039.

Split type MarkedSource nodes containing decl names

---

kythe/go/extractors/bazel/extractors.bzl

As part of #2867, switch the default format emitted by the Go-based Bazel
extractors to be .kzip instead of .kindex. This means the name of the tool is
now no longer accurate, but we can clean that up in a separate pass.

Bazel extractors: Emit .kzip files by default.

---

kythe/docs/schema/BUILD
kythe/docs/schema/asciidoc_with_verifier.bzl
kythe/release/appengine/buildbot/master/master.cfg.template

The other asciidoc_with_verifier targets have their 'manual' tag removed so they are tested in all configurations.
The bazel-opt builder has been folded into the bazel-release builder.

Add //kythe/docs/schema to Buildbot release tests

---

kythe/go/extractors/bazel/extractor.go
kythe/go/extractors/bazel/extractor_test.go

The underlying extraction machinery already invokes the fixup, so it is not
necessary to repeat it when extracting to a file. It is harmess apart from
being wasteful of resources to do so as long as the fixup is idempotent -- but
since that is not required, so don't (unintentionally) rely on it.

Bazel extractor: Remove a redundant call to config.FixUnit.

---

kythe/go/extractors/config/runextractor/backup/backup.go

Specifically to avoid #3051 we need to make sure we get a "." for the
local directory instead of "", because `ioutil.TempFile` will helpfully
prepend /tmp if you pass "" to dir.

Use filepath.Dir & filepath.Base instead of filepath.Split.

---

kythe/go/extractors/bazel/extractor.go
kythe/go/extractors/bazel/extractor_test.go

When processing input files, filters may re-introduce files that were already
examined. Prior to this commit, this has two downsides: One, it's redundant
(which, though harmless, is wasteful), and two it can result in entries that do
not get correctly updated (which is incorrect).
Verify that we only add a new required_input for new file paths, and update the
tests to ensure this gets checked.

Bazel extractor: Avoid re-recording input files already added.

---

kythe/go/extractors/bazel/extractors.bzl
kythe/go/extractors/cmd/bazel/BUILD
kythe/go/extractors/cmd/bazel/extract_kzip/BUILD
kythe/go/extractors/cmd/bazel/extract_kzip/extract_kzip.go

This tool still knows how to write .kindex files if requested, but eventually
that feature will be removed.

Rename extract_kindex to extract_kzip.

---

kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java
kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BazelJvmExtractor.java

Load in the JVM extractor's detail messages so the kzip can write out files. If you don't do this, you'll get an error message like java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: kythe.io/proto/kythe.proto.JarEntryDetails

Bootstrap JVM extractor details messages

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/function/function_knr_defn.c
kythe/cxx/indexer/cxx/testdata/function/function_picky_types.c

We were overzealous before and triggered an assert() in clang in production.  This didn't manifest in tests because we build llvm with -DNDEBUG, bypassing the assert.
We are also triggering a segfault in production, but not with the included test.  It appears to be the same problem, but optimization and lack of NDEBUG makes it harder to tell why/where that failure is occurring.  It should be the same one (or at least related), but it's hard to tell for certain.

Only replace Decl TSI if the location-aware type is an undeduced type

---

third_party/llvm/src/BUILD
tools/build_rules/cc_resources.bzl

When built as part of an external repository, the generated files directory needs to be updated with the repository name.

Fix building @io_kythe//third_party/llvm/src:clang_builtin_headers

---

kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java

This interface implementation is required by javac for compilations specifying a `--release` version.

Implement StandardJavaFileManager for wrapper class

---

kythe/go/util/riegeli/reader.go
kythe/go/util/riegeli/riegeli_test.go

Seeking through the chunks in a block needs to include seeking past the data for each chunk.

Riegeli: fix seeking in files with metadata record

---

kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/JavaFileStoreBasedFileManager.java

This override is necessary in Java 9 and later to fully support the `--release` option.  Reflection is used to allow us to continue to support Java 8.

Implement StandardJavaFileManager#setLocationsFromPaths

---

WORKSPACE

Tested against https://releases.bazel.build/0.18.0/rc8/index.html

Support upcoming Bazel 0.18.0 release

---

kythe/java/com/google/devtools/kythe/extractors/java/bazel/README.md
kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
kythe/java/com/google/devtools/kythe/util/BUILD
kythe/release/BUILD
kythe/release/README.md
kythe/release/release_test.sh
kythe/web/site/examples.md
third_party/javac/BUILD

Part of #3075.
This removes our hard-coded usage of `-Xbootclasspath/p` and allows the `javac-wrapper.sh` to be version-agnostic.  When running on JRE 8, the `-Xbootclasspath/p` flag can be passed using the `KYTHE_JAVA_RUNTIME_OPTIONS` environment variable.

Migrate javac_extractor to use ambient langtools

---

kythe/java/com/google/devtools/kythe/platform/kzip/BUILD
kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java

It looks like we may see the same file multiple times during extraction. If we try to add the file to the zip again, the zip library will throw a generic zip exception. We can avoid this situation by just not appending a file if we know we have already added it to the zip.

Don't crash if we try to write the same file to a kzip more than once

---

WORKSPACE
external.bzl

This allows other Bazel projects to more easily depend on Kythe without
needing to copy our entire WORKSPACE file.
Only repositories needed to build targets exposed by #3105 have been
migrated.

Begin migrating external repository definitions to importable WORKSPACE function

---

kythe/cxx/extractor/BUILD
kythe/extractors/bazel/extract.sh
kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD

The kythe/extractors/bazel/extract.sh script was still using kindex and
that format is deprecated.
- Switch the script to use kzips
- Add kzip extra actions for Java and C++
- Remove option to convert to indexpack in extract.sh

Update kythe/extractors/bazel/extract.sh so it works with kzips

---

kythe/cxx/common/indexing/frontend.cc

Fix the following lint warning: std::move of the const expression has no effect; remove std::move()

Remove no-op std::move

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java

Symbol modifiers can be inconsistent between definition/referencing compilations.  The existing exception was found due to the way Turbine handles the 'final' modifier on enums, but it can also be case that other modifiers (like 'strictfp') are inconsistent.  This change makes the symbols hashing less precise but shouldn't affect any known use-case for the indexer.

Java indexer: do not include Symbol modifiers in hashes

---

kythe/web/site/Gemfile.lock
kythe/web/site/sync_docs.sh

If you don't have the asciidoctor gem installed, you can generate a website,
but it will be missing toc/title/etc. because the commands from the script that
use the asciidoctor gem to find those values will silently fail.
Also bump the jekyll and asciidoctor versions to their latest in the gemfile

Add check for asciidoctor gem

---

kythe/go/platform/indexpack/BUILD
kythe/java/com/google/devtools/kythe/platform/indexpack/BUILD

Match the current C++ deprecation warnings.

chore(platform): deprecate Go/Java indexpack libraries

---

kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile

I forgot one place when you suggested this rename last week.

Another rename of for javac9-tools.jar

---

kythe/cxx/indexer/cxx/IndexerFrontendAction.h

Set a default value for the drop fwd decl docs option so if a client doesn't initialize these
values in an Options, they still get predictable behavior.

fix: Set default value for dropping fwd decl docs

---

.bazelrc
WORKSPACE

Tested against https://releases.bazel.build/0.19.0/rc6/index.html.

build(bazel): support upcoming 0.19.0 release

---

kythe/go/extractors/config/preprocessor/README.md
kythe/go/extractors/gcp/README.md
kythe/go/extractors/gcp/mvnpoc/cloudbuild.yaml

Also add a bunch of docs on how to run it on a given repo.
This is progress for #3150, but still much is missing.  Notably, this only
works for a minority of maven repos, doesn't have any configuration for
subdirectory pom.xml files, doesn't support anything but java8, etc.
Also add instructions for the `preprocessors.go` binary that is now wrapped into a docker image as specified in #3158.

Add a cloudbuild.yaml for maven extraction on Cloud Build

---

tools/git/commit-msg.sh

Unclear if we'd want this somewhere else.

fix: Adding error message to git hook when commitlint not installed.

---

kythe/go/extractors/config/preprocessor/preprocessor.go
kythe/go/extractors/gcp/README.md
kythe/go/extractors/gcp/examples/gradle.yaml

docs: documentation for above
fix: fix bug in preprocessor where it linked to javac, not wrapper

feat: add a gradle extraction example for cloud build

---

kythe/java/com/google/devtools/kythe/extractors/java/artifacts/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/artifacts/Dockerfile

Since gcp/cloud build is the way forward, we no longer need this binary
to put together steps for extraction.  Instead, that now lives inside
of a yaml file.  (We'll need a separate library and potentially binary
to do similar creation of a yaml file though).

fix: remove runextractor from javac-extractor-artifacts

---

WORKSPACE
external.bzl
kythe/cxx/extractor/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
kythe/java/com/google/devtools/kythe/extractors/jvm/bazel/BUILD
tools/build_rules/verifier_test/cc_indexer_test.bzl
tools/build_rules/verifier_test/verifier_test.bzl

Allow for repositories depending on Kythe to use their own VNames configuration.

build: move vnames configuration to external target

---

kythe/cxx/common/kzip_reader.cc
kythe/cxx/common/kzip_reader.h
kythe/cxx/common/kzip_reader_test.cc

The reference counting semantics of libzip object are such that it is the caller's responsibility to free constructor objects on error.  Retain a reference to the source in `KzipReader::FromSource` when validation fails so callers can do this reliably.

retain a reference to zip source on validation error

---

kythe/go/storage/inmemory/inmemory.go
kythe/go/storage/inmemory/inmemory_test.go
kythe/go/storage/keyvalue/keyvalue.go
kythe/go/storage/leveldb/leveldb.go

This is necessary to provide an efficient paging implementation for the
columnar serving formats (#2930).

feat: add Seek method to keyvalue.Iterator interface

---

tools/git/pre-commit.sh

Without these changes, arc fails when I try to commit.
```{.sh}
$ arc --version
arcanist 83661809e532c3fe444a8bf7c7d6936e6377691b (26 Oct 2018)
libphutil cf96fd681e7d35ad21c7aaaa0bd1869124e377ef (1 Nov 2018)
```
Error message when trying to commit:
```
You're running a command which operates on a range of revisions (usually,
from some revision to HEAD) but have not specified the revision that should
determine the start of the range.
Previously, arc assumed you meant 'HEAD^' when you did not specify a start
revision, but this behavior does not make much sense in most workflows
outside of Facebook's historic git-svn workflow.
arc no longer assumes 'HEAD^'. You must specify a relative commit explicitly
when you invoke a command (e.g., `arc diff HEAD^`, not just `arc diff`) or
select a …
```

fix: specify revision to diff against when using arc

---

kythe/cxx/extractor/cxx_extractor.cc

When going through the examples, I mis-typed a file name parameter to the cxx_extractor and got a segfault. It did print a helpful error message about the missing file before crashing which was good :)
Stack trace:
~~~{.sh}
#0  google::protobuf::io::CodedOutputStream::HadError (this=0x0) at external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:816
#1  0x000000000041ea6d in kythe::KindexWriterSink::~KindexWriterSink (this=0x22a0400) at kythe/cxx/extractor/cxx_extractor.cc:951
#2  0x000000000041ecb9 in kythe::KindexWriterSink::~KindexWriterSink (this=0x22a0400) at kythe/cxx/extractor/cxx_extractor.cc:950
#3  0x000000000044a65f in std::default_delete<kythe::CompilationWriterSink>::operator() (this=0x7fffffffd390, __ptr=0x22a0400) at …

fix(cxx_extractor): segfault when given nonexistent file

---

kythe/docs/exploring-kythe-sample-web-ui.txt
kythe/docs/kythe-configurable-extraction.txt
kythe/docs/kythe-storage.txt
kythe/web/site/examples.md

There's also a link in the "Build System Integration" section of kythe/web/site/contributing.md that points to some cmake files that seem to have moved. I'm not sure where that code lives now.

fix(docs): fixed a few broken links

---

tools/git/setup_hooks.sh

This ensures that changes like #3231 don't break existing checkouts.

fix: allow git hooks to not exist

---

kythe/cxx/extractor/cxx_details.h
kythe/cxx/extractor/index_pack.h
kythe/cxx/extractor/language.h
kythe/cxx/extractor/path_utils.h
kythe/cxx/indexer/cxx/KytheClaimClient.h
kythe/cxx/indexer/cxx/frontend.h
kythe/cxx/indexer/cxx/proto_conversions.h

We need a stronger tag than `chore` for changes like this

chore: rename header guards (#945)

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts

These are flagged by the Google linter, which we don't enforce for
the Kythe project, but it seems harmless to occasionally fix these on a
case by case basis.
- Use 'const' whereever possible.
- Fix a missing semicolon by using the preferred function style.

typescript: fix some lint issues

---

kythe/typescript/indexer.ts
kythe/typescript/tsconfig.json

TypeScript rolled all of its strictness flags into a single `--strict`
flag.  Enable this and fix the errors it found.
- The central `Visitor` class had a weird API where it took some params
as ctor arguments and then it took the input file as a function
argument, despite the fact that you need a new instance per file.
Fix this by making everything into ctor arguments and moving some
code.
- Fix a nullability issue when iterating input files.  Handle a
potential null by just throwing with a nicer error message.

typescript: enable strict mode and fix errors

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
tools/build_rules/verifier_test/verifier_test.bzl

The old pattern did an implicit iteration over a depset which is potentially expensive. The new to_list() call is still expensive but it will be more visible.

refactor: replace iteration over depsets with explicit .to_list() call

---

kythe/cxx/indexer/cxx/KytheIndexerMain.cc
kythe/cxx/indexer/cxx/frontend.cc
kythe/cxx/indexer/cxx/frontend.h

This way there is only one compilation in memory at a time (#3233), which is more memory-efficient than building a list of all compilations and processing them all afterwards.
Previously the `IndexerContext` constructor did all the work and saved a list of jobs. Now the constructor just does some basic setup and the `EnumerateCompilations()` method handles reading files and passing compilations to the indexer callback.

refactor(cxx_indexer): enumerate compilations as they're read

---

kythe/cxx/indexer/cxx/frontend.cc

When using the indexer like: `indexer -i file.cc`, sets the `source_file` field to `["file.cc"]`.
The C++ indexer seems to work fine without this field set, but other indexers do require it. Setting this field could allow for other indexers implemented in C++ to reuse `IndexerContext`. Why does C++ not require this field? Does it just read thorough all of the files in the list passed alongside the `CompilationUnit`?

fix(cxx frontend): set CompilationUnit.source_file for unpacked input

---

kythe/web/site/examples.md

A few updates to examples.md. The java and c++ extraction examples both had some complications with dependencies, so I changed them to use files with less deps.
Part of #108

fix(docs): a few documentation updates

---

kythe/cxx/common/BUILD
kythe/proto/BUILD
visibility.bzl

* The aliases for //visibility:public in visibility.bzl allow us to restrict visibility to certain package groups within google.
* The newly-public targets are needed for the proto indexer
This is kind of a hack, so I'm definitely open to better ideas. This problem is somewhat similar to what's discussed here: https://github.com/bazelbuild/bazel/issues/3744.

feat: add visibility aliases and mark some protos/utils as public

---

kythe/cxx/common/BUILD
kythe/cxx/common/kythe_uri.cc
kythe/cxx/common/path_utils.cc
kythe/cxx/common/path_utils.h
kythe/cxx/common/path_utils_test.cc
kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/path_utils.cc
kythe/cxx/extractor/path_utils.h
kythe/cxx/extractor/path_utils_test.cc
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/frontend.cc

I'll need these utility functions for the proto indexer.

Create a new path_utils library in kythe/cxx/common that doesn't depend on llvm

---

AUTHORS
CONTRIBUTORS
kythe/go/util/riegeli/riegeli.go
kythe/go/util/riegeli/riegeli_test.go

Otherwise 
```go
riegeli.ParseOptions("chunk_size:1024")
```
results in error `unknown option: "chunk_size:1024"`

Riegeli: support parsing chunk_size option

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
kythe/release/release_test.sh

Follow-up to #3297, getting rid of kindex and indexpack support.
Relevantly, this will mean that setting KYTHE_OUTPUT_DIRECTORY now
writes potentially multiple kzips, instead of kindex.  We can bundle
those together later with zipmerge if we want.

refactor: write kzip always for JavaStandalone extractor

---

kythe/cxx/extractor/BUILD
kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/cxx_extractor.h
kythe/cxx/extractor/testdata/test_alternate_platform.sh
kythe/cxx/extractor/testdata/test_extract_transcript.sh
kythe/cxx/extractor/testdata/test_has_include.sh
kythe/cxx/extractor/testdata/test_indirect_has_include.sh
kythe/cxx/extractor/testdata/test_main_source_file_env_dep.sh
kythe/cxx/extractor/testdata/test_main_source_file_no_env_dep.sh
kythe/cxx/extractor/testdata/test_metadata.sh
kythe/cxx/extractor/testdata/test_modules.sh
kythe/cxx/extractor/testdata/test_root_directory.sh
kythe/go/extractors/config/runextractor/compdb/BUILD
kythe/go/extractors/config/runextractor/compdb/compdb_test.go

KZip has replaced the index pack and kindex formats.
Previously the extractor only wrote kzip files if KYTHE_OUTPUT_FILE was
specified in the environment and ended with '.kzip'. This remains
unchanged, but now the extractor also writes kzip files if
KYTHE_OUTPUT_DIRECTORY is specified - this used to result in .kindex
files being written instead. When given a directory, the extractor names
the .kzip files based on a hash of the compilation unit just as it did
with kindex.
Extractor tests have been updated to use kzip instead of kindex.
Part of #2867

refactor: remove deprecated kindex from cxx extractor

---

kythe/cxx/indexer/cxx/marked_source.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/objc/categories/marked_category.m

Instead of just printing the category name in the marked source for category
methods, print the interface and category, like you would expect. So instead of
Cat::foo we now output Base(Cat)::foo.

feat(objc_indexer): marked source for category methods

---

kythe/web/site/getting-started.md
kythe/web/site/install-macos.md

The steps to set up developer tools and install external dependencies for Kythe
to build on macOS are sufficiently different from Linux-based systems that they
deserve a separate document. Add that document, and link to it from the master
setup instructions.
Fixes #3313.

docs(macos): add macOS installation instructions

---

kythe/web/site/getting-started-macos.md
kythe/web/site/getting-started.md

The link was wrong for the new macos docs. I also renamed the file so the link has the same name as the file.

fix: The link to the new macos docs was broken

---

kythe/web/site/getting-started.md
tools/modules/update.sh

One way of fixing #3307.
This will make the initial download of llvm and clang faster, by not
requiring a clone of the entire ~3GB repo.  It also save on the ongoing
disk used.  However, it does make updates marginally slower because you
have to re-download a new archive.  Given that updates are vastly
dominated by the cost of building llvm&clang, this is probably ok.
Also this has the side effect of making images for Google Cloud Build +
bazel significantly smaller, which will be nice for #3210.

fix: change tools/modules/update.sh to use an archive instead of clone

---

kythe/examples/bazel/BUILD
kythe/go/extractors/gcp/bazel/BUILD
kythe/go/extractors/gcp/bazel/Dockerfile

Creates `gcr.io/kythe-public/kythe-bazel-extractor-artifacts`.
For now basing this off of launcher.gcr.io/google/ubuntu16_04 and exposing relevant pieces via /opt/kythe/ with the expectation that we can sideload necessary pieces in subsequent build steps:
* /opt/kythe/extractors contains `setup-bazel-repo.sh`, a script for modifying WORKSPACE so that a bazel repo can extract using kythe extractors
* /opt/kythe/repo/kythe contains an installed kythe repo (./tools/modules/update.sh already run, so `bazel build some:target`should work).
Another step towards #3210.

feat: add docker image with a kythe install for use in google cloud build

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/marked_source.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/objc/marked_property.m

Add basic support for generating marked source for properties in
Objective-C. This should offer similar support to what we do for class
members in C++. It doesn't do anything special for the automatically
generated getter and setter methods. It also doesn't do anything special
with the @property string (though it is present in the marked source).

feat(objc_indexer): support marked source for @property

---

kythe/web/site/getting-started-macos.md

A follow-up to #3314, needed now that #3308 has landed.  macOS does not include
wget in the base install.

fix: include wget in the list of packages to install on macOS

---

kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/java/SourceText.java
kythe/java/com/google/devtools/kythe/util/Span.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java

Emit implicit `defines` anchors for default constructors and emit
implicit `ref/call` edges for implicit `super` constructor calls (even
if the callsites are in an implicit constructor).

feat(java_indexer): emit implicit anchors for default constructors

---

kythe/docs/schema/example-go.sh
kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/extractors/golang/BUILD
kythe/go/extractors/golang/golang.go
kythe/go/extractors/golang/packages.go
kythe/go/indexer/cmd/go_example/BUILD
kythe/go/indexer/cmd/go_example/go_example.go
kythe/go/indexer/testdata/go_indexer_test.bzl

As a consequence, the `gotool` extractor now supports extracting Go 1.11 modules (#2881).

feat(gotool_extractor): use Go tool to extract package data

---

kythe/go/extractors/gcp/examples/guava-mvn.yaml

Tested using `install` instead (see #3126), didn't work as well.

fix: extract guava tests as well

---

kythe/go/indexer/testdata/go_indexer_test.bzl

It looks like this has been replaced by the `go_verifier_test()` macro below it.

chore: remove unused bazel rule _go_verifier_test()

---

kythe/go/platform/tools/kzip_validator/kzip_validator.go

Other souce hosting services will use different url formats for their
repo archives, for example android.googlesource.com.

fix: add docs on extracting non-github repo

---

kythe/go/extractors/validation/validation.go
kythe/go/platform/tools/kzip_validator/kzip_validator.go

I was originally gonna do some hackery with a default output, but ended
up not doing so, and this means the string pointer I was using isn't
really useful anymore, so removing it because I'll probably shoot myself
in the foot with it later if I don't kill it now.

fix: don't use a string pointer when we don't have to

---

kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc
third_party/llvm/src/cxx_extractor_preprocessor_utils.cc
tools/modules/versions.sh

This also switches getSourceText to using the upstream static member function in Lexer, originally to workaround the bug in r350891 but now just to accomplish the same goal in cleaner way.
As `getThisType()` no longer accepts an ASTContext parameter, remove the extra Kythe plumbing passing it around.

update llvm to r350964 

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h

Since clang r351047 the implicit classes for lambdas are visited for
lambdas in all scopes, not just the global scope.

Remove workaround for clang bug

---

kythe/go/extractors/gcp/README.md
kythe/go/extractors/gcp/config/kziptool/BUILD
kythe/go/extractors/gcp/config/kziptool/Dockerfile
kythe/go/extractors/gcp/examples/guava-mvn.yaml

Cody added kzip cli tool in #3354, which we should use instead of
zipmerge.
This change also exposes kzip cli tool as a docker image hosted at
gcr.io/kythe-public/kzip-tools, so you can now run:
```
docker run --rm gcr.io/kythe-public/kzip-tools merge \
--output <some-file> <bunch-of-kzip-files>
```
Or alternatively, on GCP:
```
- name: 'gcr.io/kythe-public/kzip-tools'
entrypoint: 'bash'
args:
- '-c'
- '/opt/kythe/tools/kzip merge --output out inputs*.kzip'
```

fix: use kzip tool instead of zipmerge for gcp extraction

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h

This fact is already supported, but wasn't present in the common enumerator.

fix(cxx_common): add enumerator for kDocUri fact

---

external.bzl
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/testdata.proto
tools/build_rules/verifier_test/java_verifier_test.bzl

java_proto_verifier_test extracts/analyzes/verifies protocol buffer
sources, their generated Java sources, and Java sources depending on the
generated sources as test of the cross-language references between Java
and proto.
A single test is implemented as a proof-of-concept for the Starlark
rule.  More tests will follow.

build: add java_proto_verifier_test Starlark rule

---

kythe/web/site/getting-started.md
kythe/web/ui/BUILD

Bazel doesn't build everything by default with `//...`, and we have a
good number of packages that use `tags = ["manual"]` to avoid this,
including release, docker images, etc.

fix: add documentation on the limitations of `build //...`

---

tools/modules/update.sh

I always forget exactly where I dropped the sentinel files.

fix: add short hint in tools/modules/update on how force rebuild

---

kythe/cxx/common/BUILD

Needed for textproto extractor.

build: add visibility for cxx/common:index_writer

---

kythe/go/extractors/cmd/bazel/govnames.json
kythe/go/extractors/cmd/bazel/govnames_test.json

This lets sane extraction of kythe/go. There are some unpleasant file vnames left due to `cgo`, these can be rewritten as well later if bothers.
TESTED=indexed //kythe/go/...
Fixes #3096.

Fix govnames.json to reflect actual patterns.

---

kythe/go/extractors/bazel/extractor.go
kythe/go/extractors/bazel/settings.go
kythe/typescript/BUILD

This allows a caller to push all corpus configuration logic to the VName rules file.

feat(bazel_extractor): infer corpus from source files

---

kythe/go/extractors/bazel/extractor.go

Source files can be specified with a regex over the inputs OR as a regex
over the arguments. The arguments regex is applied during the "fixup"
stage at the end. This change moves a log statement to print out the
number of source files after the count is finalized.
Before this change, textproto extraction was consistently logging that there were zero source files, even though the kzip correctly had one.

fix(bazel extractor): print file counts after handling source args

---

kythe/examples/bazel/BUILD

Re-add the BUILD file to fix query failures when arcanist tries to find affected tests.

fix(examples): fix a missing dependency from a docker rule

---

kythe/web/site/getting-started-macos.md

Although Bazel claims it only requires a command-line installation of Xcode,
recent updates appear to need a "real" (app) installation.

docs: update the macOS instructions for #3439

---

.commitlintrc.js

Add 'deprecation' as a commit type.
Warn when a commit does not specify a scope or it is not a standard scope.

release(dev): add stricter checking of commit messages

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h

This field isn't used by the C++ indexer, but may be used by other indexers written in C++

feat(cxx_common): Add ref imports edge field

---

kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java

Shows why #3462 is a terrible, terrible idea.
Also add test for class annotation docs as well.

test: add tests for line comments on methods

---

external.bzl
go.mod
go.sum

After https://github.com/google/subcommands/pull/20 this package now has a
go.mod file and versioned tags.

build: update github.com/google/subcommands to tagged version 1.0.1

---

external.bzl
go.mod
go.sum

This is not the most recent version, but is newer than we have been using so
far, and is the latest that does not bring in new ancillary dependencies.

build: update go.opencensus.io to tagged version v0.15.0

---

external.bzl
go.mod
go.sum

Interestingly we had a pointer to something claiming to be v1.0.1, but the
repository does not advertise such a tag. It's possible there was at one point
that was later removed, but we should probably not depend on that.

build: update github.com/nwaples/rardecode to tagged version v1.0.0

---

external.bzl
go.mod
go.sum
third_party/go/BUILD

There are no imports of this package anywhere. If we do want to take a
dependency on it in the future, we should do so at one of the release tags.
For now, doing so at any recent tag will pull in extra dependencies, so I
propose to drop it till we need it concretely.

build: remove unused dependency on github.com/google/go-github

---

external.bzl

This does not actually change which version we are using, since the digest was
already set to this tag's digest in the original import, and thus the go.mod
and go.sum files do not need to change.

build: update github.com/mholt/archiver to tagged release v3.1.1

---

kythe/proto/analysis.proto

Updates #3483, where it arose that the existing description is not sufficiently
detailed to make the intention clear. Specifically, point out that the v_name
of a compilation record is not an identifier. To the extent that compilation
records have identifiers, it is the unit digest of the complete record.

docs: clarify the comment on the CompilationUnit.v_name field

---

kythe/cxx/common/path_utils.cc
kythe/cxx/common/path_utils.h
kythe/cxx/common/path_utils_test.cc

This is needed if `KYTHE_ROOT_DIRECTORY=/` is passed to the cxx
extractor.
Also check that relativization only happens if the relativization base
is a proper path prefix of the target, and not just a stringy prefix.

Make kythe/cxx/common/path_utils.cc relativize against root dir.

---

external.bzl
go.mod
go.sum
kythe/go/extractors/config/runextractor/cmakecmd/BUILD
kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
kythe/go/extractors/config/runextractor/compdbcmd/BUILD
kythe/go/platform/indexpack/BUILD
kythe/go/platform/indexpack/indexpack.go
third_party/go/uuid.BUILD

Recent updates of the github.com/pborman/uuid library have become thin wrappers
around the Google version, and in fact they're both maintained at least in part
by the same person. Instead of updating the wrapper, which would require us to
also depend on the underlying library, just use the Google one directly.
This required a small change to the call site for uuid.New(), since the type
has changed slightly. However, otherwise this is a fairly straightforward update.

build: use github.com/google/uuid for Go UUID generation

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD

This will do something undesireable for comments like this:
```
@Inject private String someVar; // comment no longer on someVar
```
This also doesn't address comments on class annotation lines:
```
@RunWith(...) // comment is still on SomeClass
public class SomeClass {
...
```

fix: address part of #3459 by claiming comments for annotation lines

---

WORKSPACE
tools/build_rules/verifier_test/java_verifier_test.bzl

Tested against https://releases.bazel.build/0.23.0/rc1/.

build(bazel): support upcoming Bazel 0.23.0 release

---

external.bzl
kythe/cxx/common/file_vname_generator.cc
kythe/cxx/indexer/cxx/GraphObserver.h

This requires updating RE2 to include the `explicit operator std::string` conversion so that we can use it.  I'm sure there are additional such cleanups to be made, but this is a good start.

Use std::string and string_view-like APIs more uniformly

---

kythe/go/serving/pipeline/beam.go
kythe/go/serving/pipeline/pipeline.go

There were two places that bailed out on error. I observed these happening when using the `beam` pipeline or the older `graphstore`-based one. The added flag can turn bailing out to just logging the warning but continuing processing.

Make pipeline more tolerant to some errors (affects write_tables tool).

---

kythe/typescript/test.ts

Replace property access on objects with an index signature type, with an index access.
Previously, you could write:
```
interface IdxSig {
[key: string]: string;
}
function propAccess(x: IdxSig) {
x.prop;
}
```

fix: propagating a downstream fix on typescript

---

kythe/data/BUILD
kythe/data/vnames.bzl
kythe/extractors/BUILD
kythe/extractors/bazel/BUILD
kythe/extractors/bazel/Dockerfile
kythe/extractors/bazel/README.md
kythe/extractors/bazel/extract.sh
kythe/extractors/bazel/extractors.BUILD
kythe/extractors/bazel/extractors.WORKSPACE
kythe/extractors/bazel/extractors.bazelrc
tools/build_rules/docker.bzl

Use pre-built extractor binaries to create a local Bazel repository to
use as a source of extra actions.  Add all common Kythe configuration to
the builder's .bazelrc file and use a simple script to collect the .kzip
artifacts after a Bazel execution.

feat(extraction): add Bazel extraction Docker image

---

kythe/cxx/verifier/assertions.yy
kythe/web/site/getting-started.md

Also drop official support for ancient Bisons.

fix(cxx_common): anticipate changes in Bison 3.3 syntax

---

kythe/data/vnames.bzl

The build rules for the VName test data fail on macOS because we used the
GNU-supported --delete flag instead of POSIX-recommended -d. All the Linuces
support -d just fine with the same semantics, so this has no discernable effect
on the results.

fix(dev): use POSIX safe flags for tr

---

.bazelrc
kythe/cxx/verifier/assertions.yy
kythe/data/vnames.bzl
kythe/web/site/getting-started-macos.md
tools/build_rules/lexyacc.bzl

Updates #3514. In #3513 we stipulated that Bison 3 must be used. On macOS,
which ships with Bison 2, this requires installing a new version.
However, the obvious way to do so, via Homebrew, brings in Bison 3.3.2 for
which the verifier's grammar file (assertions.yy) contains some no-longer-valid
definitions.  Moreover, Homebrew installs bison as "keg-only" meaning it is not
linked into the user's PATH. This presents a tricky setup problem, since users
configure their path in very different ways.
To address these issues, this change does several small things:
1. Add bison as a macOS dependency.
2. Allow a BISON environment variable to be set, that will be plumbed through
by Bazel to the environmento of actions.
3. Update the build rules to address the environment variable where set, with a …

fix(dev): allow specification of a correct Bison version

---

kythe/docs/asciidoc.bzl

GNU find will default to "." if run without any starting directories.  But in
POSIX the path is not optional, and macOS find fails if there is a flag before
any paths have been seen. The GNU behaviour is arguably better, but this makes
the docs build cleaner on macOS.

fix(dev): provide a starting point for the find command

---

kythe/web/site/getting-started-macos.md

In order for the native Go build to work on macOS, we need brotli and leveldb
to satisfy C++ header dependencies. Homebrew has cromulent packages for these,
so it suffices to include them in the install list.

fix(dev): include brotli and leveldb in the macOS package list

---

tools/build_rules/verifier_test/java_verifier_test.bzl

java_extract_kzip() calls extract(), which handles passing src paths
to the underlying extractor:
https://github.com/kythe/kythe/blob/448d46e8bb30c16345d516f09b6904e92b7a05cf/tools/build_rules/verifier_test/verifier_test.bzl#L147-L157.

fix(build): remove duplicate src paths in java_extract_kzip

---

kythe/extractors/gcp/examples/gradle.yaml
kythe/extractors/gcp/examples/guava-android-mvn.yaml
kythe/extractors/gcp/examples/guava-mvn.yaml
kythe/extractors/gcp/examples/mvn.yaml
kythe/go/extractors/constants/constants.go
kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
kythe/go/extractors/gcp/config/testdata/gradle.yaml
kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
kythe/go/extractors/gcp/config/testdata/mvn.yaml

I have separately tagged all of our gcr.io/kythe-public images with
stable.

fix: pin gcp extraction example and tests to :stable

---

kythe/extractors/gcp/examples/gradle.yaml
kythe/extractors/gcp/examples/guava-android-mvn.yaml
kythe/extractors/gcp/examples/guava-mvn.yaml
kythe/extractors/gcp/examples/mvn.yaml
kythe/go/extractors/gcp/config/converter.go
kythe/go/extractors/gcp/config/gradle.go
kythe/go/extractors/gcp/config/maven.go
kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
kythe/go/extractors/gcp/config/testdata/gradle.yaml
kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
kythe/go/extractors/gcp/config/testdata/mvn.yaml
kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
kythe/release/release_test.sh

Since we won't be able to have all extractors and wrappers outputting
clean err/out files like this one does, we'll instead just always print
inline errors.  This also obviates the need to set TMPDIR in
maven/gradle extraction.
This "fixes" #3528 by making it obsolete - no more files, so nothing to
tag.
This starts the ball rolling for #3521, though doesn't really make the
experience around missing kzips any cleaner.

fix: remove javac-extractor.err and .out printing from javac-wrapper.sh

---

kythe/cxx/indexer/cxx/testdata/proto/BUILD
kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl

These build rules will be re-used for some more testing around message
set / extension xrefs.

refactor(build): move cc proto verifier tests into a bzl macro

---

kythe/go/platform/tools/kzip/createcmd/flag.go

The internal flag library requires more of flag.Value, so add `Get()` to the remaining flag types.

fix(kzip_create): implement flag.Getter for all flat types

---

kythe/extractors/gcp/examples/bazel.yaml
kythe/extractors/gcp/examples/gradle.yaml
kythe/extractors/gcp/examples/guava-android-mvn.yaml
kythe/extractors/gcp/examples/guava-mvn.yaml
kythe/extractors/gcp/examples/mvn.yaml
kythe/go/extractors/gcp/config/common.go
kythe/go/extractors/gcp/config/testdata/bazel-multi.yaml
kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
kythe/go/extractors/gcp/config/testdata/gradle.yaml
kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
kythe/go/extractors/gcp/config/testdata/mvn.yaml

This should have been done when I ported from zipmerge to kzip tool.
It's no longer necessary to make the output directory.

chore: remove mkdir step from gcp extraction

---

.bazelrc
.gitignore

Allow an unversioned user.bazelrc in the project root.  This will allow folks to provide project-specific bazel settings that aren't pushed broadly (like, say, `build --config=remote`).

chore: allow user-provided bazelrc

---

kythe/extractors/gcp/examples/bazel.yaml
kythe/extractors/gcp/examples/gradle.yaml
kythe/extractors/gcp/examples/guava-android-mvn.yaml
kythe/extractors/gcp/examples/guava-mvn.yaml
kythe/extractors/gcp/examples/mvn.yaml
kythe/go/extractors/gcp/config/converter.go
kythe/go/extractors/gcp/config/testdata/bazel-multi.yaml
kythe/go/extractors/gcp/config/testdata/gradle-subdir.yaml
kythe/go/extractors/gcp/config/testdata/gradle.yaml
kythe/go/extractors/gcp/config/testdata/guava-mvn.json
kythe/go/extractors/gcp/config/testdata/mvn-multi.yaml
kythe/go/extractors/gcp/config/testdata/mvn-subdir.yaml
kythe/go/extractors/gcp/config/testdata/mvn.yaml

Include the corpus (optionally substituted at request time).  Also
include the builder used (maven, gradle, bazel).
Don't prefix with `kythe_` though, maybe there's disagreement there.

fix: tag google cloud builds

---

kythe/proto/analysis.proto

This should probably also be mentioned in the writing-an-indexer documentation, but I didn't see a particularly good spot for it.

fix(docs): clarify VName documentation in analysis.proto

---

kythe/extractors/bazel/BUILD
kythe/extractors/bazel/Dockerfile
kythe/extractors/bazel/extract.sh
kythe/extractors/bazel/extractors.WORKSPACE
kythe/extractors/bazel/extractors.bazelrc
kythe/release/BUILD
kythe/release/release.BUILD
kythe/release/release.WORKSPACE

Convert Bazel extraction Docker image to use the Kythe release archive as its embedded tooling repository.

release: support release archive as Bazel repository

---

third_party/googlelog.BUILD
third_party/googlelog/BUILD

This fixes `bazel build --incompatible_remap_main_repo //...`

build: remove manually written header include path

---

kythe/cxx/verifier/verifier_main.cc

Visually separating adjacent entries makes it a lot easier to read.

Add newlines between verifier -show_protos output.

---

kythe/cxx/indexer/cxx/KytheGraphObserver.cc

We should distinguish between files when they're compiled with
different build configurations, as otherwise we'll fail to record
(some of) the anchors they share.

fix(cxx_indexer): attach build_config to file claim tokens

---

tools/build_rules/verifier_test/cc_indexer_test.bzl

This also moves the generated files to the bin directory due to https://github.com/bazelbuild/bazel/issues/4858.

build: fix error with --incompatible_new_actions_api

---

external.bzl
go.mod
go.sum

This commit also includes the required bump for xz.

build: update github.com/dsnet/compress to tagged release v0.0.1

---

kythe/release/appengine/buildbot/master/master.cfg.template

Due to https://github.com/bazelbuild/bazel/issues/7674, -k will miss package loading errors.

ci(buildbot): remove --keep_going option from Bazel build

---

kythe/release/BUILD
kythe/release/release_test.sh

lein is very finicky, and requires contortions to integrate into the bazel build (things like self-update, etc).
It's currently broken for internally used JDKs. It also only supports JDK8. 
#3600

release: remove sample web ui

---

kythe/extractors/bazel/Dockerfile
kythe/extractors/bazel/extract.sh

Instead of clobbering ~/.bazelrc, just ensure we use the kythe extractor bazelrc directly.

fix(bazel): Ensure extra actions actually get hooked up.

---

kythe/go/indexer/emit.go
kythe/go/indexer/testdata/basic/anonymous.go

Do not miss emitting definitions for anonymous value types when a
variable declaration duplicates the anonymous type.
Whether to join the duplicate types is left to a later decision.  This
change ensures that the reference to Y2 at least has *a* definition
location.

fix(go_indexer): always emit anchor for anon value types

---

kythe/go/indexer/emit.go
kythe/go/indexer/testdata/override.go

Instead of only adding `overrides` edges for methods of structs declared
within the same or a dependency package, also add `overrides` edges for
struct methods in dependency packages that satisfy a declared interface
in the analyzed package.

fix(go_indexer): handle overrides for structs in a other packages

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

This is some of the initial groundwork necessary for extracting OpenJDK9+ (focusing on 11).  Specifically, it implements the entirety of StandardJavaFileManager interface (which is required when compiling modular sources) and falls back to the first available compiler if the system compiler isn't available (because when compiling the JDK itself the newer compiler uses a non-standard name to avoid conflicting).
Finally, as a hack in Javac9Wrapper.java, restore the  -d flag if present as it is removed by JavaCompilationUnitExtractor but is required for modular builds.

fix(java_extractor): initial work enabling extraction of openjdk11

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java

Internally we still need to support JDK 8. Which is complainy when you try to call methods that don't exist ;-)

fix(java_extractor): use reflection to access/override JDK bits.

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java

All the accidental JDK 9 should be gone now...

fix(java_extractor): replace JDK9 findFirst with loop

---

kythe/release/README.md

We generally produce .kzip files these days, rather than .kindex files.  The README.md should reflect that.

fix(docs): update release docs to specify kzip

---

kythe/docs/schema/schema.txt
kythe/go/indexer/emit.go
kythe/go/indexer/testdata/override.go
kythe/go/indexer/testdata/types.go

The type of any method seen to override an interface method will now
have a `satisfies` edge to the interface method's type.
```
type I interface {
//- @M defines/binding MI
//- MI typed IType
M()
}
type S struct {}
//- @M defines/binding MS
//- MS overrides MI
//- MS typed SType
//- SType satisfies IType    <------ new edge
func (S) M() {}
```

feat(go_indexer): overriding method type satisfies interface method type

---

third_party/leiningen/lein_repo.bzl

(because /bin/sh doesn't always understand pipefail)

fix(leiningen): ensure wrapper script uses /bin/bash rather than /bin/sh

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Deprecation.java

Record the contents of `@deprecated` javadoc tags, and attach them to the
javadoc documentation node under `/kythe/java/deprecated`.

Record @deprecated javadoc tags in the Java indexer

---

tools/build_rules/llvm/cmake_defines.bzl
tools/build_rules/llvm/llvm.BUILD

LLVM uses ncurses for terminfo support and even then only to determine if the terminal supports color.  Barring that it false back to a hard-coded list of TERM values.  We don't really care about this feature anyway so remove the dependency.

fix(cxx): remove dependency on ncurses/terminfo

---

kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java

The referenced javac bug has been fixed:
https://bugs.openjdk.java.net/browse/JDK-8189782

Remove obsolete assertion

---

.bazelrc
WORKSPACE
kythe/release/appengine/buildbot/Dockerfile
kythe/release/appengine/buildbot/master/master.cfg.template

Update .bazelrc to use a remote toolchain corresponding to the minimum supported version, update WORKSPACE to correspond to the minimum tested version and bump the buildbot maximum supported version to reflect the new limit.  Fixes #3650

build: update min/max bazel version to 0.22/0.24

---

kythe/release/appengine/buildbot/.gitignore
kythe/release/appengine/buildbot/Dockerfile
kythe/release/appengine/buildbot/bazelrc
kythe/release/appengine/buildbot/cloudbuild.yaml
kythe/release/appengine/buildbot/deploy.sh
kythe/release/appengine/buildbot/master/master.cfg

Rather than include the sed shenanigans in the deploy.sh script, read them from master.cfg directly.  Also and a cloudbuild.yaml file to allow building buildbot images using GCB.

release: change buildbot config to use secrets directly

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

Leaving this arg in kills our caching and hinders pipeline performance.

fix: remove Option.D from compilation unit again

---

kythe/cxx/extractor/proto/proto_extractor.cc
kythe/cxx/extractor/textproto/BUILD
kythe/cxx/extractor/textproto/testdata/BUILD
kythe/cxx/extractor/textproto/testdata/subdir.UNIT
kythe/cxx/extractor/textproto/testdata/subdir/subdir.pbtxt
kythe/cxx/extractor/textproto/testdata/subdir/subdir.proto
kythe/cxx/extractor/textproto/textproto_extractor.cc

Previously there was an issue where proto file lookup failed if
KYTHE_ROOT_DIRECTORY was set to something other than the current
directory. Additionally, the textproto extractor did not respect
KYTHE_ROOT_DIRECTORY when recording the textproto file path.

fix: handle relative paths correctly in textproto and proto extractors

---

kythe/cxx/common/BUILD
kythe/cxx/common/file_utils.cc
kythe/cxx/common/file_utils.h
kythe/cxx/extractor/BUILD
kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/proto/BUILD
kythe/cxx/extractor/proto/proto_extractor.cc
kythe/cxx/extractor/textproto/BUILD
kythe/cxx/extractor/textproto/textproto_extractor.cc
kythe/cxx/verifier/BUILD
kythe/cxx/verifier/assertions.cc

I think this is a worthwhile refactor on its own, but the reason I'm doing this is so I can easily swap the implementation when in google3. I need to read some files from google-specific filesystems that don't work with `fopen()`.

refactor(cxx): move LoadFileOrDie() into a new file_utils library

---

kythe/go/extractors/config/runextractor/compdb/compdb_test.go

In google3, the c++ extractor calls InitGoogle(), which causes log files
to be written to disk. This commit changes the compdb test to ignore
them instead of trying and failing to extract them as kzips.
Related to https://github.com/kythe/kythe/pull/3695.

fix(compdb_test): ignore log files intead of treating as kzip

---

kythe/docs/kythe-uri-spec.txt

The example puts the root parameter in the wrong place.

docs: fix alternate root example to match URI spec

---

WORKSPACE
version.bzl

Seeing as we have a specific reason we're avoiding 0.25, document that the reason is known and warn users against it for now.

chore(build): add blacklist for known-bad releases (currently 0.25.0)

---

kythe/cxx/indexer/cxx/KytheVFS.cc

clang's Preprocessor::LookupFile always expects FileMgr.getDirectory(".")
to succeed, so we should make sure there's a directory there.

fix(cxx_indexer): always add . to the VFS

---

kythe/cxx/indexer/cxx/frontend.cc
kythe/cxx/indexer/cxx/testdata/kindex_test.unit

The C++ (+ friends) indexer should be hermetic modulo claiming when
reading from extracted compilation units. Currently, it will use the
indexing environment's working directory when one is not set in the
compilation unit (or if the value that was set is not an absolute path).
This PR turns this into an error condition.

fix(cxx_indexer): insist that compilation units have working directories

---

kythe/release/appengine/buildbot/Dockerfile
kythe/web/site/getting-started-macos.md
kythe/web/site/getting-started.md
tools/docker/Dockerfile
tools/platforms/Dockerfile

We haven't needed CMake or SSL libraries to build anything for a while now, remove them from the docs and Dockerfiles.
Document the long-standing requirement for clang >= 3.8

chore(doc): remove cmake/ssl from deps and docs

---

kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

Be explicit about which annotations dependencies are explicit and intended and which are accidental artifacts of the build environment.  This makes it easier to replace the latter and, eventually, remove them.

chore(java_extractor): rename build env jar in test

---

kythe/extractors/gcp/README.md

The yaml templates use _CORPUS as the variable name.

docs: fix examples to use _CORPUS instead of _KYTHE_CORPUS

---

package-lock.json

A run of `npm audit` reported the following vulnerabilities:
```
$ npm audit
│ Moderate      │ Denial of Service
│ Package       │ js-yaml
│ Dependency of │ @commitlint/cli [dev]
│ Path          │ @commitlint/cli > @commitlint/load > cosmiconfig > js-yaml
│ More info     │ https://npmjs.com/advisories/788
│ High          │ Code Injection
│ Package       │ js-yaml
│ Dependency of │ @commitlint/cli [dev]
│ Path          │ @commitlint/cli > @commitlint/load > cosmiconfig > js-yaml
│ More info     │ https://npmjs.com/advisories/813
```
This change was proposed by `npm audit fix` to update the package lock.

fix: update vulnerable outdated js-yaml NPM package

---

third_party/zlib.BUILD

Minor cleanup to only export the actually public headers from zlib (after looking at the README) instead of all of them.

chore(zlib): only export actual public headers from zlib

---

kythe/cxx/extractor/cxx_extractor.cc

Some cuda compilations will expand to more than a single clang invocation and
our extractor doesn't support that at the moment. Work around this by adding
--cuda-host-only to the clang args if we detect a cuda compilation. That will
force a single clang invocation.

fix(cxx): better support cuda extractions

---

kythe/cxx/indexer/cxx/testdata/objc/marked_method.m

Add tests for multi arg and no arg methods. The underlying code
already did the right thing, but now we have a test to provide an
example of what identifier names look like for no argument and multi
argument methods in objective c.

chore(objectivec): Explicitly test multi arg method marked source

---

kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
tools/build_rules/verifier_test/java_verifier_test.bzl

Prior to this PR, importing kythe using the [intellij bazel plugin](https://github.com/bazelbuild/intellij) fails at sync time. The `java_extract_kzip` rule includes a `java_common.compile` action that will fail if the source requires any (non-jvt) deps. The failing targets used annotations that were not declared as deps, but the `java_common.compile` actions were getting pruned as the outputs were not used. The IntelliJ plugin tries to build them because the rule return a `JavaInfo` provider.
This PR renames the existing `deps` attribute to `java_verifier_test` to `verifier_deps` (as it is specifically only meant to be passed `java_verifier_test` targets) and introduces a new `deps` attribute that just gets passed through to the `java_common.compile` action.

java_verifier_tests: declare deps for annotations

---

kythe/cxx/tools/fyi/testdata/compile_commands.bzl

This PR migrates Kythe for
https://github.com/bazelbuild/bazel/issues/7260, which we plan to flip in Bazel 0.27.

Migrate Kythe for Bazel 0.27

---

external.bzl

Roughly 70% improvement in split performance over v0.0.4.
N.B.: This will require updating the internal version when you import, but that should be trivial as there are no API changes.

build: update bitbucket.org/creachadair/shell to v0.0.5

---

kythe/go/serving/pipeline/beam.go

fix(post_processing): split semantic callers within xrefs group

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java

Remove redundant facts emitted by indexer.

fix(java_indexer): only emit MarkedSource for defined symbols

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/MarkedSource.java

This reverts commit 6bfb2f7a46e7704f25073b7f419c34062218765a.
It breaks cross-file references.

revert: "fix(java_indexer): only emit MarkedSource for defined symbols (#3788)

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/common/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java

Experimental feature to support cross-language references for JVM-based
languages.  Currently, the indexer will be highly conservative when
deciding whether to emit references to the JVM language vs Java-native
nodes.  Only nodes within the same source file as the enclosing class
and JDK symbols will be considered Java-native when
--emit_jvm_references is enabled.
See: https://github.com/kythe/kythe/blob/master/kythe/java/com/google/devtools/kythe/analyzers/jvm/DESIGN.md#relations-with-higher-level-jvm-languages

feat(java_indexer): emit refs to JVM graph for externally defined nodes

---

kythe/cxx/extractor/objc_extractor_bazel_main.cc

Bazel captures logs below error. Increase our log level so we actually see the logs during a bazel build.

fix(objc): Log extractor errors

---

kythe/typescript/indexer.ts

Remove a method implemented by the TypeScript compiler.

refactor(typescript_indexer): defer method to TypeScript compiler

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts

Plugins would benefit from determining the name of TypeScript modules in the same manner that the TypeScript indexer does, to ensure compatibility between the TS indexer and its plugins. This PR adds this feature.

feat(typescript_indexer): pass module name creation logic to plugins

---

kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java

The wrapped-for-JDK9 methods will tunnel any exceptions thrown by the target method through an unchecked exception.  Unwrap and propagate those exceptions if possible, otherwise keep the current behavior.

chore(java_common): propagate underlying exceptions if possible

---

kythe/go/platform/tools/kzip/createcmd/createcmd.go
kythe/go/platform/tools/kzip/mergecmd/mergecmd.go

I couldn't decide if it was better to make a EncodingDefault constant = 0, and treat that specially, or do this.

fix(kzip): ensure the EncodingFlag has a suitable default.

---

kythe/go/indexer/markedsource.go
kythe/go/indexer/testdata/code/interface.go
kythe/go/indexer/testdata/code/structtype.go

```
type S struct {}
func f(s *S) {}
```
The MarkedSource for `S` can now be rendered as simply "S" (versus "type S struct {...}") and `f` can be rendered as "f(s *S)" instead of "f(S *type S struct {...})".

fix(go_indexer): use only name for a named type's MarkedSource

---

kythe/go/extractors/cmd/gotool/BUILD
kythe/go/extractors/cmd/gotool/gotool.go

Some go files are conditionally included in the build according to semantic comments at the top of the file. The new `--buildtags` flag allows specifying which of these tags/constraints to enable so that the right files get included by the extractor.
https://golang.org/pkg/go/build/#hdr-Build_Constraints
TODO: is there a cleaner way to have multi-value flags in go?

feat(go extractor): allow specifying go +build tags

---

kythe/cxx/indexer/textproto/analyzer.cc

instead of exiting when bad schema comments are found, log an error and continue

fix(textproto): continue analysis even if schema comments are invalid

---

kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipReaderTest.java

KZipReaderTest.java:98: error: as of release 9, '_' is a keyword, and may not be used as an identifier

fix(java tests): apparently '_' is a keyword now

---

kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java

The test would occasionally fail due to interactions with the old file.
Error msg: "java.lang.IllegalArgumentException: MALFORMED" at java.util.zip.ZipCoder.toString(ZipCoder.java:65).
I'm not 100% sure why this is an issue. Does the kzip writer append to an existing file rather than replacing it? If so, maybe that should be changed instead.

fix(KZipWriterTest.java): remove previous kzip before writing new one

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/export.ts

Fix a long-standing todo where module names in export statements are not
referenced to the modules they refer to. Same approach as referencing
modules in import statements.

feat(typescript_indexer): reference modules in export statements

---

kythe/javatests/com/google/devtools/kythe/platform/kzip/KZipWriterTest.java
kythe/typescript/indexer.ts
kythe/typescript/testdata/object.ts

Shorthand property assignments like foo in a = {foo,} were
previously not indexed at all. This emits edges for shorthand
assignments similar to other property assignments. Also adds xrefs for
computed properties in objects and ignores lvalue literals in a
declaration.
_edit_: new description

feat(typescript_indexer): add xrefs for declarations in objects

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/equals_export.ts
kythe/typescript/testdata/equals_import.ts

Adds support for indexing `import =` and `export =` statements by
extending existing import and export logic. `export =` statements
are given a VName signature of `export =`, similar to how
`export default` statements are given signatures `default`.

feat(typescript_indexer): index export equals and import equals nodes

---

tools/build_rules/verifier_test/kzip_archive.bzl

Add a kzip_archive target which allows direct construction of a compilation unit from given inputs.  This should facilitate writing verifier_test rules for those languages which can use the generic extractor.

feat(build): add generic kzip_archive rule

---

tools/build_rules/verifier_test/kzip_archive.bzl

Take advantage of the fact that `kzip create` passes all of the arguments after a bare `--` to generate shorter command lines.

chore(build_rules): use simpler arguments when invoking kzip create

---

kythe/typescript/indexer.ts

This broke development downstream. Emit a todo rather throw an error
that crashes the process.

fix(typescript_indexer): don't throw on unfound module path

---

kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

Only test for those things which are necessary and expected by the test(s) in question. 
In particular, don't assert on the exact size of various required input lists and only expect that the elements known to the test are present.  Similarly, only test that the Generated annotation is included when the code-under-test actually uses Generated annotations.  When that's the case, we can test for exactly the expected annotation class, regardless of what the JDK uses.

chore(java_extractor): make test less brittle on JDK changes

---

kythe/typescript/BUILD
kythe/typescript/indexer.ts
kythe/typescript/kythe.ts
kythe/typescript/test.ts

Add Kythe types from `kythe.ts` to the indexer. In cases where custom
Kythe facts and edges are used, just cast them to a `FactName` or
`EdgeKind`.

refactor(typescript_indexer): integrate Kythe types in indexer

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/function.ts

Function expressions like `(function())` have no name but introduce a
scope. Add an anonymous name for them when they are encountered in
generated a VName signature.

fix(typescript_indexer): add anon signature part for function expressions

---

kythe/extractors/bazel/extract.sh

Print out the executed commands and exit the script after the first failed
command to make debugging easier and to help avoid silent failures in an early
step that cause unexpected failures in a later step.

fixup: fail extraction after first failed command

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingMetadata.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingMetadata.java.meta
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingProtobufMetadata.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/ProcessingProtobufMetadata.java.pb.meta

Thankfully, the indexer itself doesn't reference `javax.annotation.Generated` directly so won't break in the same fashion as the extractor, but we might as well add support for the new package.

chore(java_indexer): add support and tests for JDK9 Generated annotation

---

kythe/extractors/bazel/extract.sh

tensorflow needs external setup before it can run a bazel build. It
needs to have certain Python pips present and it needs to run a
configure script before builds can be done. See https://www.tensorflow.org/install/source.

feat: Add commands necessary for tensorflow builds

---

kythe/go/extractors/cmd/gotool/analyze_packages.sh

Followup to https://github.com/kythe/kythe/pull/3890 that adds the same pre-build step to the go extractor image.

feat: add KYTHE_PRE_BUILD_STEP handling to go extractor image

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/template/template_class_ctor_deduction.cc

Incidentally fixes and enables the test for #2894

fix(cxx_indexer): properly reference C++17 deduced templates

---

kythe/extractors/BUILD

When Kythe annotates protos, the resulting java code depends on jsr250. The
default proto runtime doesn't include this dep so we need to manually include
it in a custom runtime for our custom proto lang toolchain.

fixup: Add jsr250 dep for Kythe annotated protos

---

kythe/release/release.BUILD

This is the same change as #3910 but applied to our proto lang toolchain rule we expose in our release

fixup: Add jsr250 to our release proto toolchain

---

kythe/typescript/SCHEMA.md
kythe/typescript/indexer.ts
kythe/typescript/testdata/object.ts
kythe/typescript/testdata/schema.ts

Add support for indexing string and numeric literals in property names,
and referencing string and numeric literals in a property access.

feat(typescript_indexer): add support for indexing literal properties

---

readme.md

this accidentally got pulled in when the kythe/lang-proto repo got merged.
The actual readme for kythe is README.adoc.

docs: remove obsolete readme.md

---

tools/cpp/generate_compilation_database.sh

Don't try to build manual targets when using the generate compilation database script.

fixup(c++): Don't build manual targets

---

kythe/extractors/bazel/BUILD
kythe/extractors/bazel/extract.sh

We use the `--keep_going` flag so that we can extract all buildable targets even if some other targets fail.
If bazel fails to build some packages, but otherwise succeeds in extracting, the exit code is 1. Other
errors like "bazel server died unexpectedly" give other exit codes and will now cause the
extractor script to fail.

fix(bazel extractor): better handling of bazel exit code

---

external.bzl
kythe/java/com/google/devtools/kythe/analyzers/base/BUILD
kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/base/NodeKind.java
kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/MarkedSources.java
kythe/java/com/google/devtools/kythe/extractors/java/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/InputUsageRecord.java
kythe/java/com/google/devtools/kythe/platform/java/BUILD
kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
kythe/java/com/google/devtools/kythe/platform/shared/BUILD
kythe/java/com/google/devtools/kythe/platform/shared/KytheMetadataLoader.java
kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java

This version of `@Nullable` is usable in TYPE_USE and TYPE_PARAMETER contexts (e.g. it permits declaring `List<@Nullable String>`); it also is used by the [checker framework](https://checkerframework.org) nullness analysis. .

chore: use checkerframework @Nullable annotation

---

kythe/extractors/bazel/extract.sh

We shouldn't quote the target expression variable because we want the underlying
script/program to interpret each target expression individually, we don't want
the program to get a single target expression that contains white space.

fix: Properly handle target expressions

---

kythe/go/extractors/cmd/gotool/gotool.go

the extractor only handles kzip

docs(go extractor): remove mention of kindex and indexpack

---

kythe/go/platform/tools/kzip/infocmd/infocmd.go

The motivation for this change is to make `kzip info` more useful for validating kzips. A few things we can check using this new info:
* compare counts between different versions of a kzip from the same repo to detect large changes.
* check that a kzip contains compilation units only from the corpus it has been assigned. 
* the corpora of other input files in the kzip can be different, but are something we're interested in keeping track of
TODO:
* is there any other info we want to record?
* naming of keys in the json output?
Example usage:
```
$ kzip info --input github.com_knative_pkg.kzip                            
57 compilation units, 828 input files, corpora: {"github.com/knative/pkg", "golang.org"}
Unit Counts (by corpus, language):
github.com/knative/pkg
go: 57
File Counts (by …
```

feat(kzip tool): add more details and json output mode to `kzip info`

---

external.bzl
kythe/examples/proto/BUILD
kythe/extractors/BUILD
kythe/go/util/riegeli/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/BUILD
kythe/proto/BUILD
setup.bzl
third_party/bazel/BUILD

For now, they are just wrappers around the native rules, but their usage will become mandatory in Bazel 1.0 (issue bazel#8922).

build: migrate to Starlark Proto rules

---

kythe/go/services/xrefs/xrefs.go

Sometimes it is ok to return PERMISSION_DENIED instead of NOT_FOUND,
when protecting the name of an asset isn't necessary.
Be careful to not use this when protecting even the existince of some
thing is important - the nit would be better to still return NOT_FOUND.

fix: add an ErrPermissionDenied for services to return

---

kythe/release/appengine/buildbot/Dockerfile
kythe/release/appengine/buildbot/master/master.cfg
tools/arc/linter.sh

Update buildbot to use latest clang/Go versions (7.0 and 1.12.7) and their formatters.

ci(buildbot): add builder to run 'arc lint'

---

kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/javatests/com/google/devtools/kythe/platform/java/BUILD

In particular the Bazel extractor has not been updated as it actually needs the --patch-module flags.
Also updates the check for "jdk-owned" modules.

fix(java_build): remove jvm_flags which complicate running on newer JDKs

---

kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/extractors/golang/golang.go

This isn't used anywhere - should it be?

cleanup(go extractor): remove unused --local_path flag

---

kythe/cxx/extractor/proto/testdata/custom_corpus.UNIT
kythe/cxx/extractor/proto/testdata/custom_root_directory.UNIT
kythe/cxx/extractor/proto/testdata/custom_vname_config.UNIT
kythe/cxx/extractor/proto/testdata/duplicate_imports.UNIT
kythe/cxx/extractor/proto/testdata/duplicate_imports2.UNIT
kythe/cxx/extractor/proto/testdata/kzip_diff_test.sh
kythe/cxx/extractor/proto/testdata/multiple_source_files.UNIT
kythe/cxx/extractor/proto/testdata/proto_extractor_test.bzl
kythe/cxx/extractor/proto/testdata/relative_imports.UNIT
kythe/cxx/extractor/proto/testdata/simple.UNIT
kythe/cxx/extractor/textproto/testdata/custom_corpus.UNIT
kythe/cxx/extractor/textproto/testdata/deps.UNIT
kythe/cxx/extractor/textproto/testdata/extra_imports.UNIT
kythe/cxx/extractor/textproto/testdata/multiple_proto_files.UNIT
kythe/cxx/extractor/textproto/testdata/simple.UNIT
kythe/cxx/extractor/textproto/testdata/subdir.UNIT
kythe/cxx/extractor/textproto/testdata/without_schema.UNIT
kythe/cxx/tools/BUILD

* The meaningful part of this change is in kzip_diff_test.sh, most everything else is golden file updates
* Using `kzip view` instead of `kindex_tool -explode` to get units out of kzips.
* Fields that we don't want to diff test are removed with `jq` instead of bash functions and `awk`.
* Resulting unit files and goldens are now json instead of textproto

cleanup(tests): use kzip instead of kindex_tool in proto/textproto tests

---

kythe/cxx/extractor/proto/testdata/custom_corpus.UNIT
kythe/cxx/extractor/proto/testdata/custom_root_directory.UNIT
kythe/cxx/extractor/proto/testdata/custom_vname_config.UNIT
kythe/cxx/extractor/proto/testdata/duplicate_imports.UNIT
kythe/cxx/extractor/proto/testdata/duplicate_imports2.UNIT
kythe/cxx/extractor/proto/testdata/kzip_diff_test.sh
kythe/cxx/extractor/proto/testdata/multiple_source_files.UNIT
kythe/cxx/extractor/proto/testdata/proto_extractor_test.bzl
kythe/cxx/extractor/proto/testdata/relative_imports.UNIT
kythe/cxx/extractor/proto/testdata/simple.UNIT
kythe/cxx/extractor/textproto/testdata/custom_corpus.UNIT
kythe/cxx/extractor/textproto/testdata/deps.UNIT
kythe/cxx/extractor/textproto/testdata/extra_imports.UNIT
kythe/cxx/extractor/textproto/testdata/multiple_proto_files.UNIT
kythe/cxx/extractor/textproto/testdata/simple.UNIT
kythe/cxx/extractor/textproto/testdata/subdir.UNIT
kythe/cxx/extractor/textproto/testdata/without_schema.UNIT
kythe/go/util/formatjson/BUILD
kythe/go/util/formatjson/formatjson.go

unfortunately `jq` is not available in google3, so I changed the tests
back to awk for skipping nondeterministic fields and python's json.tool
for formatting. Because python's json output is different than jq's, all
our golden files had to be updated too.

fix(tests): make proto/textproto tests not rely on `jq`

---

kythe/cxx/extractor/README.md
kythe/cxx/extractor/cxx_extractor_main.cc
kythe/cxx/extractor/objc_extractor_bazel_main.cc
kythe/cxx/extractor/testdata/run_cxx_bazel_extraction.sh
kythe/cxx/extractor/testdata/run_objc_bazel_extraction.sh

The cxx extractor only supports kzip outputs

fix(cxx_extractor): update comments to mention kzip instead of kindex

---

kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java

If no JRE 8-style jars are found, fall-back to finding the default
bootclasspath for JRE 9+ using a StandardFileManager instance.

fix(java_indexer): dynamically resolve JRE 9 bootclasspath

---

kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java

The Java indexer uses the JavaFileObject's URI host as a key for looking up (or constructing) a file VName.  While it should likely just use the path directly, it's easy enough to support this in CompilationUnitPath for now.

fix(java_common): add file digest as Path URI host

---

kythe/docs/schema/schema.txt

* We weren't listing or testing variable subkinds for Java.
* Notation used in property-related edges suggested that
`property` nodes were called `variable/property` instead.
I don't believe this was the intention.
* We expect to see aliases used for imports.

fix(doc): clarify variable subkinds and aliases edge

---

kythe/go/serving/xrefs/BUILD
kythe/go/serving/xrefs/xrefs.go
kythe/go/serving/xrefs/xrefs_test.go
kythe/go/util/flagutil/flagutil.go

Add `--experimental_cross_reference_indirection_kinds` flag, a multimap
from node kind to edge kinds, to Kythe xrefs server.  When handling a
CrossReferences request, if a requested node has a specified node kind,
all related nodes passing through one of the specified edge kinds will
be added the merged node set for the request.  This allows for dynamic
single-directional, top-down indirection through nodes such aliases or
universal name nodes.

feat(serving): experimental support for xrefs indirection

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/typeof.ts

'typeof' appears in type expressions and takes a value as its argument,
so when we encounter one we continue recursion using the value visitor
visit() instead of the type visitor visitType().

typescript: handle 'typeof'

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts

Emit a reference between "this" keywords that have a particular type and
the type of the object they refer to. For instance,
```typescript
//- @C defines/binding CType
class C {
foo() {
//- @this ref CType
this.foo();
}
}
```
Nothing is done for "this" keywords that do not refer to any particular
type. In
```typescript
let obj = {
foo() {
this.foo();
}
}
```
`obj` has no particular type other than `object` and so no reference is
emitted. The same applies to class expressions.

feature(typescript_indexer): emit reference for "this" keyword

---

kythe/typescript/package.json
kythe/typescript/yarn.lock

There are no changes needed for this particular upgrade but it's good to
keep this in sync with current TypeScript in case the difference
matters.

typescript: update from 3.3 => 3.5

---

tools/arc/linter.sh

See discussion at #3982. The linter currently checks .lock files for
copyright headers, which do not need to have one.

fix(lint): ignore .lock files in copyright checks

---

kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/IndexerFrontendAction.h
kythe/cxx/indexer/cxx/KytheIndexerMain.cc
kythe/cxx/indexer/cxx/frontend.cc
kythe/cxx/indexer/cxx/indexer_worklist.cc
kythe/cxx/tools/fyi/fyi.cc
kythe/cxx/tools/fyi/fyi_main.cc

The former is going away now that LLVM has switched to C++14 upstream

chore(cxx_common): replace uses of llvm::make_unique w/ absl::make_unique

---

kythe/web/site/Gemfile.lock

CVE-2019-5477 is fixed in 1.10.4

fix: bump nokogiri to 1.10.4

---

.bazelrc
kythe/web/site/getting-started.md

Fixes #4006. Recent versions of LLVM require some C++14 features, which may not be enabled by default. Ensure Bazel enables them for local builds as well as remote (CI) builds.
Also mention the need for C++14 in the setup instructions, to aid someone trying to debug this from an old configuration (as I did).

fix(build): include C++14 options in default build flags

---

tools/arc/linter.sh

Use the more detailed diff options to output arc-lint compatible messages on changed lines rather than just reporting the first line of the file.

feat(linter): report better messages when clang-format fails

---

kythe/cxx/common/path_utils_test.cc

This fragile-ly just removes the symlink at the end of the test; a more robust approach would be to use a text fixture, and ideally, a per-test-run tmp dir.

fix: clean up link in temp dir for test

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh

If the extractor or javac calls in the wrapper fail, the wrapper should return an error code.

fix(javac-wrapper): use `set -e` to propagate errors

---

external.bzl

This also switches to using git_repository over http_archive to do the fetch because it potentially makes updates easier and more clearly encodes the branch requirement.

chore: update boringssl and use github mirror

---

kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
kythe/javatests/com/google/devtools/kythe/extractors/java/BUILD

Without this, if the JDK under which we're running the extractor is newer than the patched-in version of langtools, we'll fail to read .class files provided by the JDK (as they have a newer language version set).

fix(java_extractor): and tests should use ambient langtools

---

kythe/cxx/indexer/cxx/ImputedConstructorSupport.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/libraries/make_shared_factories.cc
kythe/cxx/indexer/cxx/testdata/libraries/make_unique_factories.cc

It appears as though is was already supported, but just needed whitelisting and testing.

fix(cxx_indexer): whitelist and test std::make_shared

---

kythe/extractors/bazel/Dockerfile

This version of clang supports the cc_configure change made in https://github.com/bazelbuild/bazel/commit/cdd0c3cdba270115940e8ca5ec8104cbcd694671#diff-9899f9deb6047fe5ab4a4d2f8a96122e.

fix(extraction): update bazel-extractor Docker image to clang-6.0

---

kythe/java/com/google/devtools/kythe/analyzers/indexer.bazelproject

There is no need to build all java verification test sources in intellij

fix: be more precise for ijwb targets

---

kythe/go/platform/kzip/kzip.go

Kzips were setting the internal file modification times to when the kzip was
created. This prevents bazel from caching the results since each time the extra
action is run, it will produce a different kzip.

fix(extractors): Don't include kzip creation time in kzip

---

kythe/go/platform/kzip/info/BUILD
kythe/go/platform/kzip/info/info.go
kythe/go/platform/kzip/info/info_test.go

This is useful when extraction results are spread among multiple
kzips and we want to know the combined details.

feat(kzip): add function for merging multiple KzipInfos together

---

kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java

Don't include time in kzips so diffs only compare the contents of the kzip, not when it was created.

fix(extractor): Don't include time in kzips for java

---

kythe/cxx/common/kzip_writer.cc

Don't include the kzip creation time in cxx kzips so kzips can be compared on only on contents, not on when they were created.

fix(extractor): Set cxx extractor kzip times to a constant

---

kythe/extractors/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go
kythe/go/util/tools/print_extra_action/BUILD
kythe/release/release.BUILD

The go bazel rules we use now produce a GoCompilePkg action instead of a
GoCompile action.

fix(go): Change action go bazel extractor runs on

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/compilefail.ts
kythe/typescript/testdata/tsconfig.for.tests.json

This change makes us ignore TypeScript errors and index the parts
of the program that still have type information.  Previously we would
abort.
TypeScript in general has lots of accomodations around programs with
errors, so it's no trouble for TypeScript to do this.  (For example,
the compiler still wants to provide jump-to-definition features even
if you have a type error elsewhere in the same file.)
Within Google we don't run programs that have errors so code in this
state is rare, with one major exception: Clutz
(https://github.com/angular/clutz) output is invalid when its input
JavaScript is also invalid.  So this change has the main effect of
making Kythe able to index Clutz output.
We already had a test that exercised what happens when you have
bad input, so I adjusted that slightly …

typescript: index inputs that contain errors

---

kythe/go/platform/kzip/info/BUILD
kythe/go/platform/kzip/info/info.go

* unit vnames typically omit the corpus, so determine it from the
contained source files instead.
* file vnames omit the language, so determine it from the unit vname.
To test, I ran `kzip info` on a recent kzip of the kythe repo before and after this code change. Here's a partial diff of the output:
```diff
"com_google_protobuf": {
"files": {
-        "": 1862
+        "c++": 39,
+        "java": 1816,
+        "protobuf": 7
},
"units": {
-        "c++": 1
+        "c++": 1,
+        "java": 2
}
},
"com_google_re2j_re2j": {
"files": {
-        "": 2
+        "java": 2
},
"units": {}
},
"cstdlib": {
"files": {
-        "": 27034
+        "c++": 27034
},
"units": {}
},
"github.com/kythe/kythe": {
"files": {
-        "": 22511
+        "c++": 17012,
+        "java": 1380,
+        "jvm": …
```

fix(kzip info): determine unit corpus and file language more robustly

---

kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
kythe/javatests/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemTest.java

As the FileDataProvider stub is typically an RPC endpoint which can be shared between CompilationUnitFileSystems, a single file system should not close it.

fix(java_common): cufs shares FileDataProvider and should not close it

---

kythe/extractors/BUILD
kythe/extractors/bazel/README.md
kythe/release/release.BUILD

The ng_module produces actions with the AngularTemplateCompile mnemonic (not
TypeScriptCompile). The two actions should both produce extra action data that
can be processed by the same extraction config.

feat(typescript): Support AngularTemplateCompile mnemonic

---

kythe/typescript/indexer.ts

We don't want to clutter our logs with 'plugin is running' messages,
given that they always run.

drop a log line that always prints

---

kythe/go/extractors/golang/golang.go

A recent PR (#4069) added logic to add a GoPackageInfo details message from
addFiles(). addInput() calls addFiles(), then overrides the vname of the file,
so we need to also invalidate the old GoPackageInfo message. If not, we end up
with two conflicting mappings for the 'canonical' import path.

fix(go extractor): fix invalid Details messages for packages

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
kythe/java/com/google/devtools/kythe/platform/java/JavacAnalysisDriver.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

This also refines the path logic within CompilationUnitPathFileManager to restrict the use of the underlying filesystem to *only* bootclasspath paths which aren't present in the CompilationUnit and updates the various comments to more accurately describe the desired semantics.

feat(java_indexer): command line option to use path-based file manager

---

kythe/java/com/google/devtools/kythe/extractors/java/InputUsageRecord.java
kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java

Often, the first use of a path is unaware of the location, so allow that to be filled in on subsequent uses, if possible.
Also, use Optional instead of Nullable to indicate the appropriate semantics here.  `.orElse(null)` is used here to avoid dealing with the two separate Optional types.

feat(java_extractor): use Optional<Location> and allow updating it

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

The only thing which currently uses the working_directory from Java is the `CompilationUnitPathFileSystem`, but with this enabled that Just Works with modular compilation units, without having to do much surgery to the paths provided on the command line.

fix(java_extractor): include working directory in extracted proto

---

kythe/extractors/openjdk11/extract/extract.go

I'm not sure when this changed, but including the workspace name now fails to find Bazel runfiles, whereas it was previously required.

fix(jdk_extractor): bazel runfiles no longer expect the workspace name

---

kythe/java/com/google/devtools/kythe/analyzers/base/EntrySet.java

We've seen warnings emitted from finalize() in non-error cases, suspicion is that it may be caused by memory barrier propagation (finalize runs in a different thread).

fix: EntrySet::emitted becomes volatile

---

kythe/release/setup_release.sh

clog is used to create the release notes, so make sure it is installed before creating a release.

fix(release): Make sure clog is installed

---

kythe/java/com/google/devtools/kythe/analyzers/base/EntrySet.java

This isn't perfect; if `emit()` throws and is retried, we'll get a different spurious warning. (as @creachadair suggested in #4140, the emitter is where this tracking belongs, if it belongs anywhere at all.)

fix(java): record EntrySet emission before calling emitter

---

kythe/extractors/bazel/BUILD
kythe/extractors/bazel/Dockerfile
kythe/extractors/bazel/extract.sh
kythe/extractors/bazel/extractors.bazelrc
kythe/release/BUILD

This config adds extra_action_listeners for each of the extractors in the kythe release, so extraction can be done in a simple invocation of bazel:
```shell
KYTHE_RELEASE=/opt/kythe
bazel \
--bazelrc=$KYTHE_RELEASE/extractors.bazelrc
build \
--override_repository kythe_release=$KYTHE_RELEASE \
//targets/to:extract
```

feat(release): add extractors.bazelrc to release

---

tools/cpp/generate_compilation_database.sh

fix(tools): fix generate_compilation_database on macOS (#4166)

---

kythe/extractors/bazel/Dockerfile

without this flag, tar was assigning a file owner from the host machine that didn't exist in the docker image

fix(bazel-extractor): fix permissions when extracting release archive

---

RELEASES.md
kythe/release/BUILD

I'd like to make a new release so I can use https://github.com/kythe/kythe/pull/4163.
I ran `./kythe/release/setup_release.sh` on `master` to generate this commit, but the release notes are empty.  I don't know if I ran it wrong or if the script is broken.

release: v0.0.32

---

kythe/typescript/test.ts
package-lock.json
package.json

Today TS test runs test files one at a time. This makes it impossible to
test scenarios that check references between multiple files. For example
when TS file requires module declared in `.d.ts` file. In this scenario
both `.ts` and `.d.ts` files must be passed togeter to indexer and
verifier.
This commit changes the way how test files are scanned by test. Now
test files passed as array instead of single file. All `.ts` files
immediately places inside testdata/ are still passed as array of single
files. Files in subfolders of testdata/ are passed as single array, one
per subfolder.

refactor(typescript_indexer): allow to pass multiple files in indexer test

---

kythe/java/com/google/devtools/kythe/extractors/jvm/JvmExtractor.java

This reverts commit 8b2c5e4390c8be89f8cbb162a826441794599850.

Revert "fix(jvm extractor): use class files as srcs, not jar (#4179)"

---

kythe/go/indexer/BUILD
kythe/go/indexer/cmd/go_indexer/go_indexer.go
kythe/go/indexer/emit.go
kythe/go/indexer/testdata/basic/scopes.go
kythe/go/indexer/testdata/go_indexer_test.bzl

This generalizes the `ref/call` scopes to all identifier references like https://github.com/kythe/kythe/commit/0a3afc9bffba3e09c638ae28575605a1441ebf5e does for the Java indexer.

feat(go_indexer): option to emit an edge for an anchor's semantic scope

---

kythe/typescript/indexer.ts

This introduces a backwards compatible shim for
ts.isParameterPropertyDeclaration that works in TS3.5 & TS3.6.

chore(typescript_indexer): TypeScript 3.6 compat.

---

kythe/extractors/bazel/Dockerfile

PR #4180 changed how we get maven artifacts and broke //kythe/extractors/bazel:docker. The jar files are located in a different path.

fix(extractor): fix jsr250 path after #4180

---

kythe/data/BUILD
kythe/data/simple_vnames.json
kythe/release/BUILD
kythe/release/release.BUILD

Provide a flag for using the old behavior, which maps external projects to their own corpora:
`--define kythe_assign_external_projects_to_separate_corpora=true`
I'm open to better names for this.

feat(bazel extractor): put everything in the same corpus by default

---

kythe/go/platform/kzip/info/info.go
kythe/go/platform/kzip/info/info_test.go

this works around the fact that log("%v", proto) is inconsistent about spacing in open source go vs google3

fix(kzip info): trim extra spaces from error message

---

kythe/java/com/google/devtools/kythe/analyzers/base/CorpusPath.java
kythe/java/com/google/devtools/kythe/analyzers/jvm/DESIGN.md
kythe/java/com/google/devtools/kythe/analyzers/jvm/JvmGraph.java

It may be desirable to separate JVM nodes by corpus (and possibly
root/path).  This is important when mixing two similar corpora that
defines many of the same JVM entities that should not be considered
identical.  It is left up to the indexer whether to incorporate a
corpus/root/path into their emitted JVM nodes.

feat(jvm_indexer): allow JVM nodes to be refined by corpus/root/path

---

RELEASES.md
kythe/release/BUILD

This release is primarily to fix java proto extraction, which requires jsr250.j-api-1.0.jar.

release: v0.0.35

---

kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java

The filemanager sometimes logs errors to stderr without any context and that makes it more difficult than it should be to debug problems. Add an explicit log invocation in all methods called via reflection. We could add the log to non-reflective calls as well, but that would be a more invasive change.

chore(java indexer): log filemanager exceptions

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
kythe/java/com/google/devtools/kythe/platform/java/BUILD
kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
kythe/java/com/google/devtools/kythe/platform/java/JavacAnalysisDriver.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

The Java libraries handle the system module path in a special way so our normal
methods for reading from a compilation unit instead of the local file system do
not work. The easiest way to deal with this is to treat system modules
specially in our indexer and unpack them to a local temp directory for java to
read from. This is not ideal because it pollutes the local file system but given
what the Java libraries do, it doesn't look like there are any better options.
H/T @shahms for the majority of this PR.

feat(java indexer): better support system modules

---

kythe/go/platform/kzip/info/info.go

Scanning a kzip can be slow for large files, so if multiple operations
need to be done, it's preferable that they all be done in one
kzip.Scan() instead of separately. This change moves most kzip info
logic into an "Accumulator" class that can be called from your own
invocation of kzip.Scan().
The motivation for this is that I need to get summary info for a kzip
and also search for certain units by file path. Doing these in one
kzip.Scan() saves a lot of time.

refactor(kzip info): allow composing other operations in kzip.Scan

---

kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

Store the absolute path for the temp directory so we don't have to compute it for every getPath call

chore(java indexer): Store absolute path

---

kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
kythe/java/com/google/devtools/kythe/platform/java/JavacAnalyzer.java

A few values from compilation details may be null so return an optional so it
is easier to make sure the clients use them correctly.

chore(java indexer): Use optional for possibly empty values

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java
kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java

We may store some temporary files on disk when we create our file manager. Normally we clean them up when the compilation details object is closed, but if an exception happens before we return the compilations details object, we will leave artifacts on disk. Handle exceptions while we are creating the compilation details object so this doesn't happen.

fix(java indexer): Clean up after exceptions

---

kythe/web/site/examples.md

The extract.sh script is meant to be run in a docker container. The
instructions on our examples page no longer work, so remove it. There is
still a reference to this script later in the page, but that is a more
invasive change and will require more work to update.

chore(doc): remove stale script

---

kythe/data/simple_vnames.json

Paths under 'external/' correspond to external dependencies pulled in
via the WORKSPACE file. Because these files are not present in the main
repo, they must be given a 'root'.
As an example, string_view.h from abseil was previously given a vname like:
path: "external/com_google_absl/absl/strings/string_view.h"
After this change, the vname is:
root: "external/com_google_absl"
path: "absl/strings/string_view.h"

fix(bazel extractor): give external paths a root

---

kythe/extractors/BUILD
kythe/extractors/bazel/extractors.bazelrc
kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java
kythe/release/release.BUILD

It appears as though the `--cc_proto_library_header_suffixes` flag works for the .meta files (after manual testing), thus we can use distinct .meta files generated by whatever the source tree in question expects, rather than the version used to compile our release.

fix(extractors): use distinct proto meta files for cc_proto_library

---

RELEASES.md
kythe/release/BUILD

This release contains the fixes for the proto extractor version issues from #4234.

release: v0.0.37

---

kythe/data/simple_vnames.json

Followup to https://github.com/kythe/kythe/pull/4233. The VName path
should be the path we want this file to show up at in the UI.
Before:
root: "external/com_google_absl"
path: "absl/strings/string_view.h"
After:
root: "external"
path: "external/com_google_absl/absl/strings/string_view.h"

fix(bazel extractor): change vnames for external paths

---

kythe/java/com/google/devtools/kythe/platform/shared/filesystem/ByteBufferByteChannel.java
kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystem.java
kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitPath.java

Rather than reading all file contents upfront, initiate the read on creation, but don't wait for it to complete until necessary.  This more closely follows the behavior of the legacy JavaFileObjects

chore(java_common): allow for lazily reading file contents

---

external.bzl
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
kythe/java/com/google/devtools/kythe/analyzers/jvm/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/jvm/BUILD
kythe/typescript/BUILD
tools/build_rules/lexyacc/BUILD
tools/build_rules/verifier_test/cc_indexer_test.bzl

While this doesn't fix the underlying bug (due to a problem in one of our myriad dependencies), it does clean things up a bit.

chore: run buildifier-lint as part of #4264

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/reexport/main.ts
kythe/typescript/testdata/reexport/reexport.ts

Some symbols like interfaces don't have VALUE nodes and only have TYPE
nodes. This commit fixes refs for such symbols.
Tested:
unit test

fix(typescript_indexer): emit refs to TYPE nodes in export statements

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java

The errorprone plugin complicates the build due to certain other
flags it requires (such as -XDcompilePolicy=byfile) and is not
necessary for extraction.
Another workaround would be to disable the errorprone plugin in the
project's gradle config, but that's often a fairly invasive change
(AFAIK) and requires removing config options in several places.

fix(java): disable errorprone plugin for java extraction

---

RELEASES.md
kythe/release/BUILD

* **java:**  disable errorprone plugin for java extraction (#4268) ([08b674ea](https://github.com/kythe/kythe/commit/08b674ea71a5481bbcc9901ae214304e9fd7f658))
* **serving:**  avoid nil when serving data is missing SourceNode (#4269) ([02a41e88](https://github.com/kythe/kythe/commit/02a41e88122ae88a2e4041b766ed8c63d344b76f), closes [#4128](https://github.com/kythe/kythe/issues/4128))
* **typescript_indexer:**  emit refs to TYPE nodes in export statements (#4247) ([cd3f14df](https://github.com/kythe/kythe/commit/cd3f14df68978b6271f3bedd6f5a720351dfcc72))

release: v0.0.39

---

kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

This appears to address the remaining performance differences between the new filemanager and old.
Notes on implementation decisions:
- Rather than caching indefinitely, the ListenableFuture is removed from the cache when read.  This is because both the underlying FileObject and analyzer_driver cache the file data, so adding a third copy seemed wasteful.
- This could be made optional as it does over-estimate the files needed.  That overzealous reading is fairly minor, however, given the pruning done by the extractor, so I opted to avoid the additional complexity of plumbing through a flag, but can do so if desired.

fix(java_indexer): enable readahead in new filemanager

---

kythe/cxx/doc/BUILD
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/proto/BUILD
kythe/cxx/tools/fyi/BUILD
kythe/cxx/verifier/BUILD

Generally, files which define `main` should be `cc_binary` unless it's something like gtest_main, which defines a general purpose reusable `main`.  Or, to paraphrase Indiana Jones: "These [mains] belong in a [cc_binary]!".

chore: libraries with main should be binaries

---

external.bzl
kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/BUILD
kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

Part of addressing #3671 in the indexer.

fix(java_indexer): use in-memory class_output path for modular builds

---

kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java

In the case when we're running on JDK8 the method stubs will be null and this turns calls of those stubs from NullPointerException into UnsupportedOperationException and does the same for other exceptions arising from incompatibilities in the reflective call (but not exceptions arising from the underlying code).

fix(java_common): filemanager NPE => UnsupportedOperationException

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java

Without this the logs are filled with:
```
Jan 22, 2020 9:20:12 AM com.google.devtools.kythe.analyzers.java.KytheTreeScanner loadImplicitAnnotationsFile
WARNING: Can't read metadata for x-kythe-compilation://....
```
for *every* file.

fix(java_indexer): only attempt to load implilcit metadata if it exists

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheJavacAnalyzer.java

The extractor doesn't currently include files or packages only mentioned in transitive `module-info.java` files, leading to benign warnings from the indexer.  As these are harmless, downgrade diagnostics for module-info.java to INFO rather than WARNING.  Additionally, group all diagnostics per-file.

chore(java_indexer): group and classify diagnostics per-file

---

kythe/typescript/package.json
kythe/typescript/yarn.lock

Node 10 is the current LTS version, and test.ts already depends on some
of its functionality.

typescript: depend on node v10 definition of types

---

kythe/typescript/test.ts

The test suite attempted to cache the standard library, but it only
cached one file, and the library is now ~10 files.
Fix this by caching all files that are in the standard library
directory.  This makes all test cases (after the first, which primes
the cache) roughly 10x faster.

typescript: smarter cache of standard library

---

kythe/typescript/test.ts

If the indexer throws during a test, ensure that the test suite
fails gracefully.

typescript: handle indexer crashes in tests

---

kythe/typescript/indexer.ts

This will let subsequent changes also run autoformatter, without causing
random churn on these lines.

typescript: run autoformatter

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/compilefail.ts

In some cases we encounter a symbol that doesn't have an associated
VName.  Rather than crashing, change the calling code to move on to
subsequent code by adding a million return statements.
The associated test adds more badly formed code that reproduces this
problem.  The test will crash without the corresponding indexer change.

typescript: handle the case where symbol has no name

---

kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go

Logging the command we are running makes it easier to understand error messages that come from cmake.

chore(cmake): log the command we are running

---

kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go

Set the compiler id in cmake to clang so repos that generate different commands based on the compiler ID will generate the correct commands for us.

chore(cmake): Tell cmake we are clang

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java

This changes semantics slightly, so I want to put it into a small and targeted change to keep the Chesterton's Fence damage radius small.  Notable semantic differences:
1) Single-empty-element search paths will be set on the file manager (previously, both [] and [""] would be excluded).
2) Paths are only set on the fileManager, rather than being set on the fileManager and injected into the command line.  This means that if those flags are present on the command line, they will override the specified values.  This shouldn't be a problem as non-Bazel extractors currently pull these search paths out of the command line and then re-inject them, but is something to watch out for.
3) Uses configured fileManager for the processor search path, rather than the iterables directly, but the semantics …

feat(java_extractor): allow passing search paths as a map

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

This fixes extraction so that the go indexer can correctly add cross-references
for import statements. I tested this by extracting the cmdutil package
in this repo after making these changes and indexing the resulting
compilation unit.
I'm having trouble finding documentation on -arc, but it seems to do the same
thing as -importpath, except for archive files. See for example the arguments
list for the kythe/go/util/cmdutil/cmdutil.go compilation unit:
```
"argument": [
"bazel-out/host/bin/external/go_sdk/builder",
"compilepkg",
"-sdk",
"external/go_sdk",
"-installsuffix",
"linux_amd64",
"-src",
"kythe/go/util/cmdutil/cmdutil.go",
"-arc",
"github.com/google/subcommands=github.com/google/subcommands=bazel-out/k8-fastbuild/bin/external/com_github_google_subcommands/linux_amd64_stripped/go_def …
```

fix(go extractor): treat -arc flag like -importpath

---

kythe/typescript/indexer.ts

From the TypeScript compiler source, it's possible for
symbol.valueDeclaration to be undefined, and within Google we have code
that crashes on it being undefined.
I have been unable to come up with a test case that reproduces this
crash, so instead I just looked for references to .valueDeclaration in
the code and added an additional check at each reference.
(You might ask, doesn't TypeScript's type system help with exactly this
problem?  And the answer is yes, but the TS compiler API itself
unfortunately lies in its types, and claims that .valueDeclaration is
never undefined. Sadness.)

don't assume Symbol.valueDeclaration exists

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java

This splits the extraction task into a separate class which is responsible for doing most of the setup of the extraction, but decouples this from turning the results into an AnalysisResults and CompilationDescription class.  This should make it easier follow and change in the future, in particular with an eye towards more accurately extracting openjdk11.

chore(java_extractor): refactor extraction into a separate class

---

kythe/extractors/openjdk11/extract/extract.go
kythe/extractors/openjdk11/java_wrapper/BUILD
kythe/extractors/openjdk11/java_wrapper/java_wrapper.go

There are a few problematic modules at the moment, specifically: jdk.internal.vm.compiler, jdk.aot, and jdk.internal.vm.compiler.management.  While work is ongoing to fix them, in the meantime it we can start indexing the rest of the modules.

feat: allow excluding modules from openjdk11 extraction

---

kythe/go/platform/vfs/BUILD
kythe/go/platform/vfs/vfs.go
kythe/go/platform/vfs/vfs_test.go

Adds a fairly simple test of the glob-based Walk implementation that compares its result to that of using LocalFS directly.

fix(kzip_merge): add a test that globwalker behaves like filepath.Walk

---

kythe/go/extractors/cmd/bazel/copy_kzip/BUILD
kythe/go/extractors/cmd/bazel/copy_kzip/copy_kzip.go

In order to integrate in-build extracted object with extra-action based pipelines, this extractor just copies a single SpawnAction output to the specified path.

feat(extractors): add a passthrough bazel extractor

---

kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

This should fix https://github.com/bazelbuild/bazel/issues/10802 for us.

fix(java_extractor_test): make error test less picky on required input

---

kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/extractors/golang/golang.go
kythe/go/extractors/govname/govname.go

By default, the go extractor makes source files relative to GOPATH or
the module root if using modules. This change extends the extractor to
use the KYTHE_ROOT_DIRECTORY environment variable instead if it is
provided.
This helps us handle extraction for go code in android better because their code uses multiple go modules, which are extracted separately. The extraction script is [here](https://cs.android.com/android/platform/superproject/+/master:build/soong/build_kzip.bash;l=30), but the golang part is roughly:
`cd build/soong && gotool --rules=./go.vnames.json ./...`
`cd build/blueprint && gotool --rules=./go.vnames.json ./...`
This extracts the `soong` and `blueprint` go modules, each using their own vnames.json mapping file. The `soong` module depends on `blueprint`, so `blueprint` …

feat(go extractor): relativize paths against KYTHE_ROOT_DIRECTORY

---

kythe/go/extractors/config/runextractor/gradlecmd/gradlecmd.go

this is the file name most projects use and is recommended by:
https://guides.gradle.org/creating-new-gradle-builds/

fix(runextractor): set --build_file default to build.gradle

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h

C++ doesn't have a notion of properties, so the edge kinds didn't previously exist; however KytheGraphRecorder is in common C++ code that could be used for other languages whose indexer can be written in C++.

Add property/reads and property/writes edge kinds to KytheGraphRecorder.

---

kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/recursive_type_visitor.h
kythe/cxx/indexer/cxx/recursive_type_visitor_test.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/template/template_dependent_name_ref.cc

Rather than using the current hack for visiting types when the type-as-written differs from the resolved type, factor that logic into a separate visitation hierarchy that visits the type-as-written in parallel with the resolved type.
This is closer to the old logic, but implemented using the same visitation approach as the rest of RecursiveASTVisitor.

fix(cxx_indexer): refactor TypeLoc visitation into separate class

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
kythe/java/com/google/devtools/kythe/extractors/java/bazel/JavaExtractor.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/ForwardingStandardJavaFileManager.java
kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

Trying this again with internally-tested fallbacks for JDK8.

chore(java_extractor): use SOURCE_OUTPUT rather than genSrcDir

---

kythe/web/site/getting-started.md

The recent changes to enable -std=c++17 are not supported in Clang 3.8.

docs: update minimum Clang version to 8

---

kythe/extractors/bazel/Dockerfile

we can't get a new enough clang/libstdc++ using the gcr.io bazel image,
so I switched to debian sid.

fix(bazel-extractor): update docker image for c++17

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD
kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

This should fix cross-module linking for go code extracted through bazel.
Go package dependencies are pulled in as static archives (.a files) and are mentioned in the arguments like:
`-arc "github.com/google/subcommands=github.com/google/subcommands=bazel-out/k8-fastbuild/bin/external/com_github_google_subcommands/linux_amd64_stripped/go_default_library%/github.com/google/subcommands.a="`
This change parses the `-arc` arguments and builds a map of filepath -> importpath, which is then used to attach `GoPackageInfo` details messages to the corresponding required_inputs in the compilation unit. The indexer later picks these up and refers to package dependencies by the correct vname/importpath.

fix(bazel_go_extractor): record canonical importpath for archives

---

kythe/release/package_release.sh

Having tar try to modify the current working directory is rude, don't.  Also fixes https://github.com/kythe/kythe/issues/4430

fix(release): don't include the current working directory in release

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/sun/SunSource.java

I don't believe this is a complete solution, which will involve checking the enclosing class's classfile against file manager locations, but it's a good low-risk initial change.

fix(java_indexer): only apply jdk override for non-source symbols

---

kythe/go/extractors/config/runextractor/cmakecmd/BUILD
kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go

These extra args are passed to runextractor's invocation of cmake.

feat(runextractor cmake): add -extra_cmake_args option

---

.bazelrc
tools/arc/unit/engine/BazelTestEngine.php

This will allow folks (read: me) to optionally have the pre-push tests use the remote configuration without changing the default.

feat(build): have arc run bazel test with named config

---

kythe/web/site/getting-started-macos.md

Install OpenJDK via Homebrew, and document the need to set JAVA_HOME.
Older versions of macOS could also get a "system" Java, but this should work
for any reasonably up-to-date macOS.

docs: update JDK installation notes for macOS

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h

This removes a Location argument which was only used recursively and an `EmitRanges` argument which was either unused or always used with the same value. This allows combining the overloads of `BuildNodeIdForTemplateArgument`

chore(cxx_indexer): remove argument which is unused or invariant

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheVFS.cc

`std::make_pair` is at best redundant and almost always just results in an extra copy.

chore: remove use of std::make_pair

---

kythe/typescript/indexer.ts
package-lock.json
package.json

TypeScript 3.8 updated the AST so that a `ts.ExportDeclaration` can now either have a `NamedExports` or `NamespaceExport` as child ([example](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAKjgQwM5wHboGZQgWzgHIsiBuAKFEljgG8BfOXA40soA)). This PR updates the current exports handing to only traverse into named exports and leave namespace exports alone. This is only meant to unblock building and running Kythe with TypeScript 3.8 and it's API's.

Support TypeScript 3.8 AST

---

kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/clang_range_finder.cc
kythe/cxx/indexer/cxx/clang_range_finder.h
kythe/cxx/indexer/cxx/clang_range_finder_test.cc
kythe/cxx/indexer/cxx/clang_utils_test.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/basic/new_operator.cc
kythe/cxx/indexer/cxx/testdata/function/function_operator_overload_names.cc

I'm 95% certain that all of the current uses of `getLocWithOffset()` come down to a confusion between character and token oriented ranges and can be cleaned up.  This PR is somewhat cleanup and somewhat proof-of-concept for writing unittests of specific behavior in the indexer, rather than relying on verifier tests to accomplish everything.  Verifier tests are great at saying when something fails, but can be challenging to use to determine *why* something failed.

chore(cxx_indexer): centralize and unittest some range handling

---

.ycm_extra_conf.py
tools/cpp/generate_compilation_database.sh

Rather than re-generating compile_commands.json all in one go, use `--compile_one_dependency` to insert new entries and reformat.

chore: generate partial compile_commands.json

---

kythe/web/site/getting-started.md
tools/build_rules/lexyacc/lexyacc.bzl

Fixes #4455 (by requiring a version of flex that omits the `register` keyword).

fix: require flex version 2.6 or newer

---

kythe/web/site/getting-started-macos.md
tools/build_rules/lexyacc/lexyacc.bzl

This is a follow-up to #4455 and #4456. Because macOS ships with flex 2.5 and
homebrew will not link it to avoid confusing the system build tools, this
change also adds a FLEX environment variable to allow it to be overridden
without diddling the user's PATH.

docs: install flex via Homebrew for macOS

---

external.bzl
kythe/cxx/extractor/BUILD
kythe/cxx/extractor/bazel_artifact_reader.cc
kythe/cxx/extractor/bazel_artifact_reader.h
kythe/cxx/extractor/bazel_artifact_reader_test.cc
kythe/cxx/extractor/bazel_event_reader.cc
kythe/cxx/extractor/bazel_event_reader.h
kythe/cxx/extractor/bazel_event_reader_test.cc
kythe/cxx/extractor/dump_bazel_artifacts.cc
tools/build_rules/build_event_stream/BUILD
tools/build_rules/build_event_stream/repo.bzl

In the short term, this paves the way for Bazel extraction using the build event stream, rather than groveling around in `bazel-out` for .kzip files.  In the medium term it will allow for aspect-based extraction (via output_group).

feat: add lib for reading artifacts from bazel event streams

---

kythe/docs/schema/schema.txt

Given that this found a bug in the inline test as well, I'm confident this will address the problem with `ref/id` missing from the TOC.

chore: normalize and fix schema formatting

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc
kythe/cxx/indexer/cxx/testdata/rec/rec_designated_initializer.c

This matches the Go behavior and that documented in the schema.  Prior to this, we would only emit ref/init for the designated initializer case, which is less useful because we also emit a regular ref from the field name in the designated initializer itself.
This PR cuts out a redundant traversal and emits a ref/init edge to all fields initialized from a given initializer list, excluding those without an explicit initializing expression.

fix(cxx_indexer): properly emit ref/init edges in all cases

---

kythe/cxx/common/BUILD
kythe/cxx/common/path_utils.cc
kythe/cxx/common/path_utils.h

If this is insufficient, I can try implementing realpath directly to cache intermediate symbolic links and further cut down on the redundant work, but for now just use a direct cache.

feat(cxx_extractor): cache symlink resolution in PathRealizer

---

kythe/cxx/extractor/cxx_extractor.cc

This quiets and otherwise harmless error from failing to resolve the paths.

chore(cxx_extractor): don't attempt to relativize builtin paths

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Files.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Jvm.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java

Experiment with emitting edges into the JVM graph for both definitions
and references when --emit_jvm=SEMANTIC.  This allows post-processing to
decide whether to use the language-specific nodes or general JVM nodes
for cross-references.

feat(java_indexer): experimentally emit named edges to JVM nodes

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/testdata/rec/rec_agg_init.cc

This would've been much easier if Clang consistently gave imaginary expressions invalid locations, but nooooo.

fix(cxx_indexer): don't emit ref/init for unspecified fields

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/JvmCrossFile.java

This functionality is superseded by #4505.

deprecation(java_indexer): remove --emit_jvm_references feature

---

kythe/cxx/indexer/proto/BUILD

Bazel will start supporting layering check in the next version and then
this package will start failing
(https://github.com/bazelbuild/bazel/issues/11501). This PR removes
enabled  freatures from this packages until the violations are fixed.

Remove layering_check and parse_headers from cxx/intexer/proto package

---

kythe/go/extractors/config/runextractor/compdb/compdb.go

I dropped the `ErrGroup` in favor of a `WaitGroup`, so we continue processing other compilations even if one fails. A counter tracks how many failed and is returned in the error message at the end.
Fixes #4534

feat(compdb): continue processing other compilations on error

---

kythe/go/platform/tools/kzip/metadatacmd/BUILD
kythe/go/platform/tools/kzip/metadatacmd/test.sh

It's much easier to get this test running in google3 without the jq dependency.

fix(build): remove jq dependency

---

kythe/go/platform/tools/kzip/metadatacmd/test.sh

In google3, only the TEST_TMPDIR is writable from the test.

test(kzip metadata): save test kzip to $TEST_TMPDIR

---

kythe/cxx/extractor/BUILD
kythe/cxx/extractor/cxx_extractor_bazel_main.cc

CppCompile actions (created by cc_* rules or Starlark rules using
cc_common.compile) can accept a variety of types of files in srcs,
including assembly (".s" or ".asm"). However, those source files
don't actually result in compiler jobs, so there's nothing to
extract. Attempting to run the extractor on e.g. cc_* targets
with only ".s" srcs results in an error like:
error: unable to handle compilation, expected exactly one compiler job in ''
Instead, the extractor should write an empty output in those cases and
exit, since there are no C/C++ cross-references to extract from those
sources.

Don't attempt to extract compilation from assembly

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h
kythe/cxx/indexer/cxx/clang_utils.cc
kythe/cxx/indexer/cxx/clang_utils.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_var_ref_blame.cc
kythe/cxx/indexer/cxx/testdata/df/df_var_rw.cc
kythe/cxx/indexer/cxx/testdata/objc/categories/extension_property.m
kythe/cxx/indexer/cxx/testdata/objc/ivar_decl.m
kythe/cxx/indexer/cxx/testdata/objc/property_decl_defn_synth.m
kythe/cxx/indexer/cxx/testdata/rec/rec_class_member_ptr.cc

This PR marks a subset of ref edges known to be writes (currently using the primitive operator = with vars or ivars on the lhs) as `ref/writes` (or `ref/writes/implicit`).

feat(cxx_indexer): annotate edges we know are writes to vars and ivars

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h
kythe/cxx/indexer/cxx/indexer_worklist.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_var_influence.cc
kythe/docs/schema/schema.txt

This PR introduces the `influences` relation on variables, which
is meant as a primitive (and still experimental) way to track
dataflow in the semantic graph. Influence is currently limited
only to the primitive assignment operator =.

feat(cxx_indexer): record var-to-var influence

---

kythe/typescript/indexer.ts
kythe/typescript/kythe.ts
kythe/typescript/testdata/jsdoc.ts

While reading the [TS 4.0 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/),
I realized that the TS indexer currently doesn't tag entities that are
marked as deprecated. There's a formal API for this in TS 4.0, but we
accurately determine whether a node is deprecated (and why) by scanning
the JSDoc tags of that node.

Support deprecated tags in TS marked source

---

kythe/cxx/common/json_proto.cc
kythe/cxx/common/json_proto.h

Modernizing the API by replacing `const char *` parameter type with `string_view`.

Convert PackAny's parameter to absl::string_view.

---

kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
kythe/cxx/indexer/cxx/testdata/libraries/proto_parsetextproto.cc

Specifically, support calling ParseTextProtoOrDie (in a variety of flavors) directly rather than via the macro.

fix(cxx_indexer): increase flexibility of proto library plugin

---

.arclint
kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/extractor/tests/integration_test.rs
kythe/rust/indexer/src/providers.rs

This PR fixes a bug in the Rust extractor where a top-level folder was not being created in the kzips, causing them to be invalid. The extractor will now create a top-level folder named "root". The indexer has been fixed to properly detect the root folder name. 
This PR adds an exclusion for `kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java` from the arcanist spellchecker. This prevents the linter from failing due to a false-positive.

fix(rust): Ensure that Rust extractor creates a top-level folder

---

.bazelrc

--experimental_allow_incremental_repository_updates has been deleted in https://github.com/bazelbuild/bazel/commit/fdf10c34c82c563fb7fc7f262de32e1f7af59e2d

Remove deprecated flag from bazelrc

---

kythe/cxx/indexer/proto/indexer_frontend.cc
kythe/cxx/indexer/proto/proto_analyzer.cc
kythe/cxx/indexer/proto/proto_analyzer.h

The FileVNameGenerator only produces useful VName lookups if given a
vname config file or if other defaults are set. In this case it was just
being used empty.
Because the proto indexer only needs file vnames for .proto files and
these all have vnames specified in the compilation unit, there isn't
need for other configuration.
In the case that a proto is referenced, but not in the compilation unit,
an empty vname would be used. This shouldn't happen though because the
proto parser itself would fail and the indexing code wouldn't get run.
We could consider changing the lookup functions to return a StatusOr to
handle that case better.

chore(proto_indexer): remove unused FileVNameGenerator

---

kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/marked_source.cc

For some reason, in recent versions of Clang, integer template arguments (when fed into Sema as we do in MarkedSource) reach an assert that fails. To avoid tripping the assert, this PR stops trying to infer information about default template arguments if it encounters an integer template argument.
This PR also disables diagnostics while inferring which arguments are defaults. Previously, the indexer would report spurious diagnostics that were raised during inference.

fix(cxx_indexer): avoid an assert check in Clang, silence errors

---

kythe/release/BUILD

Adds the Fuchsia Rust extractor binary to the regular Kythe release.
This allows us (Fuchsia engs) to just grab a new Kythe binary release
and reuse in Fuchsia buildbots.
Issue: 4606

feat(rust): Adds Fuchsia Rust extractor to release

---

kythe/java/com/google/devtools/kythe/extractors/java/SystemExploder.java
kythe/java/com/google/devtools/kythe/platform/java/filemanager/CompilationUnitPathFileManager.java

Stream::iterator is an unsafe way to create an Iterable, and will soon be banned by an ErrorProne check.

Replace `stream::iterator` with alternatives in enhanced for loops.

---

kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/indexer/testdata/struct.rs

This PR fixes the following bugs:
- Previously, the Rust extractor didn't emit an explicit root directory. This meant that the kzips produced by the extractor were incompatible with the `kzip` tool. This has been fixed.
- The struct verifier test for the indexer was missing a main function and not working properly. The main function has now been added.

fix(rust): Fix small bugs in the Rust implementation

---

kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/testdata/modules/test.rs
kythe/rust/indexer/testdata/struct.rs
kythe/rust/indexer/testdata/trait.rs

This PR fixes the following bugs in the Rust indexer:
- Fixes some of the verifier tests to prevent compiler warnings
- Removes the functionality associated with emitting `overrides` edges with Traits. Overrides are not part of the Rust language, and there were bugs associated with standard library Traits not having their definitions known while indexing.

fix(rust): Fix Rust indexer issue with Trait definitions

---

kythe/rust/extractor/src/bin/extractor.rs

Use write_all instead of write; otherwise, file content may be truncated unexpectedly.

fix(rust): write_all instead of write in the extractor

---

kythe/rust/fuchsia_extractor/src/bin/main.rs
kythe/rust/indexer/BUILD
kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/testdata/xrefs/log.rs
kythe/rust/indexer/testdata/xrefs/main.rs
tools/rust/extra_action/src/main.rs

This PR does the following:
- Runs rustfmt on the Rust code
- Removes the path field from the VName of emitted definitions nodes
- Removes emitting definitions that are in files we didn't emit file nodes for
- Makes verifier test for xrefs more complex

fix(rust): Fix definition anchors and xrefs in the indexer

---

kythe/rust/fuchsia_extractor/BUILD
kythe/rust/fuchsia_extractor/src/bin/main.rs

The old code filled FileInfo.path with a path relative to the corpus
root, but should instead have filled it with a path relative to the
build directory.
Added a regression tests, and added *most* of an integration test
which runs kzip info... for additional verification of adherence
to the spec.
Howeer, that last test is currently not enabled as it is apparently
not allowed to subprocess to a binary.

fix(rust): Fixes the kzip generation

---

kythe/rust/cargo/BUILD
kythe/rust/cargo/Cargo.toml
kythe/rust/cargo/crates.bzl
kythe/rust/cargo/remote/cloudabi-0.0.3.BUILD
kythe/rust/cargo/remote/lock_api-0.3.4.BUILD
kythe/rust/cargo/remote/parking_lot-0.10.2.BUILD
kythe/rust/cargo/remote/parking_lot_core-0.7.2.BUILD
kythe/rust/cargo/remote/redox_syscall-0.1.57.BUILD
kythe/rust/cargo/remote/scopeguard-1.1.0.BUILD
kythe/rust/cargo/remote/serial_test-0.4.0.BUILD
kythe/rust/cargo/remote/serial_test_derive-0.4.0.BUILD
kythe/rust/cargo/remote/smallvec-1.4.2.BUILD
kythe/rust/cargo/remote/syn-1.0.36.BUILD
kythe/rust/fuchsia_extractor/BUILD
kythe/rust/fuchsia_extractor/src/bin/main.rs
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/gen/third_party/rust_crates/vendor/nom/dir/file.rs
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/gen/third_party/rust_crates/vendor/nom/dummy
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/gen/third_party/rust_crates/vendor/nom/lib.rs
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/save-analysis-temp/nom.json
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/liblazy_static-cdf593bd3fb3d68f.rlib
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/libmemchr-523a962cdfbcb111.rlib
kythe/rust/fuchsia_extractor/testdata/test_dir_2/compilation-root/out/terminal.x64/x64-shared/obj/third_party/rust_crates/libregex-be3eec66bf66867d.rlib

Adds sorting code that bins all the Fuchsia source
files into separate roots, based on the relative
path of a file with respect to the directory the
root builds in.
There are about a dozen different roots, some of which
are "" (the "default" source, which is the "in-tree" code),
the "gen" (source code generated by build rules), "fidling_gen"
(the source code generated by the FIDL compiler) and so on.
Regression test added to confirm that the paths are set as
expected.

fix(rust): Handles different roots for Fuchsia

---

kythe/rust/cargo/BUILD
kythe/rust/cargo/Cargo.toml
kythe/rust/cargo/crates.bzl
kythe/rust/cargo/remote/crossbeam-deque-0.7.3.BUILD
kythe/rust/cargo/remote/crossbeam-epoch-0.8.2.BUILD
kythe/rust/cargo/remote/crossbeam-queue-0.2.3.BUILD
kythe/rust/cargo/remote/crossbeam-utils-0.7.2.BUILD
kythe/rust/cargo/remote/maybe-uninit-2.0.0.BUILD
kythe/rust/cargo/remote/memoffset-0.5.5.BUILD
kythe/rust/cargo/remote/num_cpus-1.13.0.BUILD
kythe/rust/cargo/remote/rayon-1.3.1.BUILD
kythe/rust/cargo/remote/rayon-core-1.7.1.BUILD
kythe/rust/fuchsia_extractor/BUILD
kythe/rust/fuchsia_extractor/src/bin/main.rs

The Fuchsia compilation extraction is easy to parallelize, so
we do so.  The rayon library farms out the extraction process,
and the extraction workers won't interfere with each other as
they only read inputs, and are guaranteed not to step over
each other.
This should speed up the extraction significantly.

fix(rust): parallelize the extraction process

---

kythe/cxx/indexer/textproto/BUILD
kythe/cxx/indexer/textproto/plugin_registry.cc
kythe/cxx/indexer/textproto/plugin_registry.h
kythe/cxx/indexer/textproto/textproto_indexer_main.cc

this will allow for easily swapping to a different loader in google3

feat(textproto): move plugin loader to a library

---

kythe/go/extractors/config/runextractor/cmakecmd/cmakecmd.go
kythe/go/extractors/config/runextractor/compdb/compdb.go
kythe/go/extractors/config/runextractor/compdb/compdb_test.go
kythe/go/extractors/config/runextractor/compdbcmd/compdbcmd.go

Adds the ability to pass arbitrary additional flags to the
extractor binary ran by `runextractor`.  This allows for example
specifying custom include library paths for `cxx_extractor`, which
allows the extractor access to include library paths for a custom
compiler if used.
Example:
```bash
runextractor compdb -extractor cxx_extractor -- -cxx-isystem=../some/dir
```

feat(runextractor): Pass flags to the compdb extractor

---

kythe/rust/fuchsia_extractor/src/bin/main.rs

This test was passing with `--config=remote` and failing locally.  Sort `required_input` so positions are more deterministic.

fix(fuschia_extractor_test): sort required_inputs

---

.bazelrc

This flag seems to invalidate the build graph cache and causes bazel to re-fetch and re-analyze a lot of dependencies when switching between `bazel query` and `bazel build`.
I frequently use `ibazel` and this change makes the experience *significantly* better as it often runs bazel queries.

fix(bazel): align options between `query` and `build`

---

kythe/cxx/common/init.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/clang_utils.cc
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_field_ref_blame.cc

This PR pulls out blame assignment into a separate function.
It also fixes init.cc on macOSx (and presumably other platforms
that fail to define __THROW).

feat(cxx_indexer): add blame scopes for field references

---

kythe/go/util/kytheuri/uri_test.go
kythe/java/com/google/devtools/kythe/util/KytheURI.java
kythe/javatests/com/google/devtools/kythe/util/KytheURITest.java

This makes the Java KytheURI implementation match the canonical Go implementation.

fix(java_common): keep rooted URI paths rooted

---

kythe/cxx/extractor/textproto/testdata/custom_corpus.UNIT
kythe/cxx/extractor/textproto/testdata/extra_imports.UNIT
kythe/cxx/extractor/textproto/testdata/extra_imports.pbtxt
kythe/cxx/extractor/textproto/testdata/simple.UNIT
kythe/cxx/extractor/textproto/testdata/simple.pbtxt

this makes import into google easier because if the path in the .pbtxt needs to be updated at import, the digest in the .UNIT golden file needs to be recomputed

fix(textproto tests): use relative path in `proto-file` schema comment

---

kythe/cxx/indexer/textproto/BUILD
kythe/cxx/indexer/textproto/plugin_registry.cc
kythe/cxx/indexer/textproto/plugins/example/testdata/BUILD
kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl

This also adds an `indexer_opts` param to textproto_verifier_test, so
tests can enable specific plugins.

feat(textproto): put example plugin behind a flag

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_fncall_influence.cc
kythe/cxx/indexer/cxx/testdata/df/df_fncall_influence_defaultargs.cc
kythe/cxx/indexer/cxx/testdata/df/df_fncall_influence_pack.cc
kythe/cxx/indexer/cxx/testdata/df/df_fncall_influence_vararg.cc

This PR adds influence edges for function calls. In particular:
* argument expressions influence parameter variables
* parameter variables on incomplete functions influence the
parameter variables on functions that complete them
* return expressions influence their containing (complete)
functions
* a function call results in that function being included
in the current influence set.
It should not be necessary to make complete functions influence
the functions they complete as they are already related through
clustering. Parameters on incomplete definitions are not clustered
with the corresponding parameters on complete definitions.
Note: it may be necessary to implement the new traverse functions
using data recursion should we start running out of stack. I have not
observed this behavior …

feat(cxx_indexer): trace influence through function calls

---

kythe/javatests/com/google/devtools/kythe/doc/BUILD

This gives the testdata files the same visiblity as the other targets in this package.

chore: Make filegroup for testdata

---

WORKSPACE
external.bzl

This allows other bazel projects to depend on kythe without adding the `npm_install` to their own WORKSPACE

chore(build): move npm_install to external.bzl

---

kythe/typescript/README.md
kythe/typescript/indexer.ts
kythe/typescript/testdata/function.ts
kythe/typescript/testdata/object.ts

From developer point of view computed properties themselves don't
represent a separate entity that you can click. Instead they are
just expressions and identifiers in that expression should be
xrefed.
Current behavior (which is being fixed in this commit) is the
following:
```typescript
const k = {
[foo]: 123,
};
```
Currently `[foo]` considered a definition and it overlaps `foo`
making it impossible to click on `foo`.
Tested:
unit tests

fix(typescript_indexer): don't emit defines/binding for computed properties

---

kythe/cxx/indexer/textproto/analyzer.cc
kythe/cxx/indexer/textproto/plugin.h

plugins can use this to lookup proto descriptors based on qualified names

feat(textproto): expose DescriptorPool in plugin api

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaNode.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/java/TreeContext.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Classes.java

This matches the C++ indexer's existing behavior and better represents the actual callgraph.
The cinit function is newly represented in this commit as a bare function node per class.

fix(java_indexer): blame instance/static callsites on ctor/cinit methods

---

kythe/data/vnames.bzl

`\]` and `\[` are invalid escape sequences in Starlark. This used to be silently ignored but now throws an error (see https://github.com/bazelbuild/bazel/commit/73402fa4aa5b9de46c9a4042b75e6fb332ad4a7f).

Fix invalid escape sequences

---

kythe/go/indexer/testdata/code/methdecl.go

This doesn't change any functionality but records the current behavior
for marked source for go methods.

chore(go_indexer): Add a marked source test for methods

---

autotools.bzl
external.bzl
kythe/cxx/verifier/BUILD
kythe/cxx/verifier/souffle_entrysteam_support.cc
third_party/souffle.BUILD
third_party/souffle_remove_config.patch

This PR builds a version of the souffle frontend that can read an
entrystream directly. For example, the program
```
.type vname = [
signature:symbol,
corpus:symbol,
path:symbol,
root:symbol,
language:symbol
]
.decl entry(source:vname, kind:symbol, target:vname, value:symbol)
.input entry(IO=kythe_entrystream)
.decl outentry(source:vname, kind:symbol, target:vname, value:symbol)
.output outentry(IO=json)
outentry(s,k,t,v) :- entry(s,k,t,v).
```
when invoked as
```
./bazel-bin/kythe/cxx/verifier/souffle_with_kythe example.dl \
< in.entries
```
will print the entries as JSON.
libffi still doesn't work on Darwin and the fix isn't immediately
clear (I did look at a different BUILD file, but I think their
version of libffi was different; ours seems to be missing some
Darwin headers for …

feat(verifier): build a souffle frontend that can read an entrystream

---

kythe/cxx/indexer/textproto/BUILD
kythe/cxx/indexer/textproto/analyzer.cc
kythe/cxx/indexer/textproto/analyzer.h

Some portions of google3 contain so many textproto build targets that it is causing performance problems for blaze. Stuffing multiple textprotos in a single compilation unit will allow us to reduce the number of build targets.

feat(textproto): allow compilation units to contain multiple sources

---

external.bzl
setup.bzl

This will allow Kythe to work with Bazel 4.0.

Update to rules_go 0.25.0.

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/indexed_parent_iterator.h
kythe/cxx/indexer/cxx/indexed_parent_map.cc
kythe/cxx/indexer/cxx/indexed_parent_map.h

This mirrors and automated internal cleanup.

chore(cxx_indexer): remove obsolete clang nested namespace

---

kythe/cxx/extractor/bazel_artifact_selector.cc
kythe/cxx/extractor/bazel_artifact_selector.h
kythe/cxx/extractor/bazel_artifact_selector_test.cc

The resulting design is predicated on a couple of things:
1) protos may be arena allocated, which makes output parameters preferred
2) RepeatedPtrField is awkward to work with, suggesting an overload to better accommodate it.
3) Overloads and virtual member functions don't play well.
4) So update the deserialization protocol to operate on a single Any, with non-virtual members which make use of that.
I've also included tests of the serialization/deserialization both generically and for AspectArtifactSelector.  The remaining changes are due to updates in clang-format.

fix(cxx_common): change selector serialization to work better with protos

---

kythe/cxx/common/regex.cc
kythe/cxx/common/regex.h

There are a wide variety of data structures from which we might want to Build a RegexSet and not all of them will fit into a `Span<const std::string>`.  So template Build on a range-of-string-like things to allow more flexible construction.

feat(cxx_common): allow any range-of-string-like-types for RegexSet::Build

---

.bazelrc

Without this change, when you do a build from a sub-directory, it won't be able
to find the javacopts bazelrc file.

chore: make bazelrc import rooted

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/semantic_hash.cc

Omit the `default` case for some switches which should be exhaustive, add `case` statements for the missing enumerators.  Remove `LOG(FATAL)` in favor of `CHECK(IgnoreUnimplemented)` where appropriate.

fix(cxx_indexer): add missing cases and remove default from clang enum switches

---

kythe/web/site/getting-started-macos.md

Rather than give users manual installation and upgrade instructions for Bazel,
use the Bazelisk command-line tool, which knows how to use the metadata in
the repository to pick the correct version and to download/install it.

docs: update macOS installation instructions for Bazel

---

external.bzl

Something in the next commit
(https://github.com/abseil/abseil-cpp/commit/c9894d1dc38577c4ce50eefe0a944ea8d46d7fc5)
is breaking the build (on my darwin machine).

chore: update absl to the last version that works on darwin

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_field_influence.cc

Fields appear under MemberExprs, which take care of both
direct (.) and indirect (->) access.

feat(cxx_indexer): add fields to the influence graph

---

kythe/java/com/google/devtools/kythe/extractors/java/UsageAsInputReportingFileManager.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac8Wrapper.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Javac9Wrapper.java
kythe/java/com/google/devtools/kythe/extractors/shared/IndexInfoUtils.java
kythe/java/com/google/devtools/kythe/platform/kzip/KZipWriter.java

via the KYTHE_JAVA_SOURCE_BATCH_SIZE environment variable.
From my limited testing, this appears to work and yields indexable compilation units.

feat(java_extractor): allow specifying java sources batch size for extractor

---

kythe/go/extractors/cmd/gotool/Dockerfile

Repos are starting to need newer version of go than come standard in our base image, so manually install go 1.15

chore: Use go 1.15 in our go extract docker image

---

kythe/go/extractors/cmd/gotool/analyze_packages.sh

This fixes 2 issues in the script:
- Use $GOPATH instead of the hard-coded /workspace directory.
This makes the script be more agnostic to how the script is being ran
(e.g. assuming where go get puts the underlying source).
- Use PACKAGES[0] instead of PACKAGES[1]. Since the script args are
shifted, package params specified by the user start at 0, not 1.

go extractor: Fix package directory resolution.

---

kythe/go/extractors/cmd/gotool/Dockerfile

Remove any existing go installs before installing our recent go release to avoid multiple version problems.

chore: clean up go docker image

---

kythe/docs/schema/schema.txt

While implied elsewhere, the lack of this field on file nodes causes some confusion.  Make it explicit in the documentation.
Note that the current use of anchors when constructing `imputes` edges strongly suggests that we should either fully specify the expected signature as well or use a distinct language for that case.

docs: include specific note that anchors should include a language

---

kythe/cxx/verifier/verifier.cc
kythe/cxx/verifier/verifier.h
kythe/cxx/verifier/verifier_main.cc

The existing solver depends on sorting input facts for various
reasons. As it turns out, these sorting phases take a significant
amount of the runtime of a single verification test. This PR adds
a flag (meant to eventually invoke the fast solver) that removes
the sorting phases while preserving some invariants.
In greater detail, there are two phases. In the first, the verifier
identifies anchor nodes (for an optimization that turns anchors into
a different internal data type) and file nodes (as we support reading
goals from file nodes). Sorting is necessary to group entries
according to VName (and to provide other guarantees, like the ordering
of well-known facts) that makes this process easy to encode as a
state machine. While we no longer need the optimization, we still
need to …

feat(verifier): don't spend time sorting input for the fast solver

---

kythe/cxx/indexer/proto/file_descriptor_walker.cc
kythe/cxx/indexer/proto/testdata/basic/extend.proto
kythe/cxx/indexer/proto/testdata/basic/nested-message-field.proto
kythe/cxx/indexer/proto/testdata/corner_cases/import_syntax.proto
kythe/cxx/indexer/proto/testdata/corner_cases/tabs.proto

Some UIs have problems decorating the multi-line spans which can result from taking the type locations directly from the proto compiler.  Split qualified names and only decorate the final unscoped type name.  This also matches the behavior from most other languages.

fix(proto): only decorate the relative type name in fields

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

The Go compiler produces these as well as .a archive files and they contain the minimal interface information necessary for dependencies.  I'm not entirely sure of the details (and searching for information on ".x" is predictably unfruitful), but they cause issues with xrefs when omitted.

fix(bazel_go_extractor): include .x files in required input

---

kythe/data/vnames.go.json
kythe/data/vnames_test.go.json

Update the generic Go vnames.json to strip both .a and .x suffixes

fix(go_vnames): properly map .x file vnames

---

kythe/data/simple_vnames.json
kythe/data/vnames.go.json
kythe/data/vnames_test.go.json

The bazel Go rules no longer create the same symlink forest they used to and instead stick to the standard Bazel file structure.  Update the vnames.go.json and corresponding tests to account for this.  Also add a special case for .x and .a files to the "simplified" vnames.json so that Go archives map to the same node.

fix(go_vnames): add go vname archives to simple_vnames.json

---

external.bzl
kythe/cxx/common/BUILD
kythe/cxx/common/file_vname_generator.cc
kythe/cxx/common/file_vname_generator.h
kythe/cxx/common/file_vname_generator_test.cc
kythe/cxx/extractor/proto/BUILD
kythe/cxx/indexer/proto/BUILD
kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
kythe/javatests/com/google/devtools/kythe/extractors/shared/FileVNamesTest.java

Allow the use of named captures and replacements in vnames.json.  Go already had this, but the 3 languages should be consistent.

feat(common): allow named captures in vnames.json rules

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/analyzers/java/TreeContext.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Modifiers.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Visibility.java

Adds support for 
* visibility = {public, private, package, protected}
Also adds support for
* tag/volatile
* tag/abstract
* tag/default

feat(java): emit visibility and other modifier facts

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Callgraph.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/GenericMethodRef.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Methods.java

Users expect that the primary linkages in the statement
`new Foo<Bar>(z)`
will be to the constructor of `Foo`, the definition of class `Bar`, and the definition/declaration of variable `z`. Existing behavior is to set the span for the constructor reference to be `new Foo`. This turns out to require a lot of special casing in resolving all the overlapping references in such a way that users expect. If we remove `new ` from that span, a relatively simple straightforward approach of choosing "smallest" spans, accompanied with a prioritization of `ref/call` edges, yields satisfactory results.
It can be (has been?) argued that `new ` is *part* of the constructor name, on the basis that Java method references use the word "new", e.g. in `String::new`. However, the constructor is declared with …

Do not include "new " in java constructor refs

---

third_party/libffi.BUILD

I'm not clear why a `configure` in a checkout of libffi finds `ar` properly but running `configure` inside bazel ends up choosing `libtool`, but a blunt hammer seems to work on linux as wel.

fix: force selection of `ar` to unbreak os x build of libffi

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/clang_utils.cc
kythe/cxx/indexer/cxx/clang_utils.h
kythe/cxx/indexer/cxx/testdata/BUILD

Tag particular AST nodes as writes. This is cleaner than the previous
approach, which tries to scramble up the tree to figure out if a node
is in a write context. This PR also unifies lvalue interpretation
and influence target identification.
We can probably turn dataflow edges on by default, but that will be
a separate PR.

fix(cxx_indexer): refactor lvalue handling for dataflow

---

kythe/typescript/languageserver/vscode-extension/package-lock.json
kythe/typescript/languageserver/vscode-extension/package.json

This was done by running `npm audit fix --force`.  The result doesn't build with `npm run compile` but it *also* didn't build for me before running this.  As this integrated with Bazel and doesn't have standalone tests I can't tell if this is a regression or not, but dependabot is insisting on updating each vulnerability one-at-a-time and with each CI run taking at least ten minutes, I'll be stuck here all week approving them at that pace.

fix(vscode): update vscode dependencies

---

kythe/java/com/google/devtools/kythe/analyzers/indexer.bazelproject

Bazel's `*.bazel.io` domains are deprecated and redirect to their `*.bazel.build` equivalents.
I'm cleaning up references that I come across so that we can eventually retire the *.io subdomains completely.

Replace ij.bazel.io reference with ij.bazel.build.

---

kythe/rust/fuchsia_extractor/src/bin/main.rs

Small change to fix a warning about `panic!` supporting format strings natively in Rust 2021
```
INFO: From Compiling Rust bin fuchsia_extractor_test (1 files):
warning: panic message is not a string literal
--> kythe/rust/fuchsia_extractor/src/bin/main.rs:962:16
|
962 |           panic!(format!(
|  ________________^
963 | |             "pbunits file not found in existing zip file: zip_path: {:?}",
964 | |             &zip_path.as_ref(),
965 | |         ));
| |_________^
|
= note: `#[warn(non_fmt_panic)]` on by default
= note: this is no longer accepted in Rust 2021
= note: the panic!() macro supports formatting, so there's no need for the format!() macro here
```

fix(fuschia-extractor): Fix panic format string for Rust 2021

---

kythe/go/indexer/BUILD
kythe/go/indexer/cmd/go_example/go_example.go
kythe/go/indexer/cmd/go_indexer/go_indexer.go
kythe/go/indexer/emit.go
kythe/go/indexer/testdata/basic/tappcorpus.go
kythe/go/indexer/testdata/go_indexer_test.bzl

this is essentially the same as the c++ indexer's
--use_compilation_corpus_as_default option, which assigns the
compilation unit's corpus to template instantiations, etc.

feat(go_indexer): add option to put tapp nodes in the CU corpus

---

kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/DefaultCorpus.java

this is intended to match the behavior of the `--use_compilation_corpus_as_default` option in the c++ and go indexers
followup changes will apply this same logic to other types of corpus-less nodes

feat(java_indexer): add option to put tapps in the CU corpus

---

kythe/release/cloudbuild/presubmit.yaml

Under the hypothesis that increasing versions is more likely to share cache as is keeping a consistent version in sequence, where possible.

chore: reorder GCB steps in presubmit

---

kythe/web/site/BUILD
kythe/web/site/serve.sh

This allows testing changes before deployment via: `bazel run //kythe/web/site:serve`

feat(site): add a target for serving website locally

---

external.bzl
setup.bzl

The primary purpose here is to switch to using the in-tree Bazel targets rather than the external overlay.

chore: update LLVM

---

kythe/rust/extractor/src/bin/cli.rs
kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/extractor/src/bin/save_analysis.rs
kythe/rust/extractor/src/lib.rs
kythe/rust/extractor/tests/integration_test.rs
kythe/rust/extractor/tests/test.rs
kythe/rust/fuchsia_extractor/src/bin/main.rs
kythe/rust/fuchsia_extractor/src/kzip.rs
kythe/rust/indexer/src/bin/bazel/main.rs
kythe/rust/indexer/src/bin/proxy/main.rs
kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/src/indexer/entries.rs
kythe/rust/indexer/src/indexer/mod.rs
kythe/rust/indexer/src/indexer/offset.rs
kythe/rust/indexer/src/indexer/save_analysis.rs
kythe/rust/indexer/src/providers.rs
kythe/rust/indexer/src/writer.rs
kythe/rust/indexer/tests/array_writer.rs
kythe/rust/indexer/tests/providers.rs
tools/rust/rustfmt.sh

Runs `tools/rust/rustfmt.sh` to format all the Rust files. A future PR will add formatting checks to the pre-submit.

chore(rust_common): format all Rust files

---

kythe/go/extractors/config/runextractor/compdb/BUILD
kythe/go/extractors/config/runextractor/compdb/compdb.go
kythe/go/extractors/config/runextractor/compdb/compdb_test.go
kythe/go/extractors/config/runextractor/compdb/testdata/compilation_database_arguments.json

[some](https://github.com/rizsotto/Bear) tools generate "arguments" instead of "command",
both are valid according to https://clang.llvm.org/docs/JSONCompilationDatabase.html

feat(extraction): accept "arguments" in addition to "command" in compdb

---

kythe/rust/extractor/BUILD
kythe/rust/indexer/BUILD

PROTO_COMPILE_DEPS is unneeded and over-complicates BUILD files

fix(rust_common): remove references to PROTO_COMPILE_DEPS

---

kythe/rust/extractor/tests/test.rs

Previously, the test for the Rust extractor would succeed inside Bazel, but would fail in other environments

fix(rust_extractor): fix --out-dir path in test

---

kythe/extractors/BUILD
kythe/rust/extractor/src/bin/save_analysis.rs
kythe/rust/extractor/tests/integration_test.rs
tools/rust/extra_action/src/main.rs

Fixes a bug in the Rust extractor caused by changes in the arguments passed to the rules_rust `process_wrapper` binary

fix(rust_extractor): change argument processing due to rules_rust change

---

kythe/proto/generate_protobufs.py

Convert Bazel output to a string rather than bytes, so that string operations
in Python 3 will work correctly. This change assumes the output is UTF-8, which
should be safe in the Kythe repository.

proto: update generator script to support Python3

---

kythe/go/platform/kzip/info/info.go

this is an exception to the "no absolute paths" rule

fix(kzip info): allow paths that begin with /kythe_builtins/

---

kythe/rust/indexer/BUILD
kythe/rust/indexer/src/bin/proxy/main.rs
kythe/rust/indexer/src/error.rs
kythe/rust/indexer/src/lib.rs
kythe/rust/indexer/src/providers.rs
kythe/rust/indexer/src/proxyrequests.rs
kythe/rust/indexer/src/writer.rs

Previously we constructed the proxystub commands with format strings, which could lead to issues if there were stray quotation marks. With this PR we let serde_json handle the JSON serialization for us.

fix(rust_indexer): serialize proxy communication with serde_json

---

kythe/rust/extractor/src/bin/extractor.rs

Currently, attempting to extract targets with hyphens will fail because the extractor will assume the wrong path for the save_analysis file. This PR fixes that case.

fix(rust_extractor): fix path for targets with hyphens

---

kythe/go/platform/kcd/kcd.go
kythe/go/platform/kcd/locked/locked.go
kythe/go/platform/kcd/memdb/memdb.go
kythe/go/platform/kcd/testutil/testutil.go

Replace error-prone pair of string params with named struct fields

refactor(kcd): use Revision instead of string params

---

kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/testdata/df/df_unary.cc

This is a transitional change that will be reverted once
downstream users have had sufficient notice to expect
ref/writes edges.

feat(cxx_indexer): emit ref edges along with ref/writes edges

---

kythe/rust/examples/hello_world/BUILD
kythe/rust/extractor/BUILD
kythe/rust/fuchsia_extractor/BUILD
kythe/rust/indexer/BUILD
tools/rust/extra_action/BUILD
tools/rust/runfiles/BUILD

Changes the Kythe Rust targets to build with edition 2021. This does not require any code updates, but will allow us to use new Rust features in the future.

feat(rust_common): upgrade to Rust 2021 edition

---

kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/testdata/df/df_unary.cc

Reverts kythe/kythe#5091 -- transition plans have changed and this is no longer needed.

Revert "feat(cxx_indexer): emit ref edges along with ref/writes edges"

---

kythe/cxx/common/indexing/KytheGraphRecorder.cc
kythe/cxx/common/indexing/KytheGraphRecorder.h
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/docs/schema/schema.txt

We're deprecating completes and completes/uniquely in favor of
a simpler, completely semantic edge. This new edge also has the
advantage of reducing fanout.

feat(schema): add completedby and its implementation in C++

---

external.bzl
setup.bzl

Macs are (mostly) case-insensitive. A change to LLVM resulted in
a file called CXXABI.h being visible in the system search path
ahead of the actual cxxabi.h. This caused certain Abseil libraries
to fail to build as they depend on the content of that header.
This PR pushes Abseil to head (why not?), LLVM to head (as they
fixed this problem upstream), and rules_cc to head (because the
LLVM fix requires a more recent version).
Addresses #5133

fix: the mac build

---

kythe/typescript/indexer.ts
kythe/typescript/kythe.ts
kythe/typescript/testdata/generic_tvar.ts

This PR is part of the schema migration away from abs/absvars.
The TypeScript indexer will emit both the (incomplete, as it never
used abs nodes) old artifacts as well as the new artifacts.

feat(typescript_indexer): emit tvar and tparam.N

---

external.bzl
kythe/java/com/google/devtools/kythe/analyzers/java/BUILD
kythe/java/com/google/devtools/kythe/common/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/shared/BUILD
third_party/BUILD

While we don't use Flogger in such a vulnerable way (we only use the system backend, not log4j), update to a version of flogger which addresses the issue as well.
Also, use the maven version rather than building from source.

chore: update Flogger and use Maven version

---

kythe/go/extractors/cmd/gotool/Dockerfile

The current debian version gives an error when building the docker image. Update explicitly to 1.17
Error:
```
ERROR:
.../go/extractors/cmd/gotool/BUILD:20:13:
Executing genrule //kythe/go/extractors/cmd/gotool:docker failed: (Exit
100): bash failed: error executing command /bin/bash -c ... (remaining 1
argument(s) skipped)
The command '/bin/sh -c apt-get update &&     apt-get install -y
parallel &&     apt-get clean' returned a non-zero code: 100
Sending build context to Docker daemon  20.43MB
Step 1/8 : FROM gcr.io/cloud-builders/go:debian
---> 42247a86b532
Step 2/8 : RUN apt-get update &&     apt-get install -y parallel &&
apt-get clean
---> Running in 71129e1f967c
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security …
```

fix: update debian version in go extractor

---

external.bzl
kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/src/providers.rs

This PR upgrades the Rust toolchain to 2021-12-20 and applies clippy fixes for the new version. Unfortunately, this currently breaks the use of clippy on macOS Monterey due to issues with malloc.
See #5162 for tracking this issue

fix(rust_common): clippy fixes for new Rust version

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/recursive_type_visitor.h
kythe/cxx/indexer/cxx/testdata/basic/using_declaration_ref.cc
setup.bzl

Good news: Upstream clang seems to have added better support for tracking types found via using declaration.
Bad news: That broke some tests ;-)

chore(cxx_indexer): update LLVM

---

kythe/go/extractors/cmd/gotool/gotool.go
kythe/go/extractors/govname/govname.go
kythe/go/extractors/govname/govname_test.go

This will be used in our extraction of repos for the oss pipeline, where we want all extracted items to be assigned to the main/default corpus.

feat(go extractor): add flag to put deps in default corpus

---

kythe/proto/analysis.proto

This created confusion for our team. Moving the comment closer to the definition of the `value` field, and using backticks makes it somewhat clearer what the comment is referring to.

docs: clarify that "value" is the `value` field and not the message's value

---

kythe/go/extractors/cmd/gotool/analyze_packages.sh
kythe/go/extractors/cmd/gotool/readme.md

* additional checks for required environment variables
* only handles one top-level go package
* automatically gather deps using `go mod vendor` (requires the
extracted go package to use modules)
This change is currently running in the :latest version of the golang-extractor image, which we're using for our go builds on GCB

fix(go extractor image): updates for extracting to a single corpus

---

kythe/cxx/indexer/cxx/testdata/basic/decltype_auto.cc
setup.bzl

Unlike the generic `decltype(expr)` `decltype(auto)` is a special-case of `AutoTypeLoc` and, importantly, can't contain arbitrary expressions.  We fixed the former by only decorating the `decltype` keyword to avoid potentially conflicting decorations within the expression body along with a general distaste for anchors which may span lines (not forbidden, but often not handled well by UIs).  `decltype(auto)` doesn't have those problems so just decorate the entire thing and update the test.
If desired, however, I can make the behavior consistent between `decltype(auto)` and `decltype(expr)`

chore: update LLVM and fix tests

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/basic/decltype_auto.cc
setup.bzl

Upstream (and internal) clang reverted the change for which I had updated the tests.  As a result, they now fail.  This CL reverts the test change and adds code to keep the `decltype(auto)` range consistently over only `decltype` even when the upstream change is re-landed.  This keeps `decltype(expr)` and `decltype(auto)` consistent.

chore: update LLVM yet again and robustify test fixes

---

kythe/rust/indexer/tests/providers.rs

Other uses of `rlocation` have the path at the start of the argument. This PR updates this test's usage of `rlocation` to make to match, making text replacement of the path prefix simple.

chore(rust_indexer): change test to make text replacement easier

---

external.bzl

fix(rust_common): update Rust toolchain to fix tests on macOS Monterey

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/df/df_operatoreq.cc
kythe/cxx/indexer/cxx/testdata/df/df_operatorpluseq.cc
kythe/cxx/indexer/cxx/testdata/df/df_operatorplusplus.cc

We make the assumption that users do not abuse operator definitions.
That is, one can trust that `operator=` is an assignment;
operators of the flavor `+=` are assignments with an additional
dependency on the value being assigned.

feat(cxx_indexer): support r/w and influence for user-defined operators

---

kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexerConfig.java
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/AnnotationComments.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Comments.java

* leave a configuration knob to preserve existing behavior to emit doc nodes for non-javadoc comments
* update and re-enable doc node tests

fix(java): do not emit doc nodes for non-javadoc commits by default

---

kythe/rust/indexer/BUILD
kythe/rust/indexer/src/bin/bazel/main.rs
kythe/rust/indexer/src/bin/proxy/main.rs
kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/src/indexer/mod.rs

Open Source Code Search has a strange bug where, occasionally, anchors for cross-references can be clickable even when the definition node (including an anchor node) for the target of the cross reference does not exist. Clicking the cross reference anchor brings up the References panel which shows an error because the definition node does not exist (we don't index the Rust standard library, so we can't emit definition nodes and anchors for it). An example of this is here: https://cs.opensource.google/fuchsia/fuchsia/+/main:src/connectivity/network/dns/src/main.rs;l=30;bpv=0;bpt=1 (hover over the "std" and try clicking on it)
This PR adds an optional flag to the Rust indexer that disables emitting any cross references to the standard library, which should mitigate this issue.

feat(rust_indexer): add flag to disable emitting xrefs for stdlib

---

.bazelrc

`auth_enabled` and `project_id` have been renamed.  `remote_download_minimal` is an experiment to see if it helps.

chore: update bazel remote flags

---

kythe/cxx/indexer/proto/file_descriptor_walker.cc
kythe/cxx/indexer/proto/file_descriptor_walker.h

Builtins and maps don't point anywhere useful, so omit emission entirely.

fix(proto_indexer): elide references to builtins and maps

---

third_party/llvm/src/cxx_extractor_preprocessor_utils.cc

This makes us a bit more robust to future Clang changes in this interface. Specifically: https://github.com/llvm/llvm-project/commit/00cd6c04202acf71f74c670b2dd4343929d1f45f

chore: change how preprocessor_utils iterates tokens

---

kythe/extractors/openjdk11/extract/extract.go

Fix for the now-defunct javac9 extractor path in the OpenJDK11 extraction rules.

fix(extraction): fix javac9 extractor path

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/interface.ts

This change emits `ref` edges from properties on object literals and destructuring to fields of the corresponding types, if type is known. Example:
```typescript
interface Person {
name: string;
}
const p: Person = {name: 'Alice'};
const {name} = p;
```
With this change there will be two new `ref` edges from `name` properties in object literal and destructuring to `Person.name` field. 
This change supports object literals returned from functions, passed as function arguments and type casting. See examples in `testdata/interface.ts` test. It doesn't support more tricky cases that require deeper type checking, for example the following case won't have refs:
```typescript
const p: Person = isAlice ? {name: 'Alice'} : {name: 'Bob'};
```

feat(typescript_indexer): emit edges from object literals to corresponding types

---

.bazelrc

Using `--remote_download_minimal` results in built targets not being saved locally, so `--remote_download_toplevel` is the better choice for development. We could still potentially use `--remote_download_minimal` in the Pre-Submit if we wanted to.

fix(chore): switch to toplevel for rbe downloads

---

kythe/cxx/verifier/verifier.cc
kythe/cxx/verifier/verifier.h
kythe/cxx/verifier/verifier_main.cc

For even simple code the resulting graph can be pretty daunting.  While there are definitely circumstances which call for viewing that graph in all its glorious complexity, it makes producing minimal representations quite challenging.  These minimal representations aid in understanding the specific corner of the graph being investigated without all of the associated clutter.
This PR adds a `--minimal_graphviz` which includes only the nodes bound to goals and the edges between them.

feat(verifier): add a flag to elide nodes not bound as goals

---

kythe/docs/schema/schema.txt
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Interfaces.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/package-info.java

This PR makes it easier to distinguish actual Java annotation use sites from other places those annotations are used.

feat(java_indexer): use ref/id in annotation utterance contexts

---

kythe/cxx/verifier/BUILD
kythe/cxx/verifier/pretty_printer.cc
kythe/cxx/verifier/pretty_printer.h
kythe/cxx/verifier/verifier.cc
kythe/cxx/verifier/verifier.h
kythe/cxx/verifier/verifier_main.cc

This adds two additional verifier flags which control removing the `/kythe/(edge/)?` prefix and hiding node VNames when dumping graphviz graphs.  This results in much more compact and readable graphs (to say nothing of the dot file itself).
This also incidentally updates the PrinterPrinter interface to use absl::string_view instead of `const std::string&`

feat(verifier): allow simplifying graph output data

---

kythe/cxx/verifier/assertions.cc
kythe/cxx/verifier/verifier.cc

Include the `@` directly in captured anchor labels and don't filter out EVar-typed labels when printing.  Without this the label to which an anchor may be bound via `=` was excluded, e.g.
```
//- ThingAnchor=@Thing ref ThingRef
Thing _;
```
The resulting graph labels would skip "ThingAnchor".  If these labels are included, it's hard to distinguish the "@"-bound label, so move that into the label itself rather than just when printing.

fix(verifier): include @ in anchor labels and support EVars

---

kythe/typescript/indexer.ts
kythe/typescript/kythe.ts
kythe/typescript/testdata/interface.ts

It also affects object literal properties that reference inteface fields.
Those should use `override` instead but it requires extra work and will
be done as follow up.

feat(typescript_indexer): use ref/id for destructuring variables

---

kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/textproto/testdata/textproto_verifier_test.bzl
tools/build_rules/verifier_test/BUILD
tools/build_rules/verifier_test/cc_indexer_test.bzl
tools/build_rules/verifier_test/indexer.sh.in
tools/build_rules/verifier_test/java_verifier_test.bzl
tools/build_rules/verifier_test/jvm_verifier_test.bzl
tools/build_rules/verifier_test/kzip_archive.bzl
tools/build_rules/verifier_test/verifier_test.bzl

This adds a generic mechanism where rules can opt to have indexing run at test time, rather than build time.  It's a bit awkward, but means that the indexer can be built in the target configuration (opt, sanitizers, etc.) rather than just the host configuration.  It also potentially means that coverage data can be collected (but I've not looked in to that yet).

feat(tests): switch c++ verifier tests to index at test time

---

kythe/go/extractors/cmd/gotool/analyze_packages.sh

In some customer go corpuses, it is customery to do `go mod vendor`
and check-in the vendor directory.  This may be due to accessing
protected vendor code.  So, support skipping 'go mod vendor' during
analyze_packages upon a envrionment variable.
ENV variable: KYTHE_SKIP_MOD_VENDOR set to one of values: ('1', 'True' or 'true')
Testing:
- Built golang-extracter docker image
- Ran the image on a sample corpus with KYTHE_SKIP_MOD_VENDOR env var set
- Ensured that `go mod vendor` step is skipped.
- Also, `bazel build //... && bazel test //...` and ensured success.

Support skipping 'go mod vendor' invocation.

---

kythe/release/release.BUILD

Without the glob, the * doesn't actually expand.

Add a missing glob to release.BUILD

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java
kythe/java/com/google/devtools/kythe/extractors/shared/FileVNames.java
kythe/javatests/com/google/devtools/kythe/extractors/java/JavaExtractorTest.java

Before this change, java CUs don't receive a corpus if the required_inputs are not all in the same corpus. With this change, instead of assigning the empty corpus, the CU is assigned a corpus from the KYTHE_CORPUS environment variable.

feat(java extractor): use default value if corpus is ambiguous

---

kythe/rust/extractor/src/bin/extractor.rs

A [recent change](https://github.com/bazelbuild/rules_rust/pull/1332) in rules_rust changed the crate name of `rust_test` targets to be the same as the target being tested. This has broken Rust extraction for these test targets as the save_analysis file name is different from what the extractor expects.
This PR fixes the issue by searching for the file based on the crate name instead of assuming the path based on the output file name.

fix(rust_extractor): find the analysis file based on crate name

---

kythe/cxx/indexer/proto/testdata/proto_verifier_test.bzl
kythe/cxx/indexer/textproto/testdata/BUILD
kythe/cxx/indexer/textproto/testdata/generated_imports.pbtxt
kythe/cxx/indexer/textproto/testdata/imports_generated.proto

Works around https://github.com/bazelbuild/bazel/issues/7964 by calculating the proto path roots from the source file roots directly. Blech, but functional.

fix(textproto): workaround upstream proto path bug

---

tools/cpp/generate_compilation_database.sh

Since [.ycm_extra_conf.py](https://github.com/kythe/kythe/blob/master/.ycm_extra_conf.py#L35) is calling `bazel print_action` directly, [generate_compilation_database.sh](https://github.com/kythe/kythe/blob/master/tools/cpp/generate_compilation_database.sh) is only called by [clang_tidy.sh](https://github.com/kythe/kythe/blob/master/tools/clang_tidy/clang_tidy.sh#L9) and this  call is broken as `clang_tidy` does not pass a certain file path to `generate_compilation_database.sh`. 
This PR fixes this by making `generate_compilation_database.sh` generate the compilation database for the project workspace and not require a file as input.

Generate compilation database for workspace

---

kythe/go/extractors/govname/govname.go
kythe/go/extractors/govname/govname_test.go
kythe/go/extractors/govname/types.go
kythe/go/indexer/BUILD
kythe/go/indexer/cmd/go_indexer/go_indexer.go
kythe/go/indexer/emit.go
kythe/go/indexer/testdata/basic/stdliboverride.go
kythe/go/indexer/testdata/go_indexer_test.bzl

Problem: we index the go std library with the "google3/golib" corpus and the rest of go code with "google3". We want the cross-references to work between these, so std library elements in both need to have the same corpus.
For many projects we index, we want stdlib nodes to be assigned the compilation unit's corpus (enabled with --use_compilation_corpus_as_default), however in some cases we want to give stdlib items an explicit corpus so we can get cross-references to a shared instance of the std library.

feat(go_indexer): add --override_stdlib_corpus flag

---

Cargo.Bazel.lock
cargo-bazel-lock.json
kythe/rust/extractor/BUILD
kythe/rust/extractor/extractor_script.sh
setup.bzl

Bumps `rules_rust` to v0.8.1 for the latest improvements. The Cargo lock files have changes because they must be regenerated each time `rules_rust` is updated. The location of the `rustc_lib` files has changed, this is reflected in the Rust extractor script.

chore: bump rules_rust to v0.8.1

---

kythe/go/indexer/BUILD
kythe/go/indexer/cmd/go_indexer/go_indexer.go
kythe/go/indexer/emit.go
kythe/go/indexer/markedsource.go
kythe/go/indexer/testdata/basic/stdliboverride.go
kythe/go/indexer/testdata/go_indexer_test.bzl

Most of this change is a flag/option rename. The most important bit is in `rewrittenCorpusForVName()` in emit.go.
The `--override_stdlib_corpus` wasn't working as intended in google3 because it identifies stdlib nodes by the 'golang.org' corpus, but in google3, these are assigned the 'google3/golib' corpus. I renamed `--use_compilation_corpus_as_default` to `--use_compilation_corpus_for_all` to better indicate it's function, which is to change the corpus of *all* VNames (including stdlib and builtin items) at emit time to that of the compilation corpus, which is what we want for oss repos. `rewrittenCorpusForVName()` has been changed so that when `--use_compilation_corpus_for_all` is disabled, the compilation unit's corpus is only used for items that don't already have a corpus set, which …

feat(go_indexer): rework --use_compilation_corpus_as_default

---

kythe/release/bazel_rust_extractor_script.sh
kythe/release/release.BUILD

Fixes the file location and data target of `rustc_lib` in our releases. This fixes issues with our Docker image and users of the `extractor_actions` from the release.

fix(rust_common): fix rustc_lib location in release

---

kythe/java/com/google/devtools/kythe/analyzers/base/KytheEntrySets.java
kythe/java/com/google/devtools/kythe/analyzers/java/JavaEntrySets.java

when use_compilation_corpus_as_default is enabled

fix(java_indexer): assign all diagnostics a corpus

---

external.bzl

fixes Kythe breakage on Bazel CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2590#0182aec8-2815-48d9-bd7a-888e5f99d4fb

update googletest version

---

.bazelrc
.pre-commit-config.yaml
kythe/release/cloudbuild/pre-commit/Dockerfile
tools/rust/BUILD
tools/rust/rustfmt.sh

The `rustfmt` tool changes over time and our repo should always aim to use the binary related to our current version of Rust. This PR updates `tools/rust/rustfmt.sh` to use the binary included with `rules_rust`, falling back to the local version if necessary. Additionally, `.bazelrc` now configures the `rustfmt` aspect from `rules_rust` so that the checks occur automatically during builds.
The `Dockerfile` for our pre-commit cloudbuilder has been updated to ensure that the installed version of Rust matches our current toolchain, and this will need to be updated periodically. Other changes have been made to the `Dockerfile` related to our Go version, as `staticcheck` could not be installed with the version of Go available in Focal Fossa.

chore(rust_common): rustfmt improvements

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h

Further simplification of the C++ indexer node generation. Generally, Build* functions shouldn't be emitting nodes (with a few exceptions).

chore(cxx_indexer): move typedef node emission to Visit

---

kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc

An assert in `clang::NamedDecl::getName` will fire in the same

fix(cxx_indexer): fix crash when logging non-identifier names

---

kythe/go/indexer/markedsource.go

This PR fixes the generated Marked Source for Go packages. The `CONTEXT` child has only one child of it's own, so `PostChildText` is not appended. This meant that the generated qualified name for a Go package looks like `import/directorypackagename`. Changing to `PostText` ensures that the slash is appended after the directory so that the qualified name is `import/directory/packagename`.

fix(go_indexer): fix go package marked source

---

kythe/rust/extractor/src/vname_util.rs
kythe/rust/indexer/src/providers.rs

No functional changes intended.
New versions of Clippy warn about these.

rust: remove some needless borrows

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/clang_utils.cc
kythe/cxx/indexer/cxx/clang_utils.h
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/template/template_alias_tvar_alias.cc
kythe/cxx/indexer/cxx/testdata/template/template_alias_tvar_class.cc

This PR also cleans up BuildNodeIdForTemplateName, since it no longer has to dereference member templates itself.

fix(cxx_indexer): dereference member templates

---

kythe/rust/extractor/extractor_test.bzl

Set the `is_executable` flag when writing the script for the Rust extractor test. This fixes an issue where a `permission denied` error is thrown when attempting to run the test using `local_strategy` internally.

fix(rust_extractor): set extractor_test script as executable

---

kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/indexed_parent_map.h

This enables refactoring some of the places which *use* this map, without sacrificing the laziness.

refactor(cxx_indexer): move lazy parent map to a distinct type

---

external.bzl
third_party/bazel/bazel_repository_files.bzl
third_party/bazel/javac_options.BUILD

Rather than downloading all of the Bazel github repository for 2 files, download those 2 files.
This also fixes a variety of occasional issues around `bazel query` requiring repositories we don't define (because bazel does, upstream).

chore: only download selected Bazel files

---

kythe/cxx/indexer/cxx/testdata/proto/BUILD
kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
kythe/cxx/indexer/cxx/testdata/proto/enum.cc
kythe/cxx/tools/BUILD
kythe/cxx/tools/static_claim_main.cc
kythe/testdata/indexers/proto/BUILD
kythe/testdata/indexers/proto/enum.proto
tools/build_rules/verifier_test/cc_indexer_test.bzl

Turns out the generally-preferred alias isn't current annotated.

chore(cxx_indexer): add a test for protobuf enum generated code

---

kythe/java/com/google/devtools/kythe/doc/MarkedSourceRenderer.java
kythe/javatests/com/google/devtools/kythe/doc/MarkedSourceRendererTest.java

Currently you can only render a Marked Source signature as HTML. This PR adds a function to render a signature as plaintext. Also adds an associated test case.

feat(java_common): add function to render signature as plaintext

---

kythe/cxx/common/testdata/BUILD
kythe/cxx/extractor/proto/testdata/BUILD
kythe/cxx/extractor/testdata/BUILD
kythe/cxx/extractor/testdata/build_config_test.cc
kythe/cxx/extractor/textproto/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/proto/BUILD
kythe/cxx/indexer/proto/testdata/BUILD
kythe/cxx/indexer/textproto/testdata/BUILD
kythe/cxx/tools/BUILD
kythe/cxx/tools/fyi/testdata/BUILD
kythe/cxx/tools/testdata/BUILD
kythe/cxx/verifier/BUILD
kythe/cxx/verifier/testdata/BUILD

Note: because `parse_headers` isn't implemented for Bazel yet, this is only a partial solution.

chore: enable layering_check for C++

---

kythe/cxx/verifier/verifier.cc
kythe/cxx/verifier/verifier_unit_test.cc

Only flip the `is_ok` flag when not ignoring conflicting `/kythe/code` facts. Also add tests for the flag.

feat(tooling): mark conflicting /kythe/code facts as ok with ignore flag and add tests

---

kythe/cxx/indexer/textproto/analyzer.cc
kythe/cxx/indexer/textproto/testdata/schema_comments.pbtxt

"ref" was used previously, but "ref/file" is slightly more correct since the target vname is a file

fix(textproto): use ref/file for proto-file schema comments

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Annotations.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/BUILD
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Definitions.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Selectors.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/Writes.java

This PR adds support for `ref/writes` edges to the Java indexer. The edges are emitted for variables and class members. See the verifier test for a full representation of when `ref`, `ref/writes`, or both edges are emitted.

feat(java_indexer): implement ref/writes edges

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Jdk15CompatibilityShims.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Jdk9CompatibilityShims.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/JdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/ReflectiveJdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
kythe/java/com/google/devtools/kythe/platform/java/helpers/JCTreeScanner.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk15CompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/JdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/ReflectiveJdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/util/BUILD
kythe/java/com/google/devtools/kythe/util/OrderedCompatibilityService.java

Using new JRE's is easier internally than using newer Java language versions.
Add a reflective fallback implementation of the various shims.

feat(java_common): include reflective fallback for compatibility shims

---

WORKSPACE
buildenv/java/BUILD
kythe/java/com/google/devtools/kythe/analyzers/java/KytheDocTreeScanner.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD

Note: there remain a pair of test failures when running tests under JDK19, but those will be addressed in the future. This is enough to get things working for now.

feat(java_common): improve JDK19 source compatibility

---

kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileSystemProvider.java

unlike the other methods, getFileAttributeView is expected to return null, rather than throwing UnsupportedOperationException

fix(java_indexer): return null instead of throwing for unsupported attribute views

---

Cargo.Bazel.lock
cargo-bazel-lock.json
external.bzl
kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/extractor/src/bin/save_analysis.rs
kythe/rust/extractor/src/lib.rs
kythe/rust/extractor/tests/integration_test.rs
kythe/rust/extractor/tests/test.rs
kythe/rust/indexer/src/bin/proxy/main.rs
kythe/rust/indexer/src/indexer/analyzers.rs
kythe/rust/indexer/src/providers.rs
kythe/rust/indexer/src/writer.rs

This PR updates the Rust version to 2022-12-21. The following changes were made to support this version:
- This version includes changes to how the save_analysis API is called so the extractor was refactored to support this.
- Format strings were refactored to use variable names inline if possible. This is in line with new default Clippy lints

fix(rust_common): upgrade and address compatibility with 2022-12-21

---

Cargo.Bazel.lock
WORKSPACE
cargo-bazel-lock.json
kythe/rust/extractor/BUILD
kythe/rust/extractor/src/bin/extractor.rs
kythe/rust/extractor/tests/integration_test.rs
kythe/rust/extractor/tests/test.rs
kythe/rust/fuchsia_extractor/BUILD
kythe/rust/fuchsia_extractor/src/bin/main.rs
kythe/rust/fuchsia_extractor/src/kzip.rs

The `tempdir` crate was deprecated in [RUSTSEC-2018-0017](https://rustsec.org/advisories/RUSTSEC-2018-0017.html). We have been told to migrate to `tempfile` since it is the official replacement.

fix(rust_common): migrate from tempdir crate to tempfile

---

kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java

The paths for these file objects changes from e.g. `/modules/java.base/java/io/Serializable.class` to `/java.base/java/io/Serializable.class` in an upcoming version, breaking the existing regex.
This change instead tests for a location whose name starts with `SYSTEM_MODULES`. The location instance for these file objects is not one of the `StandardLocations` constants, it's a custom subclass, but the name reliably starts with `SYSTEM_MODULES`.

Adjust test for file objects in the system module path

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac-wrapper.sh
kythe/release/release_test.sh

This also changes the use of KYTHE_JAVA_RUNTIME_OPTIONS because you can't actually export an array to a bash script, it will just be a single-element array with the entire value, which isn't actually useful.
It would be nice if Java was less ... Java about this, but I don't know of any better solutions.

chore: fix release_test java failures

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/dynamic_import_group/import.ts
kythe/typescript/testdata/dynamic_import_group/module.ts

This is a partial support for dynamic imports. In example like 
```typescript
const {StuffDoer} = await import('./module');
```
`./module` is now referencing the file module.ts. But `StuffDoer` isn't yet referencing the original definition.

feat(typescript_indexer): support dynamic imports (ref to modules only)

---

kythe/cxx/indexer/cxx/testdata/BUILD
kythe/cxx/indexer/cxx/testdata/tvar_template/template_rec_inherit.cc

Note that this doesn't work with the experimental_alias_template_instantiations

chore(cxx_indexer): add a test for template instantiation as a base

---

kythe/java/com/google/devtools/kythe/platform/shared/filesystem/CompilationUnitFileAttributes.java

Building all of our Java with `USE_BAZEL_VERSION=last_green` reveals this to be the last such failure with new bazel.
Fixes #5516

chore: fix ErrorProne checks only triggered in HEAD bazel

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts

This is necessary to add more options in future. Currently each options requires new method argument and that hurts readability.
Also using this opportunity modify a bit API of index() function and plugins. Now we pass files to index as explicit `paths` array rather than it being part of IndexerHost. That way index methods are a bit easier to understand of *what* exactly they need to index.
Note: this change will require some google3 changes as it's changing arguments of index() method and there are few users. Changes should be trivial: converting list of arguments to an object.

chore(typescript_indexer): consolidate indexer options in a single object

---

kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h

Some anchors (e.g. the extra anchors bind to artificial semantic nodes generated by TF library plugin) don't need to be stamped.

chore(cxx_indexer): Add optional flag to emit binding with un-stamped anchors

---

kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/testdata/alternate_platform_test.cc
kythe/cxx/extractor/testdata/build_config_test.cc
kythe/cxx/extractor/testdata/extract_transcript_test.cc
kythe/cxx/extractor/testdata/has_include_test.cc
kythe/cxx/extractor/testdata/indirect_has_include_test.cc
kythe/cxx/extractor/testdata/installed_dir_test.cc
kythe/cxx/extractor/testdata/main_source_file_env_dep_test.cc
kythe/cxx/extractor/testdata/main_source_file_no_env_dep_test.cc
kythe/cxx/extractor/testdata/metadata_test.cc
kythe/cxx/extractor/testdata/modules_test.cc
kythe/cxx/extractor/testdata/root_directory_test.cc

There is some argument to be made that this logic should (also?) go in the indexer as the indexer should always process the primary source file, regardless of claiming, but we already have a facility for this in the extractor and just need to change one place so that the primary source file is always processed.
Background: when using dynamic claiming, prospective claims are issued with a timeout, but if a given compilation unit abandoned midway through indexing it can sometimes be retried before the previous prospective claims have expired, thus skipping files which it should index.  While this is problematic for header files as well, it is most troublesome for source files which are unlikely to be indexed at all as a result. Header files may potentially be included by another compilation …

fix(cxx_extractor): the main source file should be marked always_process

---

kythe/cxx/common/protobuf_metadata_file.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/testdata/proto/proto_semantic.cc

This PR supports marking writes to decls marked with kTakeAlias semantics (that may have indirect targets, as in proto fields). Materially, this means that in:
`*m->mutable_foo() = 4;`
`mutable_foo` will ref/write the proto field `foo` directly. In contrast, `m->mutable_foo()` on its own (e.g., not as the head of an lexpression) will only be marked as a simple ref of `foo`.
Handling decls with marked semantics and exprs with marked semantics appears to be converging somewhat and could do with a little refactoring. Part of the trouble is that different information about the context is available at different times (like when traversing through assignment versus visiting a declref at a leaf). One wonders how much longer we have until we end up with more than one and a half phases (maybe once …

feat(cxx_indexer): support kTakeAlias semantics in simple alias exprs

---

kythe/cxx/indexer/proto/file_descriptor_walker.cc
kythe/cxx/indexer/proto/proto_analyzer.cc
kythe/cxx/indexer/proto/source_tree.cc

newer versions of protobuf do no export this header and most of the functions which exist therein are questionable anyway.

chore: remove uses of map_util.h

---

kythe/go/util/riegeli/riegeli_test.go
kythe/go/util/riegeli/writer.go

Internally, Riegeli wants to switch to a different API for the generated protobuf code, but that API isn't available externally yet.  This PR changes the internal use of those protocol buffers so that they are easier to transform during imports.

chore: make it easier to transition Riegeli proto APIs

---

external.bzl
kythe/cxx/common/BUILD
kythe/cxx/common/file_vname_generator_test.cc
kythe/cxx/common/kythe_uri_test.cc
kythe/cxx/extractor/testdata/BUILD
kythe/cxx/extractor/testdata/alternate_platform_test.cc
kythe/cxx/extractor/testdata/build_config_test.cc
kythe/cxx/extractor/testdata/extract_transcript_test.cc
kythe/cxx/extractor/testdata/has_include_test.cc
kythe/cxx/extractor/testdata/indirect_has_include_test.cc
kythe/cxx/extractor/testdata/installed_dir_test.cc
kythe/cxx/extractor/testdata/main_source_file_env_dep_test.cc
kythe/cxx/extractor/testdata/main_source_file_no_env_dep_test.cc
kythe/cxx/extractor/testdata/metadata_test.cc
kythe/cxx/extractor/testdata/modules_test.cc
kythe/cxx/extractor/testdata/root_directory_test.cc
kythe/cxx/extractor/testlib.cc
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc

While we wait for an official release of them, use an unofficial port to clean up some uses of DebugString and ad-hoc partial re-implementations of the equivalent matchers.

chore: use port of protobuf gMock matchers

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/tsx.tsx

This avoids noisy TODOs currently emitted for TSX files. Overall I'm not sure if there is value in outputting nodes for DOM attributes in tsx files. But given it was already implemented - I just fixed what already exists.

feat(typescript): emit code nodes for tsx attributes

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts
kythe/typescript/testdata/imports_group/import.ts

This PR adds flag that allows follow aliases when retrieving TS symbols for nodes in AST. It relies on TS API and should work well and support multiple levels of aliases.
This fixes bug where today xref is not produced for the following case:
```ts
// a.ts
export const value = 42;
// b.ts
export {value} from './a';
// c.ts
import * as b from './b';
b.value;
```
Previously there were no xref from `b.value` to `value` definition. Now there is. 
Also it will help to get rid of our custom alias collapsing that uses `localSymbolToRemoteReassignMap` once launched. I didn't know that I could achieve the same result using TS API when I implemented it originally.

feat(typescript): add flag follow aliases when emitting refs

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/object.ts

Also refactors code a bit:
*  Exit early when vname is undefined as lot's of logic depends on vname being present. 
* Consistently use `ts.is*` functions.

feat(typescript): add ref/id edges for shorthands

---

tools/git/test-affected-targets.sh

This avoids considering the dependencies of `manual` and similar targets, which avoids issues with local-only dependencies of those targets, rather than just merely excluding them after the fact.

fix(presubmit): omit manual targets from both input and output sets

---

kythe/cxx/extractor/cxx_extractor.cc

The extractor will refuse to load pch/modules if they are built from a different libclang than the extractor binary. This is not ideal. Of course, there may be breaking changes in the pch format, but it's not unreasonable to assume that these changes happen less than daily. (Initial impressions hold that we still need to get around this problem to read even simple file content from a pch.)
This PR disables pch validation. Since we don't officially support builds that require pch/modules yet, the danger here is that we crash on a bad or incompatible (or actually corrupt) pch instead of quitting nicely with a diagnostic.
In service of #5543.

fix(cxx_extractor): don't validate pchs

---

kythe/cxx/indexer/cxx/IndexerFrontendAction.h

It's #5571 for the indexer. In production, the extractor and indexer are unlikely to have been built with the same libclang.
In service of #5543.

fix(cxx_indexer): don't validate pchs

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts

The flag was launched in Google so flipping it to true in indexer and removing.

chore(typescript): cleanup alias following flag

---

.bazelrc
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
tools/build_rules/selects.bzl

When selecting on JDK version compatibility, use a more permissive version of selects.with_or which only keeps unique values in tuple-valued keys and omits falsy keys entirely.  This should allow simplifying the import to replace unsupported JDK versions with an empty string without breaking all the things.

feat(build): add and use permissive wrapper for select.with_or

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/Jdk15CompatibilityShims.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/Jdk9CompatibilityShims.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/ReflectiveJdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk15CompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk20CompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk9CompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/ReflectiveJdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/util/BUILD
kythe/java/com/google/devtools/kythe/util/OrderedCompatibilityService.java

Also update    the maxVersion on  kythe/java/com/google/devtools/kythe/platform/java/helpers/Jdk15CompatibilityShims.java to indicate that it does not support JDK20

feat(java_common): update shims to more clearly indicated supported version

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts
kythe/typescript/testdata/schema.ts

This PR changes what nodes are emitted for TS classes. Before the change for the following class:
```
class Foo {
constructor() {}
}
```
there were 3 nodes:
* `Foo#type` - node representing type of the class. 
* `Foo` - node representing value of the class.
* `Foo#type.constructor` - node representing constructor (if class an explicit constructor).
This PR merges the last two nodes into `Foo`. So after this change it will look like this:
* `Foo#type` - node representing class.
* `Foo` - node representing constructor.
Anchor for the constructor node is chosen based on whether class has an explicit constructor. 
With the new change clicking on `constructor` in the class declaration users will see all instantiations of the class.

feat(typescript): merge constructor nodes

---

kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h

Reverts kythe/kythe#5612
Is there not some other preprocessor callback that gets invoked for PCH/PCM files?

Revert "fix(cxx_indexer): find vnames for pch/pcm files"

---

kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/proto/Proto.java

note that the annotations for clearNestedMessageField were recently added internally and we will need to update our version of protobuf to get them working here

test(java): add test cases for proto-generated clearField methods

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/marked_source/class.ts
kythe/typescript/testdata/marked_source/enum.ts
kythe/typescript/testdata/marked_source/function.ts
kythe/typescript/testdata/marked_source/property.ts
kythe/typescript/testdata/marked_source/variable.ts
kythe/typescript/testdata/tsx.tsx

Instead of using `parameter`, `function`, `method` as context for marked sources we now use name of containing class/interface/enum/method.

fix(typescript_indexer): fix context in marked sources

---

kythe/go/serving/xrefs/xrefs_filter.go

Previously, uint32max, which represents the set of all pages, was being merged into the list of page indices and later used as an array index, which was out of bounds.

fix(xrefs_filter): properly merge page lists that represent allPages

---

kythe/java/com/google/devtools/kythe/platform/java/helpers/15/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/20/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/9/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
kythe/java/com/google/devtools/kythe/platform/java/helpers/ReflectiveJdkCompatibilityShimsImpl.java

Put shim implementations in different directories under the same class name so they can be included in a multijar.

chore(java_indexer): prep for multijar

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/dynamic_import_group/import.ts
kythe/typescript/testdata/dynamic_import_group/module.ts

This fixes indexing of dynamic imports where imported symbols such as classes and enums use TSNamespace.TYPE in their vnames.

feat(typescript_indexer): handle type nodes when emitting ref/id from object bindings

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/platform/shared/Metadata.java
kythe/java/com/google/devtools/kythe/platform/shared/ProtobufMetadataLoader.java

I have some proto verifier tests to exercise this, but they require the internal changes to `protoc` to be pushed to github, then included in a release, then updated in our dependencies. Merging this earlier will allow us to try this out in internally sooner.

feat(java): add semantic/generated=set facts for annotated proto accessors

---

kythe/typescript/indexer.ts
kythe/typescript/kythe.ts

At the moment TS emits 1-width spans at the beginning of the file that `defines/binding` semantic node that represents module. The new flag changes it to:
1. Emit zero-width spans so that that span is not treated as something clickable in UIs.
2. Use `defines/implicit` instead of `defines/binding`.

feat(typescript_indexer): add flag to emit zero-width spans for module nodes

---

kythe/cxx/extractor/BUILD
kythe/cxx/extractor/bazel_artifact.h
kythe/cxx/extractor/bazel_artifact_selector.cc
kythe/cxx/extractor/bazel_artifact_selector.h

This should reduce memory usage somewhat, although there are likely more gains to be had particularly during serialization.  This should incidentally reduce the size of the serialized state by removing the unused fields and using a slightly more compact format for the fields which *are* used.

fix(cxx_common): attempt to reduce memory usage of bazel artifact selector

---

kythe/cxx/extractor/bazel_artifact_selector.cc
kythe/cxx/extractor/bazel_artifact_selector_test.cc

Bazel will include partial outputs for failed targets, which we still want to collect.

fix(cxx_common): select artifacts from failed targets

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/marked_source/class.ts
kythe/typescript/testdata/marked_source/enum.ts
kythe/typescript/testdata/marked_source/function.ts
kythe/typescript/testdata/marked_source/property.ts

Given the following class
```ts
class Person {
getName(): string;
}
```
Previously marked source for the `getName` method was:
```json
{
"kind": "BOX",
"child": [
{
"kind": "CONTEXT",
"pre_text": "Person"
},
{
"kind": "BOX",
"pre_text": " "
},
{
"kind": "IDENTIFIER",
"pre_text": "getName"
}
]
}
```
After this change:
```json
{
"kind": "BOX",
"child": [
{
"kind": "CONTEXT",
"post_child_text": ".",
"add_final_list_token": true,
"child": [
{
"kind": "IDENTIFIER",
"pre_text": "Person"
}
]
},
{
"kind": "IDENTIFIER",
"pre_text": "getName"
}
]
}
```
This is closer to how it is represented in other languages (java, c++).

feat(typescript_indexer): improve marked source CONTEXT nodes

---

kythe/cxx/extractor/bazel_artifact_selector.cc
kythe/cxx/extractor/bazel_artifact_selector.h

Not exactly a bug fix, but there are some internal tests which care about this.
Specifically, the contract of this API is that each file will be selected for at least one target which contains it, not every target, so either behavior is correct.

chore: count file references to select duplicate files in some cases

---

kythe/java/com/google/devtools/kythe/platform/java/BUILD
kythe/java/com/google/devtools/kythe/platform/java/JavaCompilationDetails.java
kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java
kythe/javatests/com/google/devtools/kythe/platform/java/BUILD
kythe/javatests/com/google/devtools/kythe/platform/java/OptionsTest.java

If the -source flag is set to a version below our minimum supported version, change the flag to our minimum supported version and try to index the CU. java flag behavior may have changed between the source version requested and the one we replace it with, but the alternative is to immediately fail indexing when the Java APIs throw an exception or return an error when they are aware of the unsupported -source version.

feat(java_indexer): try to handle unsupported -source flags

---

kythe/typescript/BUILD
kythe/typescript/README.md
kythe/typescript/indexer.ts
kythe/typescript/plugin_api.ts
kythe/typescript/test.ts

Inputs such as CompilationUnit, IndexerHost and others as well as Plugin interface are moved to `plugin_api.ts`. 
This way it's easier for plugin developers to see what API is and what they have access to. Additionally it allows for further splitting `indexer.ts` into sub files as currently that file is almost 3k lines.
Additionally reworks `indexer.ts` to introduce TypescriptIndexer plugin which is a main plugin that indexes TS files. By doing  that we make sure that Plugin interface provides enough capabilities for proper indexing.
This PR will require a bunch of changes in google3 as other TS plugins import interfaces that were moved to `plugin_api.ts`. But it should be trivial to update imports to point at the new file.

chore(typescript_indexer): extract plugin API to a separate file

---

kythe/typescript/indexer.ts
kythe/typescript/test.ts

This will allow to sync refactoring #5684 to google3 without the need to update all in the same change. I'll update users once this is in.

chore(typescript_indexer): temporarily re-export plugin API from indexer.ts

---

kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl
tools/build_rules/verifier_test/cc_indexer_test.bzl

cc_indexer allows passing a different indexer binary, which we'll use internally for testing proto static reflection
cc_deps allows additional c++ deps to the file being tested, which we'll also be using for testing proto static reflection
Note that there may be a better way to make the changes to cc_indexer_test.bzl. It seems when `allow_files` is set to a list of allowed extensions, the `providers` list is ignored and cc_library targets are not allowed to be passed. Setting `allow_files = True` works around this.

feat(proto_verifier_test): add cc_deps and cc_indexer parameters

---

kythe/cxx/indexer/cxx/testdata/proto/cc_proto_verifier_test.bzl

due to the potential for conflicting aspects/actions, this is an option that should be set globally, not on a per-test basis

fix(proto_verifier_test): remove proto static reflection option

---

kythe/extractors/bazel/Dockerfile

The old versions are no longer available in the base image we're using (`debian:stable-slim`).

fix(bazel_extractor): update clang and openjdk packages in docker image

---

.bazelrc
buildenv/java/BUILD
external.bzl
kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/15/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/21/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/ReflectiveJdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/15/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/21/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/9/JdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/BUILD
kythe/java/com/google/devtools/kythe/platform/java/helpers/JdkCompatibilityShims.java
kythe/java/com/google/devtools/kythe/platform/java/helpers/ReflectiveJdkCompatibilityShimsImpl.java
kythe/java/com/google/devtools/kythe/util/OrderedCompatibilityService.java
setup.bzl

While https://github.com/bazelbuild/bazel/pull/18742 prevents testing this change, it lays the necessary groundwork for addressing incompatibilities introduced in JDK21

chore(java_indexer): prepare for JDK21 incompatibilities

---

kythe/extractors/bazel/Dockerfile

Without this, we were getting some weird dependency issues when trying to install repo-specific packages.

fix(bazel_extractor): run apt-get upgrade in docker image

---

kythe/typescript/indexer.ts

All usages in google3 were migrated to import symbols from `plugin_api.ts`

chore(typescript_indexer): stop re-exporting symbols from index.ts

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/imports_group/module.ts
kythe/typescript/testdata/schema.ts

The flag has been launched in google3 for a few months now.

chore(typescript_indexer): cleanup emitZeroWidthSpansForModuleNodes flag

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts
kythe/typescript/testdata/enum.ts

Adds `childof` edges for class/interface properties and enum members.

fix(typescript_indexer): improve `childof` coverage

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts

This fixes the following scenario:
```typescript
class One { 
doStuff() {}
}
class Two extends One {}
class Three extends Two {
override doStuff() {}
}
```
Previously TS indexer didn't emit `overrides` edge between `doStuff` methods. Now TS indexer traverses all parent class chain until it finds a class/interface that contains method in question or until it reaches base class/interface.

fix(typescript_indexer): emit `overrides` edges for methods that are 2+ levels away

---

kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/JavacWrapper.java

This class works for Java 9 and later. Seeing Javac9 in the class name can be misleading

chore: rename class

---

kythe/release/cloudbuild/pre-commit/Dockerfile

`honnef.co/go/tools/cmd/staticcheck@latest` requires go 1.19, so I updated that...
ubuntu 22.04 doesn't have go 1.19, so I updated that to 23.04...
ubuntu 23.04's python setup doesn't allow globally installing packages with pip, so I setup a virtual environment...
I think everything is working now

chore(pre-commit): update docker image so that it builds

---

kythe/typescript/indexer.ts

This is required for internal upgrade. I'm still figuring out how to fix/reproduce this issue in github repo.

chore(typescript_indexer): add ts-ignore for upcoming TS 5.1 upgrade

---

kythe/extractors/bazel/Dockerfile
kythe/extractors/bazel/extract.sh

This PR adds a new line to `extract.sh` to fix potentially broken packages after `apt upgrade` is run. It also adds a new line to the Dockerfile to block the installation of `usrmerge` and `usr-is-merged` as `usrmerge` cannot run inside a Docker image, `usr-is-merged` will complain that `usrmerge` hasn't been run, and Debian haven't started shipping stable Docker containers that have already been merged.

fix(extraction): fix Dockerfile and extraction script

---

kythe/cxx/indexer/cxx/GoogleFlagsLibrarySupport.cc
kythe/cxx/indexer/cxx/GoogleFlagsLibrarySupport.h
kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc
kythe/cxx/indexer/cxx/ImputedConstructorSupport.h
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/IndexerASTHooks.h
kythe/cxx/indexer/cxx/IndexerLibrarySupport.h
kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc
kythe/cxx/indexer/cxx/ProtoLibrarySupport.h

Remove some API vestiges from the existence of `abs` nodes.  This will be a breaking change on import for internal users of the plugin API, but should be a straightforward fix. It also corrects some mistakes in the plugin API by passing the NodeId parameters by `const&` instead of non-const.
`abs` delenda est.

chore: excise vestiges of abs nodes from API

---

kythe/cxx/indexer/cxx/GraphObserver.h

There's no reason to provide write-access to the LangOptions (unlike Preprocessor and SourceManager)

chore: only provide const access to GraphObserver::LangOptions

---

kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/IndexerASTHooks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h
kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc

Class members should not have their definitions provided by unrelated source files, so move NullGraphObserver::kTokenClaimClass out of IndexerASTHooks.cc and into an inline constant in the class itself.
Change the opaque identifier from being a `void*` (which comes with the usual issues around `const` safety) and use the more suitable `uintptr_t` type.  While these *could* be pointers, they are more reasonably just an opaque nonce.
Finally, move the nonce definition from being the address of the nonce at point-of-use, to doing the same within the definition of the nonce directly to avoid potential mistakes.

chore: move the NullGraphObserver token inline and use non-pointer opaque type

---

kythe/cxx/indexer/cxx/decl_printer.cc
kythe/cxx/indexer/cxx/decl_printer_test.cc

They tell me binding a reference to a null pointer is bad.

fix(cxx_indexer): properly handle dependent using decl names 

---

kythe/cxx/common/file_vname_generator.cc
kythe/cxx/common/re2_flag.cc
kythe/cxx/indexer/proto/file_descriptor_walker.cc
kythe/cxx/indexer/textproto/analyzer.cc
kythe/cxx/verifier/assertions.cc

`re2::StringPiece` is just an alias for `absl::string_view` these days.

chore: convert re2::StringPiece to absl::string_view

---

kythe/extractors/BUILD
kythe/release/release.BUILD
setup.bzl
third_party/protobuf-nowkt.patch

This PR adds a patch for the protobuf repository that includes the changes from https://github.com/protocolbuffers/protobuf/commit/5b6c2459b57c23669d6efc5a14a874c693004eec to expose `protobuf_nowkt` and updates the `proto_lang_toolchain` for the C++ protobuf toolchain to work with newer versions of protobuf. This will fix issues with extracting the Kythe GitHub repo once a new version of the bazel-extractor Docker container is built with this change included.

fix(cxx_extractor): fix cc proto_lang_toolchain

---

kythe/release/release.BUILD

Same change as #5843 but in the BUILD file used in the release

fix(cxx_extractor): fix cc proto_lang_toolchain in release.BUILD

---

kythe/java/com/google/devtools/kythe/platform/java/helpers/JCTreeScanner.java
setup.bzl

Note: I can't actually test this with JDK21 as Turbine still barfs (https://github.com/bazelbuild/bazel/issues/18743)
It's possible we "just" need to update rules_java, but I'm running into issues with ErrorProne in attempting that 🤷, so will do so in a future PR.

fix(java_indexer): use extant JDK21 shim in one more place

---

kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/path_utils.cc
kythe/cxx/extractor/path_utils.h
kythe/cxx/indexer/cxx/GraphObserver.h
kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.cc
kythe/cxx/indexer/cxx/KytheGraphObserver.h
kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc
kythe/cxx/indexer/cxx/KytheVFS.cc
kythe/cxx/indexer/cxx/KytheVFS.h
kythe/cxx/tools/fyi/fyi.cc
setup.bzl

While I'm sure there exist more places which can/should be migrated to `FileEntryRef`, this at least hits all the blockers.

chore(cxx_common): update LLVM w/ concomitant FileEntryRef migration

---

kythe/cxx/indexer/cxx/testdata/BUILD

This had been enabled internally, but was overwritten by the latest import.

chore: enable the fast solver on two slow tests

---

kythe/cxx/extractor/CommandLineUtils.cc

Remove flags aimed at the LLVM and CUDA driver when removing incompatible flags.

fix(cxx_extractor): remove inapplicable CUDA driver and LLVM flags

---

kythe/release/README.md

The binary in the latest binary release is named `cxx_indexer`, not `cxx_indexers`.

Fix typo `indexes/cxx_indexers` -> `.../cxx_indexer`.

---

external.bzl

After https://github.com/bazelbuild/bazel/commit/c7e391cc422d9069e6cbf24a09807638d352c4b0, Bazel interprets the `actual` parameter of a `bind` call in the context of the repo where it happens.
Unfortunately, this means that wrapping `native.bind` in a `maybe` macro loaded from `@bazel_tools` causes the `actual` parameter to be interpreted in `@bazel_tools`'s context, which is obviously wrong.
This is amazingly hard to fix at the root and is more evidence that `bind` needs to go.
Fixes https://github.com/kythe/kythe/issues/5921.

Do not use `bind` with a `maybe` macro

---

kythe/docs/kythes-command-line-tool.txt

When I run `kythe help --short`, I get the following:
```
flag provided but not defined: -short
help [<subcommand>]:
With an argument, prints detailed information on the use of
the specified subcommand. With no argument, print a list of
all commands and a brief description of each.
```
And the command returns status code `2`.
We should not try using the `--short` flag in our docs, it seems it was removed.

flag --short is no longer defined, remove it from docs

---

tools/build_rules/verifier_test/BUILD
tools/build_rules/verifier_test/verifier_test.bzl
tools/build_rules/verifier_test/verifier_test_impl.bzl

Move the verifier_test rule implementation to a separate file and wrap it with a macro which can set common tags. This is primarily useful internally, where tags factor in to how and which tests are run, etc.

chore(common): refactor verfier_test to a wrapper macro with common tags

---

.commitlintrc.js
README.adoc
kythe/docs/kythes-command-line-tool.txt
kythe/web/site/contributing.md
kythe/web/site/examples.md
kythe/web/site/getting-started-macos.md
kythe/web/site/index.html

I'm new to Kythe and got tripped up a bit by the documentation being a bit out of date.

Update documentation for macOS, remove references to Sample Web UI that no longer exists

---

kythe/go/extractors/bazel/extractor_test.go
kythe/go/extractors/bazel/utils.go

This allows for stripping the argument name from arguments like `--src=`

feat(extraction): allow using a capturing group with generic bazel extractor

---

kythe/cxx/indexer/cxx/IndexerASTHooks.cc

We already emit the same information when visiting the Decl node, don't do so while building the id.

chore(cxx_indexer): remove redundant emissions of node information

---

.bazelrc
kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/testdata/BUILD
kythe/cxx/indexer/cxx/BUILD
kythe/cxx/indexer/cxx/KytheIndexerMain.cc
kythe/cxx/indexer/cxx/clang_utils.cc
kythe/cxx/indexer/cxx/clang_utils.h

The final removal of `abs` nodes updated the function definition, but not the declaration.
Update the declaration, add `-Wmissing-prototypes` for Kythe targets and cleanup the remaining violations.

chore(cxx_indexer): cleanup decl/defn mismatch and enable warning

---

kythe/cxx/indexer/textproto/BUILD

Without this, my local build fails with:
```
ERROR: /usr/local/google/home/justinbuchanan/src/github/kythe/kythe/cxx/indexer/textproto/BUILD:93:11: Compiling kythe/cxx/indexer/textproto/recordio_textparser.cc failed: (Exit 1): clang failed: error executing command (from target //kythe/cxx/indexer/textproto:recordio_textparser) /usr/lib/llvm-16/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer ... (remaining 100 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from kythe/cxx/indexer/textproto/recordio_textparser.cc:17: …
```

fix(build): disable layering check so textproto indexer compiles

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts

Adds support for private `#foo` properties: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties

feat(typescript_indexer): support private fields 

---

kythe/go/extractors/cmd/gotool/analyze_packages.sh

This avoids the error:
```
fatal: detected dubious ownership in repository at '/tmp/workspace/gopath/src/golang.org/x/tools'
To add an exception for this directory, call:
git config --global --add safe.directory /tmp/workspace/gopath/src/golang.org/x/tools
```

Set safe.directory='*' on `git` call

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD

A user of this binary has had issues with glibc versioning (ours being newer than their host system's). Linking statically should resolve this.

chore(bazel_go_extractor): statically-link binary

---

RELEASES.md
kythe/release/BUILD

*   remove slog Context log calls (#6018) ([2589380b](https://github.com/kythe/kythe/commit/2589380b2cdf95da00d8030dd9605c3c15d500aa))
* **java_indexer:**  support more metadata types (#6017) ([28cf6700](https://github.com/kythe/kythe/commit/28cf6700649bf4f98aa6b96a672e18b0192e8388))
I'm cutting this now to get https://github.com/kythe/kythe/pull/6019 into a release.
Draft release at https://github.com/kythe/kythe/releases/tag/untagged-abcbd0a43a008b857c22

release: v0.0.66

---

kythe/cxx/common/BUILD
kythe/cxx/common/file_vname_generator.cc
kythe/cxx/common/file_vname_generator.h
kythe/proto/BUILD
kythe/proto/vnames_config.proto

This reifies the ad-hoc format used for vnames.json files into a Real Proto and uses that to parse the configuration in C++.

chore(cxx_common): add and use a vnames_config.proto for vname rules

---

kythe/typescript/indexer.ts

Currently only error name is logged without stacktrace. That makes it hard to debug. 
Before:
```
Plugin GeneratedCodePlugin errored: TypeError: Cannot read properties of undefined (reading 'getPath')
```
After:
```
Plugin GeneratedCodePlugin errored: TypeError: Cannot read properties of undefined (reading 'getPath')
at GeneratedCodePlugin.emitMappingEdge (.../generated_code_plugin/indexer.ts:332:36)
at GeneratedCodePlugin.emitEdges (.../generated_code_plugin/indexer.ts:170:14)
at GeneratedCodePlugin.index (.../generated_code_plugin/indexer.ts:156:14)
...
```

fix(typescript_indexer): Fully log errors from plugins.

---

kythe/go/indexer/emit.go
kythe/go/indexer/testdata/flags.go

As a reminder, flag features are gated behind the --flag_constructors flag and are considered experimental.

feat(go_indexer): add references to literal flag lookups

---

kythe/go/indexer/emit.go
kythe/go/indexer/indexer.go
kythe/go/indexer/testdata/code/rendered.go

This fixes the rendering of all interface methods since they all have at least an anonymous receiver (the interface itself).

fix(go_indexer): emit nodes for anonymous interface params

---

kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl

The to_proto and to_proto methods on struct are deprecated and will be
removed. The "json" and "proto" builtin modules should be used instead.
This replaces instances of `foo.to_proto()` with `proto.encode_text(foo)`.

Replace instances of to_proto() method with proto.encode_text(..)

---

kythe/data/simple_vnames.json

I copied this entry from vnames.json.
Before this change, extracting the kythe repo using the bazel-extractor image results in this entry in required_inputs for protos that depend on descriptor.proto:
```
"v_name": {
"corpus": "CORPUS",
"root": "bazel-out/bin/external/com_google_protobuf",
"path": "src/google/protobuf/_virtual_imports/descriptor_proto/google/protobuf/descriptor.proto"
},
```
After this change, we get:
```
"v_name": {
"corpus": "CORPUS",
"root": "bazel-out/bin",
"path": "google/protobuf/descriptor.proto"
},
```
This extraction change should fix errors we've been seeing where the indexer is unable to find descriptor.proto (or other external protos) and fails.

fix(extraction): add proto rule to simple vnames config

---

kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java
kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg/CrossFile.java

Ensure that the JVM node will have a node kind even if we never index its definition.

fix(java_indexer): emit node kinds for jvm nodes

---

tools/build_rules/verifier_test/BUILD
tools/build_rules/verifier_test/java_verifier_test.bzl

This is in preparation for the rules to be moved out of Bazel and into `@rules_java`

Add `load()`s for the Bazel builtin java rules to `.bzl` files

---

kythe/java/com/google/devtools/kythe/extractors/java/bazel/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/bazel/aspect.bzl
kythe/java/com/google/devtools/kythe/extractors/java/standalone/BUILD
kythe/java/com/google/devtools/kythe/extractors/java/standalone/aspect.bzl
tools/build_rules/verifier_test/BUILD
tools/build_rules/verifier_test/java_verifier_test.bzl
tools/build_rules/verifier_test/jvm_verifier_test.bzl

This is in preparation for the symbols to be moved out of Bazel and into `@rules_java`

Add `load()`s for the Bazel builtin java top-level symbols

---

tools/build_rules/verifier_test/verifier_test_impl.bzl

Revert "chore: build verifier_test deps in the exec configuration"

---

kythe/typescript/BUILD
kythe/typescript/indexer.ts
kythe/typescript/testdata/interface.ts

Given the following structure:
```typescript
interface Person {
name: string;
}
interface Address {
person: Person;
}
const a: Address = {person: {name: 'Alice'}};
```
Previously `name` on the last line was not connected to the `Person.name` property. This PR fixes it.

feat(typescript_indexer): support xrefs in nested object literals

---

kythe/web/site/examples.md

We need to wait for cxx_extractor's completion before returning from cxx_wrapper. This ensures the kzip is fully written before returning. Otherwise we cannot guarantee that all kzip files are ready when `make` completes. This risks losing the last few kzip files when cxx_extractor races with steps called after `make`.

Update "Extracting projects built with `make`" in examples.md

---

kythe/go/extractors/cmd/gotool/Dockerfile

Go itself requires at least 1.22.6 for bootstrapping as of https://go.dev/cl/606156. Thus it is no longer possible to use the extractor image on the Go repo.
Update to 1.23.0, as that is the latest release.
As an aside, it is unclear to me why there is a mismatch in the base image (1.20) and the installed version (1.21). gcr.io/cloud-builders/go doesn't seem to have a 1.23 tag yet.

chore(go): update go from 1.21 to 1.23 in extractor image

---

kythe/go/extractors/cmd/bazel/bazel_go_extractor/bazel_go_extractor.go

rules_go may pass the GOROOT via the `-goroot` flag instead of an environment variable since https://github.com/bazelbuild/rules_go/commit/6f206adcc9c2527a411a002669db1b7efafbeae8.

Adapt Go extractor to new -goroot flag

---

kythe/release/release.BUILD

Usage of `assign_external_projects_to_separate_corpora` along with `select` statement is causing a cyclic dependency for Bazel 8. Also not usage of flag  `assign_external_projects_to_separate_corpora` was found hence deprecating the flag. The flag was initially introduced for backward compatibility in https://source.corp.google.com/h/github/kythe/kythe/+/3966e3f7aa790a61645e6babf511f7ae21b78011.
Tested by executing bazelisk --bazelrc=$KYTHE_RELEASE_DIR/extractors.bazelrc build //src:bazel which succeeded.

fix(bazel): remove cyclic dependency by removing usage of assign_external_projects_to_separate_corpora config_setting flag

---

RELEASES.md
kythe/release/BUILD

Documentation and version change for release https://github.com/kythe/kythe/releases/tag/v0.0.68.
Followed documentation in kythe/release/setup_release.sh to generate the release.
Last release: https://github.com/kythe/kythe/pull/6058

release: v0.0.68

---

kythe/typescript/indexer.ts
kythe/typescript/testdata/class.ts

According to https://github.com/kythe/kythe/blob/master/kythe/typescript/SCHEMA.md#class-declaration static methods should get different vnames from instance methods. But currently static methods are treated as instance methods and vnames overlap. This PR fixes that.
Note that static properties already work correctly.

fix(typescript_indexer): emit correct vnames for static methods

---

kythe/go/extractors/cmd/rust/BUILD
kythe/go/extractors/cmd/rust/rust_project_to_kzip.go
kythe/go/extractors/cmd/rust/rust_project_to_kzip_test.go

Many projects using Rust with complicated build systems use rust-project.json to tell rust-analyzer about their source files. We can transform rust-project.json into a .kzip pretty trivially, without needing build system integration. This is simpler than integrating an extractor into every possible build system which large Rust projects use.
Add an extractor called rust_project_to_kzip which takes in a rust-project.json and outputs a .kzip. This kzip will have one CompilationUnit per Rust crate, and each CompilationUnit will include a copy of rust-project.json for the Kythe Rust indexer.
This extractor doesn't yet extract non-.rs files or the stdlib.
Test: added unit tests
Fixes #6167

[extractors] Add an extractor for rust-project.json

---

external.bzl
third_party/rapidjson_assignment.patch
third_party/souffle_atomic.patch

See #6171 
I wonder if I missed a doc somewhere that should have told me to use an earlier version of clang, but it seems we should be able to build with the latest release of clang available. 
So... fix the build with Clang 19.

Fix build with Clang 19

---

.pre-commit-config.yaml
kythe/release/BUILD
kythe/release/release.MODULE.bazel
kythe/release/setup_release.sh

The extracted Kythe release archive can now be added as a `bazel_dep` via `local_path_override`. Upon the next release, it could also be added to the Bazel Central Registry.

Add support for Bzlmod

---

kythe/cxx/indexer/proto/file_descriptor_walker.cc

See
https://github.com/protocolbuffers/protobuf/blob/main/docs/implementing_proto3_presence.md#to-iterate-over-all-oneofs
for more info.
This helps silencing some error within simple proto3 files
```
syntax = "proto3";
package moo;
message Foo {
optional int32 bar = 1;
}
```
which would yield
```
file_descriptor_walker.cc:262] Unexpected location vector [] while walking moo.proto
```
before this change.

indexer/proto: correctly visit oneof

---

RELEASES.md
kythe/release/BUILD
kythe/release/release.MODULE.bazel

I (frustratingly) forgot to add the actual built artifact of my new extractor to the release artifacts. So, do that now, and update releases.

Add rust extractor to release, cut a new release

---

kythe/go/extractors/cmd/rust/rust_project_to_kzip.go

Previously, source file entries were polluted in the cache that speeds up directory traversal. Instead of putting only a single directory's source files in the cache, we were entering the source files for (potentially) the entire crate.
Fix: only store source files for the current directory, not the whole crate.
Test: proved that Fuchsia's corpus has no more errors like "source_file does not have a required_input entry"

[fix] Correct source_file inclusion in rust extractor

---

kythe/cxx/common/path_utils.cc
kythe/cxx/common/path_utils_test.cc
kythe/cxx/extractor/cxx_extractor.cc
kythe/cxx/extractor/cxx_extractor.h
kythe/cxx/extractor/cxx_extractor_test.cc

For projects which use upward relative paths (`../<path>`), the existing PathCleaner logic was insufficient. Particularly, it would output absolute paths for inputs which were specified as ../<path>, which meant that later indexing would fail, as the `arguments` field likely referred to those inputs by their relative paths.
We address this with two fixes:
1. PathCleaner now preserves (does not modify) a relative path if it starts with ../
2. FindStableRoot now outputs the current working directory if any arguments start with ../
Many thanks to @shahms for his advice on this set of changes.
Test: Added unit tests, also verified manually that this gets the Fuchsia indexing pipeline working again
Fixes #6181

fix(cxx_extractor): preserve upward relative paths in args

---

kythe/go/extractors/cmd/gotool/Dockerfile

Update go from 1.23.0 to 1.24.4 in extractor image
PR created based on https://github.com/kythe/kythe/pull/6130/files
While https://github.com/kythe/kythe/pull/6187/checks?check_run_id=45100270116 is still in progress, extractor image upgrade does not depend on other changes and hence creating separate PR.

Update go from 1.23.0 to 1.24.4 in extractor image

---

kythe/go/extractors/cmd/gotool/Dockerfile

As of https://go.dev/cl/694535, Go itself requires 1.24.6 for bootstrapping the toolchain. Upgrade so we can run the extractor on the Go repository itself.

chore(go): update go from 1.24.4 to 1.24.6
